/*
    Staging Table: benefits
    Version: AutoCreated
    Comments: DDL created from https://app.smartsheet.com/sheets/FHw3c6hXHpQM2XhHrcFJmMpxJC3r8Cc4JPpvv3r1?view=grid
*/

/* NO LONGER SETTING UP AS AN SP
USE hellboy;     
DROP PROCEDURE IF EXISTS `sp_slng_ddl_benefits`;
-- DELIMITER $$   -- *** Comment out the delimiter declaration to load via SLNG *** -- 
CREATE DEFINER=`slng_user`@`%` PROCEDURE `sp_slng_ddl_benefits`()
  STAGING:BEGIN
*/

/*** Start of Add_Dependent_DCDD Section created from https://app.smartsheet.com/sheets/vCjR567W8m249QwmR43P46RpVP9JcRGqcRpQH9P1?view=grid ***/

DROP TABLE IF EXISTS `src_add_dependent`;
CREATE TABLE `src_add_dependent`(
  `Dependent_ID` TEXT,
  `Effective_Date` TEXT,
  `Reason_Reference_ID` TEXT,
  `Reason_Reference_ID_Type` TEXT,
  `Employee_Reference_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Existing_Related_Person_Reference_ID` TEXT,
  `Existing_Related_Person_Reference_ID_Type` TEXT,
  `Related_Person_Relationship_Reference_ID` TEXT,
  `Related_Person_Relationship_Reference_ID_Type` TEXT,
  `Use_Employee_Address` TEXT,
  `Use_Employee_Phone` TEXT,
  `Name_Detail_Data_Formatted_Name` TEXT,
  `Name_Detail_Data_Reporting_Name` TEXT,
  `Name_Country_Reference_ID` TEXT,
  `Name_Country_Reference_ID_Type` TEXT,
  `Title_Reference_ID` TEXT,
  `Title_Reference_ID_Type` TEXT,
  `Title_Descriptor` TEXT,
  `Salutation_Reference_ID` TEXT,
  `Salutation_Reference_ID_Type` TEXT,
  `First_Name` TEXT,
  `Middle_Name` TEXT,
  `Last_Name` TEXT,
  `Secondary_Last_Name` TEXT,
  `Tertiary_Last_Name` TEXT,
  `Local_Name_Detail_Data_Local_Name` TEXT,
  `Local_Name_Detail_Data_Local_Script` TEXT,
  `Local_Name_First_Name` TEXT,
  `Local_Name_Middle_Name` TEXT,
  `Local_Name_Last_Name` TEXT,
  `Local_Name_Secondary_Last_Name` TEXT,
  `Local_First_Name_2` TEXT,
  `Local_Middle_Name_2` TEXT,
  `Local_Last_Name_2` TEXT,
  `Local_Secondary_Last_Name_2` TEXT,
  `Social_Suffix_Reference_ID` TEXT,
  `Social_Suffix_Reference_ID_Type` TEXT,
  `Social_Suffix_Descriptor` TEXT,
  `Academic_Suffix_Reference_ID` TEXT,
  `Academic_Suffix_Reference_ID_Type` TEXT,
  `Hereditary_Suffix_Reference_ID` TEXT,
  `Hereditary_Suffix_Reference_ID_Type` TEXT,
  `Honorary_Suffix_Reference_ID` TEXT,
  `Honorary_Suffix_Reference_ID_Type` TEXT,
  `Professional_Suffix_Reference_ID` TEXT,
  `Professional_Suffix_Reference_ID_Type` TEXT,
  `Religious_Suffix_Reference_ID` TEXT,
  `Religious_Suffix_Reference_ID_Type` TEXT,
  `Royal_Suffix_Reference_ID` TEXT,
  `Royal_Suffix_Reference_ID_Type` TEXT,
  `Full_Name_for_Singapore_and_Malaysia` TEXT,
  `National_ID_Delete` TEXT,
  `National_ID_Reference_ID` TEXT,
  `National_ID_Reference_ID_Type` TEXT,
  `National_ID_Data_ID` TEXT,
  `National_ID_Type` TEXT,
  `National_ID_Type_Reference_ID_Type` TEXT,
  `National_ID_Country_Reference_ID` TEXT,
  `National_ID_Country_Reference_ID_Type` TEXT,
  `National_ID_Issued_Date` TEXT,
  `National_ID_Expiration_Date` TEXT,
  `National_ID_Verification_Date` TEXT,
  `National_ID_Series` TEXT,
  `National_ID_Issuing_Agency` TEXT,
  `National_ID_Verified_By_Ref_ID` TEXT,
  `National_ID_Verified_By_Ref_ID_Type` TEXT,
  `National_ID_Shared_Ref_ID` TEXT,
  `National_ID_Shared_Ref_ID_Type` TEXT,
  `Date_of_Birth` TEXT,
  `Date_of_Death` TEXT,
  `Gender` TEXT,
  `Gender_Reference_ID_Type` TEXT,
  `Uses_Tobacco` TEXT,
  `Full_Time_Student` TEXT,
  `Student_Status_Start_Date` TEXT,
  `Student_Status_End_Date` TEXT,
  `Disabled` TEXT,
  `Replace_All` TEXT,
  `Disability_Status_Reference_ID` TEXT,
  `Disability_Status_Reference_ID_Type` TEXT,
  `Disability_Delete` TEXT,
  `Disability_Reference_ID` TEXT,
  `Disability_Reference_ID_Type` TEXT,
  `Disability_Status_Date` TEXT,
  `Disability_Date_Known` TEXT,
  `Disability_End_Date` TEXT,
  `Disability_Grade_Reference_ID` TEXT,
  `Disability_Grade_Reference_ID_Type` TEXT,
  `Disability_Degree` TEXT,
  `Inactive_Date` TEXT,
  `Dependent_for_Payroll_Purposes` TEXT,
  `Citizenship_Status_Reference_ID` TEXT,
  `Citizenship_Status_Reference_ID_Type` TEXT,
  `Country_of_Nationality_Reference_ID` TEXT,
  `Country_of_Nationality_Reference_ID_Type` TEXT,
  `Country_of_Birth_Reference_ID` TEXT,
  `Country_of_Birth_Reference_ID_Type` TEXT,
  `Region_of_Birth_Reference_ID` TEXT,
  `Region_of_Birth_Reference_ID_Type` TEXT,
  `City_of_Birth` TEXT,
  `Lives_With_Worker_Effective_Date` TEXT,
  `Lives_With_Worker` TEXT,
  `Has_Health_Insurance_Effective_Date` TEXT,
  `Has_Health_Insurance` TEXT,
  `Allowed_for_Tax_Deduction_Effective_Date` TEXT,
  `Allowed_for_Tax_Deduction` TEXT,
  `Annual_Income_Effective_Date` TEXT,
  `Annual_Income_Currency_Ref_ID` TEXT,
  `Annual_Income_Currency_Ref_ID_Type` TEXT,
  `Annual_Income` TEXT,
  `Occupation_Effective_Date` TEXT,
  `Occupation` TEXT,
  `QDRO_Benefit_Coverage_Type_Ref_ID` TEXT,
  `QDRO_Benefit_Coverage_Type_Ref_ID_Type` TEXT,
  `QDRO_Start_Date` TEXT,
  `QDRO_End_Date` TEXT,
  `Could_Be_Covered_For_HC_Coverage_Elsewhere` TEXT,
  `Could_Be_Covered_For_HC_Cov_Elsewhere_Eff_Date` TEXT,
  `Dependent_Verification_Status_Reference_ID` TEXT,
  `Dependent_Verification_Status_Reference_ID_Type` TEXT,
  `Dependent_Verification_Comment` TEXT,
  `Dependent_Verification_Verification_Date` TEXT,
  `Dependent_Verification_Expiration_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_add_dependent_contact_details`;
CREATE TABLE `src_add_dependent_contact_details`(
  `Dependent_ID` TEXT,
  `Formatted_Address` TEXT,
  `Address_Data_Address_Format_Type` TEXT,
  `Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Address_Data_Delete` TEXT,
  `Address_Data_Do_Not_Replace_All` TEXT,
  `Address_Data_Effective_Date` TEXT,
  `Address_Country_Reference_ID` TEXT,
  `Address_Country_Reference_ID_Type` TEXT,
  `Address_Last_Modified` TEXT,
  `ADDRESS_LINE_1` TEXT,
  `ADDRESS_LINE_2` TEXT,
  `ADDRESS_LINE_3` TEXT,
  `ADDRESS_LINE_4` TEXT,
  `ADDRESS_LINE_5` TEXT,
  `Municipality` TEXT,
  `Country_City_Reference_ID` TEXT,
  `Country_City_Reference_ID_Type` TEXT,
  `Country_City_Reference_ID_parent_id` TEXT,
  `Country_City_Reference_ID_parent_type` TEXT,
  `Submunicipality_Data` TEXT,
  `Submunicipality_Data_Address_Component_Name` TEXT,
  `Submunicipality_Data_Type` TEXT,
  `Country_Region_Reference_ID` TEXT,
  `Country_Region_Reference_ID_Type` TEXT,
  `Country_Region_Descriptor` TEXT,
  `Subregion_Data` TEXT,
  `Subregion_Data_Type` TEXT,
  `Postal_Code` TEXT,
  `Address_Usage_Data_Public` TEXT,
  `Address_Type_Data_Primary` TEXT,
  `Address_Type_Reference_ID` TEXT,
  `Address_Type_Reference_ID_Type` TEXT,
  `Address_Use_For_Reference_ID` TEXT,
  `Address_Use_For_Reference_ID_Type` TEXT,
  `Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Address_Comments` TEXT,
  `Address_Number_of_Days` TEXT,
  `Municipality_Local` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT,
  `Address_ID` TEXT,
  `Phone_Data_Area_Code` TEXT,
  `Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Phone_Data_International_Formatted_Phone` TEXT,
  `Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Phone_Data_National_Formatted_Phone` TEXT,
  `Phone_Data_E164_Formatted_Phone` TEXT,
  `Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Phone_Data_Delete` TEXT,
  `Phone_Data_Do_Not_Replace_All` TEXT,
  `Phone_Country_ISO_Code` TEXT,
  `International_Phone_Code` TEXT,
  `Phone_Number` TEXT,
  `Phone_Extension` TEXT,
  `Phone_Device_Type_Reference_ID` TEXT,
  `Phone_Device_Type_Reference_ID_Type` TEXT,
  `Phone_Usage_Data_Public` TEXT,
  `Phone_Type_Data_Primary` TEXT,
  `Phone_Type_Reference_ID` TEXT,
  `Phone_Type_Reference_ID_Type` TEXT,
  `Phone_Use_For_Reference_ID` TEXT,
  `Phone_Use_For_Reference_ID_Type` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Phone_Comments` TEXT,
  `Phone_Reference_ID` TEXT,
  `Phone_Reference_ID_Type` TEXT,
  `Phone_Data_ID` TEXT,
  `Email_Address_Data_Delete` TEXT,
  `Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Email_Address` TEXT,
  `Email_Comment` TEXT,
  `Email_Usage_Data_Public` TEXT,
  `Email_Type_Data_Primary` TEXT,
  `Email_Type_Reference_ID` TEXT,
  `Email_Type_Reference_ID_Type` TEXT,
  `Email_Use_For_Reference_ID` TEXT,
  `Email_Use_For_Reference_ID_Type` TEXT,
  `Email_Use_For_Tenanted_Reference_ID` TEXT,
  `Email_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Email_Comments` TEXT,
  `Email_Reference_ID` TEXT,
  `Email_Reference_ID_Type` TEXT,
  `Email_Address_Data_ID` TEXT,
  `Instant_Messenger_Data_Delete` TEXT,
  `Instant_Messenger_Data_Do_Not_Replace_All` TEXT,
  `Instant_Messenger_Address` TEXT,
  `Instant_Messenger_Type_Reference_ID` TEXT,
  `Instant_Messenger_Type_Reference_ID_Type` TEXT,
  `Instant_Messenger_Comment` TEXT,
  `Instant_Messenger_Usage_Data_Public` TEXT,
  `Instant_Messenger_Type_Data_Primary` TEXT,
  `Instant_Messenger_Usage_Type_Reference_ID` TEXT,
  `Instant_Messenger_Usage_Type_Reference_ID_Type` TEXT,
  `Instant_Messenger_Use_For_Reference_ID` TEXT,
  `Instant_Messenger_Use_For_Reference_ID_Type` TEXT,
  `Instant_Messenger_Use_For_Tenanted_Reference_ID` TEXT,
  `Instant_Messenger_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Instant_Messenger_Comments` TEXT,
  `Instant_Messenger_Reference_ID` TEXT,
  `Instant_Messenger_Reference_ID_Type` TEXT,
  `Instant_Messenger_Data_ID` TEXT,
  `Web_Address_Data_Delete` TEXT,
  `Web_Address_Data_Do_Not_Replace_All` TEXT,
  `Web_Address` TEXT,
  `Web_Address_Comment` TEXT,
  `Web_Address_Usage_Data_Public` TEXT,
  `Web_Address_Type_Data_Primary` TEXT,
  `Web_Address_Type_Reference_ID` TEXT,
  `Web_Address_Type_Reference_ID_Type` TEXT,
  `Web_Address_Use_For_Reference_ID` TEXT,
  `Web_Address_Use_For_Reference_ID_Type` TEXT,
  `Web_Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Web_Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Web_Address_Comments` TEXT,
  `Web_Address_Reference_ID` TEXT,
  `Web_Address_Reference_ID_Type` TEXT,
  `Web_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_add_dependent_details`;
CREATE TABLE `src_add_dependent_details`(
  `Dependent_ID` TEXT,
  `Government_ID_Delete` TEXT,
  `Government_ID_Reference_ID` TEXT,
  `Government_ID_Reference_ID_Type` TEXT,
  `Government_ID_Data_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID_Type` TEXT,
  `Government_ID_Country_Reference_ID` TEXT,
  `Government_ID_Country_Reference_ID_Type` TEXT,
  `Government_ID_Issued_Date` TEXT,
  `Government_ID_Expiration_Date` TEXT,
  `Government_ID_Verification_Date` TEXT,
  `Government_ID_Verified_by_Reference_ID` TEXT,
  `Government_ID_Verified_by_Reference_ID_Type` TEXT,
  `Government_ID_Shared_Reference_ID` TEXT,
  `Government_ID_Shared_Reference_ID_Type` TEXT,
  `Visa_ID_Delete` TEXT,
  `Visa_ID_Reference_ID` TEXT,
  `Visa_ID_Reference_ID_Type` TEXT,
  `Visa_ID_Data_ID` TEXT,
  `Visa_ID_Type_Reference_ID` TEXT,
  `Visa_ID_Type_Reference_ID_Type` TEXT,
  `Visa_Country_Reference_ID` TEXT,
  `Visa_Country_Reference_ID_Type` TEXT,
  `Visa_Issued_Date` TEXT,
  `Visa_Expiration_Date` TEXT,
  `Visa_Verification_Date` TEXT,
  `Visa_Verified_By_Reference_ID` TEXT,
  `Visa_Verified_By_Reference_ID_Type` TEXT,
  `Visa_ID_Shared_Reference_ID` TEXT,
  `Visa_ID_Shared_Reference_ID_Type` TEXT,
  `Passport_ID_Delete` TEXT,
  `Passport_ID_Reference_ID` TEXT,
  `Passport_ID_Reference_ID_Type` TEXT,
  `Passport_ID_Data_ID` TEXT,
  `Passport_ID_Type_Reference_ID` TEXT,
  `Passport_ID_Type_Reference_ID_Type` TEXT,
  `Passport_Country_Reference_ID` TEXT,
  `Passport_Country_Reference_ID_Type` TEXT,
  `Passport_Issued_Date` TEXT,
  `Passport_Expiration_Date` TEXT,
  `Passport_Verification_Date` TEXT,
  `Passport_Verified_By_Reference_ID` TEXT,
  `Passport_Verified_By_Reference_ID_Type` TEXT,
  `Passport_ID_Shared_Reference_ID` TEXT,
  `Passport_ID_Shared_Reference_ID_Type` TEXT,
  `License_ID_Delete` TEXT,
  `License_ID_Reference_ID` TEXT,
  `License_ID_Reference_ID_Type` TEXT,
  `License_ID_Data_ID` TEXT,
  `License_ID_ID_Type_Reference_ID` TEXT,
  `License_ID_ID_Type_Reference_ID_Type` TEXT,
  `License_ID_Country_Reference_ID` TEXT,
  `License_ID_Country_Reference_ID_Type` TEXT,
  `License_ID_Country_Region_Reference_ID` TEXT,
  `License_ID_Country_Region_Reference_ID_Type` TEXT,
  `License_ID_Country_Region_Descriptor` TEXT,
  `License_Authority_Reference_ID` TEXT,
  `License_Authority_Reference_ID_Type` TEXT,
  `License_Class` TEXT,
  `License_ID_Issued_Date` TEXT,
  `License_ID_Expiration_Date` TEXT,
  `License_ID_Verification_Date` TEXT,
  `License_ID_Verified_By_Reference_ID` TEXT,
  `License_ID_Verified_By_Reference_ID_Type` TEXT,
  `License_ID_Shared_Reference_ID` TEXT,
  `License_ID_Shared_Reference_ID_Type` TEXT,
  `Custom_ID_Delete` TEXT,
  `Custom_ID_Reference_ID` TEXT,
  `Custom_ID_Reference_ID_Type` TEXT,
  `Custom_ID_Data_ID` TEXT,
  `Custom_ID_ID_Type_Reference_ID` TEXT,
  `Custom_ID_ID_Type_Reference_ID_Type` TEXT,
  `Custom_ID_Issued_Date` TEXT,
  `Custom_ID_Expiration_Date` TEXT,
  `Custom_ID_Organization_ID_Ref_ID` TEXT,
  `Custom_ID_Organization_ID_Ref_ID_Type` TEXT,
  `Custom_Description` TEXT,
  `Custom_ID_Shared_Ref_ID` TEXT,
  `Custom_ID_Shared_Ref_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Add_Dependent_DCDD Section ***/


/*** Start of Change_Beneficiary_DCDD Section created from https://app.smartsheet.com/sheets/Jvc3wq3RvHwh58vFj2MV7RFJG5HqRpRRxjq2j531?view=grid ***/

DROP TABLE IF EXISTS `src_change_beneficiary`;
CREATE TABLE `src_change_beneficiary`(
  `Discard_On_Exit_Validation_Error` TEXT,
  `Change_Beneficiary_Data_Delete` TEXT,
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Beneficiary_ID` TEXT,
  `Beneficiary_Reference_ID` TEXT,
  `Beneficiary_Reference_ID_Type` TEXT,
  `Existing_Related_Person_Reference_ID` TEXT,
  `Existing_Related_Person_Reference_ID_Type` TEXT,
  `Related_Person_Relationship_Reference_ID` TEXT,
  `Related_Person_Relationship_Reference_ID_Type` TEXT,
  `Irrevocable` TEXT,
  `Use_Employee_Address` TEXT,
  `Use_Employee_Phone` TEXT,
  `Legal_Name_Detail_Data_Formatted_Name` TEXT,
  `Legal_Name_Detail_Data_Reporting_Name` TEXT,
  `Legal_Name_Country_Reference_ID` TEXT,
  `Legal_Name_Country_Reference_ID_Type` TEXT,
  `Legal_Title_Reference_ID` TEXT,
  `Legal_Title_Reference_ID_Type` TEXT,
  `Legal_Title_Descriptor` TEXT,
  `Legal_Salutation_Reference_ID` TEXT,
  `Legal_Salutation_Reference_ID_Type` TEXT,
  `Legal_First_Name` TEXT,
  `Legal_Middle_Name` TEXT,
  `Legal_Last_Name` TEXT,
  `Legal_Secondary_Last_Name` TEXT,
  `Legal_Tertiary_Last_Name` TEXT,
  `Legal_Local_Name_Detail_Data_Local_Name` TEXT,
  `Legal_Local_Name_Detail_Data_Local_Script` TEXT,
  `Legal_Local_First_Name` TEXT,
  `Legal_Local_Middle_Name` TEXT,
  `Legal_Local_Last_Name` TEXT,
  `Legal_Local_Secondary_Last_Name` TEXT,
  `Legal_First_Name_2` TEXT,
  `Legal_Middle_Name_2` TEXT,
  `Legal_Last_Name_2` TEXT,
  `Legal_Secondary_Last_Name_2` TEXT,
  `Legal_Social_Suffix_Reference_ID` TEXT,
  `Legal_Social_Suffix_Reference_ID_Type` TEXT,
  `Legal_Social_Suffix_Descriptor` TEXT,
  `Legal_Academic_Suffix_Reference_ID` TEXT,
  `Legal_Academic_Suffix_Reference_ID_Type` TEXT,
  `Legal_Hereditary_Suffix_Reference_ID` TEXT,
  `Legal_Hereditary_Suffix_Reference_ID_Type` TEXT,
  `Legal_Honorary_Suffix_Reference_ID` TEXT,
  `Legal_Honorary_Suffix_Reference_ID_Type` TEXT,
  `Legal_Professional_Suffix_Reference_ID` TEXT,
  `Legal_Professional_Suffix_Reference_ID_Type` TEXT,
  `Legal_Religious_Suffix_Reference_ID` TEXT,
  `Legal_Religious_Suffix_Reference_ID_Type` TEXT,
  `Legal_Royal_Suffix_Reference_ID` TEXT,
  `Legal_Royal_Suffix_Reference_ID_Type` TEXT,
  `Legal_Full_Name_for_Singapore_and_Malaysia` TEXT,
  `Date_of_Birth` TEXT,
  `Date_of_Death` TEXT,
  `Gender_Reference_ID` TEXT,
  `Gender_Reference_ID_Type` TEXT,
  `Court_Order_Benefit_Coverage_Type_Reference_ID` TEXT,
  `Court_Order_Benefit_Coverage_Type_Reference_ID_Type` TEXT,
  `Court_Order_Start_Date` TEXT,
  `Court_Order_End_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_beneficiary_contact_details`;
CREATE TABLE `src_change_beneficiary_contact_details`(
  `Beneficiary_ID` TEXT,
  `Address_Data_Formatted_Address` TEXT,
  `Address_Data_Address_Format_Type` TEXT,
  `Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Address_Data_Delete` TEXT,
  `Address_Data_Do_Not_Replace_All` TEXT,
  `Address_Data_Effective_Date` TEXT,
  `Address_Country_Reference_ID` TEXT,
  `Address_Country_Reference_ID_Type` TEXT,
  `Address_Last_Modified` TEXT,
  `ADDRESS_LINE_1` TEXT,
  `ADDRESS_LINE_2` TEXT,
  `ADDRESS_LINE_3` TEXT,
  `ADDRESS_LINE_4` TEXT,
  `ADDRESS_LINE_5` TEXT,
  `Address_Line_Data_Descriptor` TEXT,
  `Address_Line_Data_Type` TEXT,
  `Municipality` TEXT,
  `Country_City_Reference_ID` TEXT,
  `Country_City_Reference_ID_Type` TEXT,
  `Country_City_Reference_ID_parent_id` TEXT,
  `Country_City_Reference_ID_parent_type` TEXT,
  `Submunicipality_Data` TEXT,
  `Submunicipality_Data_Address_Component_Name` TEXT,
  `Submunicipality_Data_Type` TEXT,
  `Country_Region_Reference_ID` TEXT,
  `Country_Region_Reference_ID_Type` TEXT,
  `Country_Region_Descriptor` TEXT,
  `Subregion_Data` TEXT,
  `Subregion_Data_Descriptor` TEXT,
  `Subregion_Data_Type` TEXT,
  `Postal_Code` TEXT,
  `Address_Usage_Data_Public` TEXT,
  `Address_Type_Data_Primary` TEXT,
  `Address_Type_Reference_ID` TEXT,
  `Address_Type_Reference_ID_Type` TEXT,
  `Address_Use_For_Reference_ID` TEXT,
  `Address_Use_For_Reference_ID_Type` TEXT,
  `Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Address_Comments` TEXT,
  `Address_Number_of_Days` TEXT,
  `Municipality_Local` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT,
  `Address_ID` TEXT,
  `Phone_Data_Area_Code` TEXT,
  `Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Phone_Data_International_Formatted_Phone` TEXT,
  `Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Phone_Data_National_Formatted_Phone` TEXT,
  `Phone_Data_E164_Formatted_Phone` TEXT,
  `Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Phone_Data_Delete` TEXT,
  `Phone_Data_Do_Not_Replace_All` TEXT,
  `Phone_Country_ISO_Code` TEXT,
  `International_Phone_Code` TEXT,
  `Phone_Number` TEXT,
  `Phone_Extension` TEXT,
  `Phone_Device_Type_Reference_ID` TEXT,
  `Phone_Device_Type_Reference_ID_Type` TEXT,
  `Phone_Usage_Data_Public` TEXT,
  `Phone_Type_Data_Primary` TEXT,
  `Phone_Type_Reference_ID` TEXT,
  `Phone_Type_Reference_ID_Type` TEXT,
  `Phone_Use_For_Reference_ID` TEXT,
  `Phone_Use_For_Reference_ID_Type` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Phone_Comments` TEXT,
  `Phone_Reference_ID` TEXT,
  `Phone_Reference_ID_Type` TEXT,
  `Phone_Data_ID` TEXT,
  `Email_Address_Data_Delete` TEXT,
  `Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Email_Address` TEXT,
  `Email_Comment` TEXT,
  `Email_Usage_Data_Public` TEXT,
  `Email_Type_Data_Primary` TEXT,
  `Email_Type_Reference_ID` TEXT,
  `Email_Type_Reference_ID_Type` TEXT,
  `Email_Use_For_Reference_ID` TEXT,
  `Email_Use_For_Reference_ID_Type` TEXT,
  `Email_Use_For_Tenanted_Reference_ID` TEXT,
  `Email_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Email_Comments` TEXT,
  `Email_Reference_ID` TEXT,
  `Email_Reference_ID_Type` TEXT,
  `Email_Address_Data_ID` TEXT,
  `Instant_Messenger_Data_Delete` TEXT,
  `Instant_Messenger_Data_Do_Not_Replace_All` TEXT,
  `Instant_Messenger_Address` TEXT,
  `Instant_Messenger_Type_Reference_ID` TEXT,
  `Instant_Messenger_Type_Reference_ID_Type` TEXT,
  `Instant_Messenger_Comment` TEXT,
  `Instant_Messenger_Usage_Data_Public` TEXT,
  `Instant_Messenger_Type_Data_Primary` TEXT,
  `Instant_Messenger_Usage_Type_Reference_ID` TEXT,
  `Instant_Messenger_Usage_Type_Reference_ID_Type` TEXT,
  `Instant_Messenger_Use_For_Reference_ID` TEXT,
  `Instant_Messenger_Use_For_Reference_ID_Type` TEXT,
  `Instant_Messenger_Use_For_Tenanted_Reference_ID` TEXT,
  `Instant_Messenger_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Instant_Messenger_Comments` TEXT,
  `Instant_Messenger_Reference_ID` TEXT,
  `Instant_Messenger_Reference_ID_Type` TEXT,
  `Instant_Messenger_Data_ID` TEXT,
  `Web_Address_Data_Delete` TEXT,
  `Web_Address_Data_Do_Not_Replace_All` TEXT,
  `Web_Address` TEXT,
  `Web_Address_Comment` TEXT,
  `Web_Address_Usage_Data_Public` TEXT,
  `Web_Address_Type_Data_Primary` TEXT,
  `Web_Address_Type_Reference_ID` TEXT,
  `Web_Address_Type_Reference_ID_Type` TEXT,
  `Web_Address_Use_For_Reference_ID` TEXT,
  `Web_Address_Use_For_Reference_ID_Type` TEXT,
  `Web_Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Web_Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Web_Address_Comments` TEXT,
  `Web_Address_Reference_ID` TEXT,
  `Web_Address_Reference_ID_Type` TEXT,
  `Web_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_beneficiary_details`;
CREATE TABLE `src_change_beneficiary_details`(
  `Beneficiary_ID` TEXT,
  `National_ID_Delete` TEXT,
  `National_ID_Reference_ID` TEXT,
  `National_ID_Reference_ID_Type` TEXT,
  `National_ID_Data_ID` TEXT,
  `National_ID_Type` TEXT,
  `National_ID_Type_Reference_ID_Type` TEXT,
  `National_ID_Country_Reference_ID` TEXT,
  `National_ID_Country_Reference_ID_Type` TEXT,
  `National_ID_Issued_Date` TEXT,
  `National_ID_Expiration_Date` TEXT,
  `National_ID_Verification_Date` TEXT,
  `National_ID_Series` TEXT,
  `National_ID_Issuing_Agency` TEXT,
  `National_ID_Verified_By_Reference_ID` TEXT,
  `National_ID_Verified_By_Reference_ID_Type` TEXT,
  `National_ID_Shared_Reference_ID` TEXT,
  `National_ID_Shared_Reference_ID_Type` TEXT,
  `Government_ID_Delete` TEXT,
  `Government_ID_Reference_ID` TEXT,
  `Government_ID_Reference_ID_Type` TEXT,
  `Government_ID_Data_ID` TEXT,
  `Government_ID_Type_Reference_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID_Type` TEXT,
  `Government_ID_Country_Reference_ID` TEXT,
  `Government_ID_Country_Reference_ID_Type` TEXT,
  `Government_ID_Issued_Date` TEXT,
  `Government_ID_Expiration_Date` TEXT,
  `Government_ID_Verification_Date` TEXT,
  `Government_ID_Verified_by_Reference_ID` TEXT,
  `Government_ID_Verified_by_Reference_ID_Type` TEXT,
  `Government_ID_Shared_Reference_ID` TEXT,
  `Government_ID_Shared_Reference_ID_Type` TEXT,
  `Visa_ID_Delete` TEXT,
  `Visa_ID_Reference_ID` TEXT,
  `Visa_ID_Reference_ID_Type` TEXT,
  `Visa_ID_Data_ID` TEXT,
  `Visa_ID_Type_Reference_ID` TEXT,
  `Visa_ID_Type_Reference_ID_Type` TEXT,
  `Visa_ID_Country_Reference_ID` TEXT,
  `Visa_ID_Country_Reference_ID_Type` TEXT,
  `Visa_ID_Issued_Date` TEXT,
  `Visa_ID_Expiration_Date` TEXT,
  `Visa_ID_Verification_Date` TEXT,
  `Visa_ID_Verified_By_Reference_ID` TEXT,
  `Visa_ID_Verified_By_Reference_ID_Type` TEXT,
  `Visa_ID_Shared_Reference_ID` TEXT,
  `Visa_ID_Shared_Reference_ID_Type` TEXT,
  `Passport_ID_Delete` TEXT,
  `Passport_ID_Reference_ID` TEXT,
  `Passport_ID_Reference_ID_Type` TEXT,
  `Passport_ID_Data_ID` TEXT,
  `Passport_ID_Type_Reference_ID` TEXT,
  `Passport_ID_Type_Reference_ID_Type` TEXT,
  `Passport_ID_Country_Reference_ID` TEXT,
  `Passport_ID_Country_Reference_ID_Type` TEXT,
  `Passport_ID_Issued_Date` TEXT,
  `Passport_ID_Expiration_Date` TEXT,
  `Passport_ID_Verification_Date` TEXT,
  `Passport_ID_Verified_By_Reference_ID` TEXT,
  `Passport_ID_Verified_By_Reference_ID_Type` TEXT,
  `Passport_ID_Shared_Reference_ID` TEXT,
  `Passport_ID_Shared_Reference_ID_Type` TEXT,
  `License_ID_Delete` TEXT,
  `License_ID_Reference_ID` TEXT,
  `License_ID_Reference_ID_Type` TEXT,
  `License_ID_Data_ID` TEXT,
  `License_ID_Type_Reference_ID` TEXT,
  `License_ID_Type_Reference_ID_Type` TEXT,
  `License_Country_Reference_ID` TEXT,
  `License_Country_Reference_ID_Type` TEXT,
  `License_Country_Region_Reference_ID` TEXT,
  `License_Country_Region_Reference_ID_Type` TEXT,
  `License_Country_Region_Descriptor` TEXT,
  `License_Authority_Reference_ID` TEXT,
  `License_Authority_Reference_ID_Type` TEXT,
  `License_Class` TEXT,
  `License_Issued_Date` TEXT,
  `License_Expiration_Date` TEXT,
  `License_Verification_Date` TEXT,
  `License_Verified_By_Reference_ID` TEXT,
  `License_Verified_By_Reference_ID_Type` TEXT,
  `License_ID_Shared_Reference_ID` TEXT,
  `License_ID_Shared_Reference_ID_Type` TEXT,
  `Custom_ID_Delete` TEXT,
  `Custom_ID_Reference_ID` TEXT,
  `Custom_ID_Reference_ID_Type` TEXT,
  `Custom_ID_Data_ID` TEXT,
  `Custom_ID_ID_Type_Reference_ID` TEXT,
  `Custom_ID_ID_Type_Reference_ID_Type` TEXT,
  `Custom_ID_Issued_Date` TEXT,
  `Custom_ID_Expiration_Date` TEXT,
  `Custom_ID_Organization_ID_Reference_ID` TEXT,
  `Custom_ID_Organization_ID_Reference_ID_Type` TEXT,
  `Custom_ID_Description` TEXT,
  `Custom_ID_Shared_Reference_ID` TEXT,
  `Custom_ID_Shared_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_beneficiary_trust`;
CREATE TABLE `src_change_beneficiary_trust`(
  `Beneficiary_ID` TEXT,
  `Trust_Name` TEXT,
  `Trust_Tax_ID` TEXT,
  `Trust_Date` TEXT,
  `Trustee_Name_Data_Formatted_Name` TEXT,
  `Trustee_Name_Data_Reporting_Name` TEXT,
  `Trustee_Country_Reference_ID` TEXT,
  `Trustee_Country_Reference_ID_Type` TEXT,
  `Trustee_Title_Reference_ID` TEXT,
  `Trustee_Title_Reference_ID_Type` TEXT,
  `Trustee_Title_Descriptor` TEXT,
  `Trustee_Salutation_Reference_ID` TEXT,
  `Trustee_Salutation_Reference_ID_Type` TEXT,
  `Trustee_First_Name` TEXT,
  `Trustee_Middle_Name` TEXT,
  `Trustee_Last_Name` TEXT,
  `Trustee_Secondary_Last_Name` TEXT,
  `Trustee_Tertiary_Last_Name` TEXT,
  `Trustee_Local_Name_Detail_Data_Local_Name` TEXT,
  `Trustee_Local_Name_Detail_Data_Local_Script` TEXT,
  `Trustee_Local_Name_First_Name` TEXT,
  `Trustee_Local_Name_Middle_Name` TEXT,
  `Trustee_Local_Name_Last_Name` TEXT,
  `Trustee_Local_Name_Secondary_Last_Name` TEXT,
  `Trustee_First_Name_2` TEXT,
  `Trustee_Middle_Name_2` TEXT,
  `Trustee_Last_Name_2` TEXT,
  `Trustee_Secondary_Last_Name_2` TEXT,
  `Trustee_Social_Suffix_Reference_ID` TEXT,
  `Trustee_Social_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Social_Suffix_Descriptor` TEXT,
  `Trustee_Academic_Suffix_Reference_ID` TEXT,
  `Trustee_Academic_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Hereditary_Suffix_Reference_ID` TEXT,
  `Trustee_Hereditary_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Honorary_Suffix_Reference_ID` TEXT,
  `Trustee_Honorary_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Professional_Suffix_Reference_ID` TEXT,
  `Trustee_Professional_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Religious_Suffix_Reference_ID` TEXT,
  `Trustee_Religious_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Royal_Suffix_Reference_ID` TEXT,
  `Trustee_Royal_Suffix_Reference_ID_Type` TEXT,
  `Trustee_Full_Name_for_Singapore_and_Malaysia` TEXT,
  `Trustee_Address_Data_Formatted_Address` TEXT,
  `Trustee_Address_Data_Address_Format_Type` TEXT,
  `Trustee_Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Trustee_Address_Data_Do_Not_Replace_All` TEXT,
  `Trustee_Address_Data_Delete` TEXT,
  `Trustee_Address_Data_Effective_Date` TEXT,
  `Trustee_Address_Country_Reference_ID` TEXT,
  `Trustee_Address_Country_Reference_ID_Type` TEXT,
  `Trustee_Address_Last_Modified` TEXT,
  `Trustee_Address_Line_1` TEXT,
  `Trustee_Address_Line_2` TEXT,
  `Trustee_Address_Line_3` TEXT,
  `Trustee_Address_Line_4` TEXT,
  `Trustee_Address_Line_5` TEXT,
  `Trustee_Address_Line_Descriptor` TEXT,
  `Trustee_Address_Line_Data_Type` TEXT,
  `Trustee_Municipality` TEXT,
  `Trustee_Country_City_Reference_ID` TEXT,
  `Trustee_Country_City_Reference_ID_Type` TEXT,
  `Trustee_Country_City_Reference_ID_parent_id` TEXT,
  `Trustee_Country_City_Reference_ID_parent_type` TEXT,
  `Trustee_Submunicipality_Data` TEXT,
  `Trustee_Submunicipality_Data_Address_Component_Name` TEXT,
  `Trustee_Submunicipality_Data_Type` TEXT,
  `Trustee_Country_Region_Reference_ID` TEXT,
  `Trustee_Country_Region_Reference_ID_Type` TEXT,
  `Trustee_Country_Region_Descriptor` TEXT,
  `Trustee_Subregion_Data` TEXT,
  `Trustee_Subregion_Descriptor` TEXT,
  `Trustee_Subregion_Data_Type` TEXT,
  `Trustee_Postal_Code` TEXT,
  `Trustee_Address_Usage_Data_Public` TEXT,
  `Trustee_Address_Type_Data_Primary` TEXT,
  `Trustee_Address_Type_Reference_ID` TEXT,
  `Trustee_Address_Type_Reference_ID_Type` TEXT,
  `Trustee_Address_Use_For_Ref_ID` TEXT,
  `Trustee_Address_Use_For_Ref_ID_Type` TEXT,
  `Trustee_Address_Use_For_Tenanted_Ref_ID` TEXT,
  `Trustee_Address_Use_For_Tenanted_Ref_ID_Type` TEXT,
  `Trustee_Address_Comments` TEXT,
  `Trustee_Address_Number_of_Days` TEXT,
  `Trustee_Municipality_Local` TEXT,
  `Trustee_Address_Reference_ID` TEXT,
  `Trustee_Address_Reference_ID_Type` TEXT,
  `Trustee_Address_ID` TEXT,
  `Trustee_Phone_Data_Area_Code` TEXT,
  `Trustee_Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Trustee_Phone_Data_International_Formatted_Phone` TEXT,
  `Trustee_Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Trustee_Phone_Data_National_Formatted_Phone` TEXT,
  `Trustee_Phone_Data_E164_Formatted_Phone` TEXT,
  `Trustee_Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Trustee_Phone_Data_Delete` TEXT,
  `Trustee_Phone_Data_Do_Not_Replace_All` TEXT,
  `Trustee_Phone_Country_ISO_Code` TEXT,
  `Trustee_International_Phone_Code` TEXT,
  `Trustee_Phone_Number` TEXT,
  `Trustee_Phone_Extension` TEXT,
  `Trustee_Phone_Device_Type_Reference_ID` TEXT,
  `Trustee_Phone_Device_Type_Reference_ID_Type` TEXT,
  `Trustee_Phone_Usage_Data_Public` TEXT,
  `Trustee_Phone_Type_Data_Primary` TEXT,
  `Trustee_Phone_Type_Reference_ID` TEXT,
  `Trustee_Phone_Type_Reference_ID_Type` TEXT,
  `Trustee_Phone_Use_For_Ref_ID` TEXT,
  `Trustee_Phone_Use_For_Ref_ID_Type` TEXT,
  `Trustee_Phone_Use_For_Tenanted_Ref_ID` TEXT,
  `Trustee_Phone_Use_For_Tenanted_Ref_ID_Type` TEXT,
  `Trustee_Phone_Comments` TEXT,
  `Trustee_Phone_Reference_ID` TEXT,
  `Trustee_Phone_Reference_ID_Type` TEXT,
  `Trustee_Phone_Data_ID` TEXT,
  `Trustee_Email_Address_Data_Delete` TEXT,
  `Trustee_Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Trustee_Email_Address` TEXT,
  `Trustee_Email_Comment` TEXT,
  `Trustee_Email_Usage_Data_Public` TEXT,
  `Trustee_Email_Type_Data_Primary` TEXT,
  `Trustee_Email_Type_Reference_ID` TEXT,
  `Trustee_Email_Type_Reference_ID_Type` TEXT,
  `Trustee_Email_Use_For_Ref_ID` TEXT,
  `Trustee_Email_Use_For_Ref_ID_Type` TEXT,
  `Trustee_Email_Use_For_Tenanted_Ref_ID` TEXT,
  `Trustee_Email_Use_For_Tenanted_Ref_ID_Type` TEXT,
  `Trustee_Email_Comments` TEXT,
  `Trustee_Email_Reference_ID` TEXT,
  `Trustee_Email_Reference_ID_Type` TEXT,
  `Trustee_Email_Address_Data_ID` TEXT,
  `Trustee_Instant_Messenger_Data_Delete` TEXT,
  `Trustee_Instant_Messenger_Data_Do_Not_Replace_All` TEXT,
  `Trustee_Instant_Messenger_Address` TEXT,
  `Trustee_Instant_Messenger_Type_Reference_ID` TEXT,
  `Trustee_Instant_Messenger_Type_Reference_ID_Type` TEXT,
  `Trustee_Instant_Messenger_Comment` TEXT,
  `Trustee_Instant_Messenger_Usage_Data_Public` TEXT,
  `Trustee_Instant_Messenger_Type_Data_Primary` TEXT,
  `Trustee_Instant_Messenger_Type_Usage_Ref_ID` TEXT,
  `Trustee_Instant_Messenger_Type_Usage_Ref_ID_Type` TEXT,
  `Trustee_Instant_Messenger_Use_For_Ref_ID` TEXT,
  `Trustee_Instant_Messenger_Use_For_Ref_ID_Type` TEXT,
  `Trustee_Instant_Messenger_Use_For_Tenanted_Ref_ID` TEXT,
  `Trustee_Instant_Messenger_Use_For_Tenanted_Ref_ID_Type` TEXT,
  `Trustee_Instant_Messenger_Comments` TEXT,
  `Trustee_Instant_Messenger_Reference_ID` TEXT,
  `Trustee_Instant_Messenger_Reference_ID_Type` TEXT,
  `Trustee_Instant_Messenger_Data_ID` TEXT,
  `Trustee_Web_Address_Data_Delete` TEXT,
  `Trustee_Web_Address_Data_Do_Not_Replace_All` TEXT,
  `Trustee_Web_Address` TEXT,
  `Trustee_Web_Address_Comment` TEXT,
  `Trustee_Web_Address_Usage_Data_Public` TEXT,
  `Trustee_Web_Address_Type_Data_Primary` TEXT,
  `Trustee_Web_Address_Type_Ref_ID` TEXT,
  `Trustee_Web_Address_Type_Ref_ID_Type` TEXT,
  `Trustee_Web_Address_Use_For_Ref_ID` TEXT,
  `Trustee_Web_Address_Use_For_Ref_ID_Type` TEXT,
  `Trustee_Web_Address_Use_For_Tenanted_Ref_ID` TEXT,
  `Trustee_Web_Address_Use_For_Tenanted_Ref_ID_Type` TEXT,
  `Trustee_Web_Address_Comments` TEXT,
  `Trustee_Web_Address_Reference_ID` TEXT,
  `Trustee_Web_Address_Reference_ID_Type` TEXT,
  `Trustee_Web_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Beneficiary_DCDD Section ***/


/*** Start of Change_Benefit_Jobs_DCDD Section created from https://app.smartsheet.com/sheets/FrHx4vqMVh9j2M4Wjw5FFV42xrcrg7jg78PcFjC1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefit_jobs`;
CREATE TABLE `src_change_benefit_jobs`(
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Benefit_Jobs_Data_Effective_Date` TEXT,
  `Use_Primary_Job` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefit_Jobs_DCDD Section ***/


/*** Start of Change_Benefits_Additional_DCDD Section created from https://app.smartsheet.com/sheets/WPfhcw2vx9V98hrw7WrgF52c34JJVPCRfJJ5p871?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_additional`;
CREATE TABLE `src_change_benefits_additional`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Additional_Benefits_Plan_Reference_ID` TEXT,
  `Additional_Benefits_Plan_Reference_ID_Type` TEXT,
  `Additional_Benefits_Coverage_Target_Reference_ID` TEXT,
  `Additional_Benefits_Coverage_Target_Reference_ID_Type` TEXT,
  `Additional_Benefits_Benefit_Individual_Rate_ID` TEXT,
  `Additional_Benefits_Employee_Cost_PreTax` TEXT,
  `Additional_Benefits_Employee_Cost_PostTax` TEXT,
  `Additional_Benefits_Employer_Cost_NonTaxable` TEXT,
  `Additional_Benefits_Employer_Cost_Taxable` TEXT,
  `Additional_Benefits_Percentage_Contribution_Value` TEXT,
  `Additional_Benefits_Flat_Contribution_Amount` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Additional_DCDD Section ***/


/*** Start of Change_Benefits_DCDD_Request Section created from https://app.smartsheet.com/sheets/QhGCXm94q6M3HRWRqQFxg8vcrmmWQgmWxP67G9W1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_request`;
CREATE TABLE `src_change_benefits_request`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Employee_Uses_Tobacco` TEXT,
  `Employee_Question_Response_Reference_ID` TEXT,
  `Employee_Question_Response_Reference_ID_Type` TEXT,
  `Spouse_Uses_Tobacco` TEXT,
  `Spouse_Question_Response_Reference_ID` TEXT,
  `Spouse_Question_Response_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_additional`;
CREATE TABLE `src_change_benefits_request_additional`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Additional_Benefits_Plan_ID` TEXT,
  `Additional_Benefits_Plan_ID_Type` TEXT,
  `Additional_Benefits_Coverage_Target_Reference_ID` TEXT,
  `Additional_Benefits_Coverage_Target_Reference_ID_Type` TEXT,
  `Additional_Benefits_Benefit_Individual_Rate_ID` TEXT,
  `Additional_Benefits_Employee_Cost_PreTax` TEXT,
  `Additional_Benefits_Employee_Cost_PostTax` TEXT,
  `Additional_Benefits_Employer_Cost_NonTaxable` TEXT,
  `Additional_Benefits_Employer_Cost_Taxable` TEXT,
  `Additional_Benefits_Percentage_Contribution_Value` TEXT,
  `Additional_Benefits_Flat_Contribution_Amount` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_health_savings`;
CREATE TABLE `src_change_benefits_request_health_savings`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Health_Savings_Account_Plan_ID` TEXT,
  `Health_Savings_Account_Plan_ID_Type` TEXT,
  `Health_Savings_Account_YTD_Contribution_Amount` TEXT,
  `Health_Savings_Account_Annual_Contribution` TEXT,
  `Health_Savings_Account_Employee_Cost` TEXT,
  `Health_Savings_Account_Beneficiary_Reference_ID` TEXT,
  `Health_Savings_Account_Beneficiary_Reference_ID_Type` TEXT,
  `Health_Savings_Account_Primary_Percentage` TEXT,
  `Health_Savings_Account_Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_healthcare`;
CREATE TABLE `src_change_benefits_request_healthcare`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Health_Care_Coverage_Plan_ID` TEXT,
  `Health_Care_Coverage_Plan_ID_Type` TEXT,
  `Health_Care_Coverage_Target_ID` TEXT,
  `Health_Care_Coverage_Target_ID_Type` TEXT,
  `Health_Care_Coverage_Provider_ID` TEXT,
  `Health_Care_Coverage_Dependent_Reference_ID` TEXT,
  `Health_Care_Coverage_Dependent_Reference_ID_Type` TEXT,
  `Health_Care_Coverage_Dependent_Provider_ID` TEXT,
  `Health_Care_Coverage_Dependent_Original_Coverage_Begin_Date` TEXT,
  `Health_Care_Coverage_Benefit_Individual_Rate_ID` TEXT,
  `Health_Care_Coverage_Employee_Cost_PreTax` TEXT,
  `Health_Care_Coverage_Employee_Cost_PostTax` TEXT,
  `Health_Care_Coverage_Employer_Cost_NonTaxable` TEXT,
  `Health_Care_Coverage_Employer_Cost_Taxable` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_insurance`;
CREATE TABLE `src_change_benefits_request_insurance`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Insurance_Plan_Reference_ID` TEXT,
  `Insurance_Plan_Reference_ID_Type` TEXT,
  `Insurance_Plan_Dependent_Reference_ID` TEXT,
  `Insurance_Plan_Dependent_Reference_ID_Type` TEXT,
  `Insurance_Plan_Coverage_Amount_Reference_ID` TEXT,
  `Insurance_Plan_Coverage_Amount_Reference_ID_Type` TEXT,
  `Insurance_Plan_Beneficiary_Reference_ID` TEXT,
  `Insurance_Plan_Beneficiary_Reference_ID_Type` TEXT,
  `Insurance_Plan_Beneficiary_Primary_Percentage` TEXT,
  `Insurance_Plan_Beneficiary_Contingent_Percentage` TEXT,
  `Insurance_Plan_Benefit_Individual_Rate_ID` TEXT,
  `Insurance_Plan_Employee_Cost_PreTax` TEXT,
  `Insurance_Plan_Employee_Cost_PostTax` TEXT,
  `Insurance_Plan_Employer_Cost_NonTaxable` TEXT,
  `Insurance_Plan_Employer_Cost_Taxable` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_other`;
CREATE TABLE `src_change_benefits_request_other`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_A` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_B` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_D` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_ID` TEXT,
  `Other_Health_Care_Insurance_Selected` TEXT,
  `Other_Health_Care_Insurance_For_Worker_TRICARE` TEXT,
  `Other_Health_Care_Insurance_For_Worker_FEHB` TEXT,
  `Other_Health_Care_Insurance_Type` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Other_Policy_Name` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Other_Policy_Number` TEXT,
  `Other_Health_Care_Insurance_For_Dependent_Ref_ID` TEXT,
  `Other_Health_Care_Insurance_For_Dependent_Ref_ID_Type` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_A` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_B` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_D` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_ID` TEXT,
  `Other_Health_Care_Insurance_Dependents_Selected` TEXT,
  `Other_Health_Care_Insurance_Dependent_TRICARE` TEXT,
  `Other_Health_Care_Insurance_Dependent_FEHB` TEXT,
  `Other_Health_Care_Insurance_Dependent_Type` TEXT,
  `Other_Health_Care_Insurance_Dependent_Other_Policy_Name` TEXT,
  `Other_Health_Care_Insurance_Dependent_Other_Policy_Number` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_retirement`;
CREATE TABLE `src_change_benefits_request_retirement`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Retirement_Savings_Plan_ID` TEXT,
  `Retirement_Savings_Plan_ID_Type` TEXT,
  `Retirement_Savings_Plan_Beneficiary_Reference_ID` TEXT,
  `Retirement_Savings_Plan_Beneficiary_Reference_ID_Type` TEXT,
  `Retirement_Savings_Plan_Beneficiary_Primary_Percentage` TEXT,
  `Retirement_Savings_Plan_Beneficiary_Contingent_Percentage` TEXT,
  `Retirement_Savings_Plan_Election_Percentage` TEXT,
  `Retirement_Savings_Plan_Election_Amount` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_retirement_savings_coverage`;
CREATE TABLE `src_change_benefits_request_retirement_savings_coverage`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Retirement_Savings_Coverage_Benefit_Coverage_Type_ID` TEXT,
  `Retirement_Savings_Coverage_Benefit_Coverage_Type_ID_Type` TEXT,
  `Retirement_Savings_Coverage_Do_not_autoenroll_unspecified_plans` TEXT,
  `Retirement_Savings_Coverage_Coverage_Begin_Date` TEXT,
  `Retirement_Savings_Coverage_Original_Coverage_Begin_Date` TEXT,
  `Retirement_Savings_Coverage_Deduction_Begin_Date` TEXT,
  `Retirement_Savings_Coverage_Original_Deduction_Begin_Date` TEXT,
  `Retirement_Savings_Plan_Reference_ID` TEXT,
  `Retirement_Savings_Plan_Reference_ID_Type` TEXT,
  `Retirement_Savings_Coverage_Employee_Contribution_Percent` TEXT,
  `Retirement_Savings_Coverage_Employer_Contribution_Percent` TEXT,
  `Retirement_Savings_Coverage_Beneficiary_Reference_ID` TEXT,
  `Retirement_Savings_Coverage_Beneficiary_Reference_ID_Type` TEXT,
  `Retirement_Savings_Coverage_Beneficiary_Primary_Percentage` TEXT,
  `Retirement_Savings_Coverage_Beneficiary_Contingent_Percentage` TEXT,
  `Retirement_Savings_Coverage_Employee_Contribution_Percentage` TEXT,
  `Retirement_Savings_Coverage_Employee_Contribution_Amount` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_request_spending`;
CREATE TABLE `src_change_benefits_request_spending`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Spending_Account_Plan_ID` TEXT,
  `Spending_Account_Plan_ID_Type` TEXT,
  `Spending_Account_YTD_Contribution_Amount` TEXT,
  `Spending_Account_Annual_Contribution` TEXT,
  `Spending_Account_Employee_Cost` TEXT,
  `Spending_Account_Beneficiary_Reference_ID` TEXT,
  `Spending_Account_Beneficiary_Reference_ID_Type` TEXT,
  `Spending_Account_Beneficiary_Primary_Percentage` TEXT,
  `Spending_Account_Beneficiary_Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_DCDD_Request Section ***/


/*** Start of Change_Benefits_Health_Savings_DCDD Section created from https://app.smartsheet.com/sheets/xqhV4cXWFxcWPM39wX38F4phXQhr4PhwJJW7wwx1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_health_savings`;
CREATE TABLE `src_change_benefits_health_savings`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency_Reference_ID` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Health_Savings_Account_Plan` TEXT,
  `Health_Savings_Account_Plan_Reference_ID_Type` TEXT,
  `YTD_Contribution_Amount` TEXT,
  `Annual_Contribution` TEXT,
  `Employee_Cost` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_health_savings_details`;
CREATE TABLE `src_change_benefits_health_savings_details`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Health_Savings_Account_Plan` TEXT,
  `Health_Savings_Account_Beneficiary_Reference_ID` TEXT,
  `Health_Savings_Account_Beneficiary_Reference_ID_Type` TEXT,
  `Health_Savings_Account_Primary_Percentage` TEXT,
  `Health_Savings_Account_Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Health_Savings_DCDD Section ***/


/*** Start of Change_Benefits_Healthcare_DCDD Section created from https://app.smartsheet.com/sheets/R4q2FmRCQJQ9rHm8r52g6M6p2fh8X25C54RC79h1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_healthcare`;
CREATE TABLE `src_change_benefits_healthcare`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID_Type` TEXT,
  `Health_Care_Coverage_Target_Reference_ID` TEXT,
  `Health_Care_Coverage_Target_Reference_ID_Type` TEXT,
  `Provider_ID` TEXT,
  `Benefit_Individual_Rate_ID` TEXT,
  `Employee_Cost_PreTax` TEXT,
  `Employee_Cost_PostTax` TEXT,
  `Employer_Cost_NonTaxable` TEXT,
  `Employer_Cost_Taxable` TEXT,
  `Employee_Uses_Tobacco` TEXT,
  `Employee_Question_Response_Reference_ID` TEXT,
  `Employee_Question_Response_Reference_ID_Type` TEXT,
  `Spouse_Uses_Tobacco` TEXT,
  `Spouse_Question_Response_Reference_ID` TEXT,
  `Spouse_Question_Response_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_healthcare_details`;
CREATE TABLE `src_change_benefits_healthcare_details`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Dependent_Provider_ID` TEXT,
  `Dependent_Original_Coverage_Begin_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_healthcare_other`;
CREATE TABLE `src_change_benefits_healthcare_other`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_A` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_B` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_Part_D` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Medicare_ID` TEXT,
  `Other_Health_Care_Insurance_Selected` TEXT,
  `Other_Health_Care_Insurance_For_Worker_TRICARE` TEXT,
  `Other_Health_Care_Insurance_For_Worker_FEHB` TEXT,
  `Other_Health_Care_Insurance_Type` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Other_Policy_Name` TEXT,
  `Other_Health_Care_Insurance_For_Worker_Other_Policy_Number` TEXT,
  `Other_Health_Care_Insurance_For_Dependent_Ref_ID` TEXT,
  `Other_Health_Care_Insurance_For_Dependent_Ref_ID_Type` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_A` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_B` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_Part_D` TEXT,
  `Other_Health_Care_Insurance_Dependent_Medicare_ID` TEXT,
  `Other_Health_Care_Insurance_Dependents_Selected` TEXT,
  `Other_Health_Care_Insurance_Dependent_TRICARE` TEXT,
  `Other_Health_Care_Insurance_Dependent_FEHB` TEXT,
  `Other_Health_Care_Insurance_Dependent_Type` TEXT,
  `Other_Health_Care_Insurance_Dependent_Other_Policy_Name` TEXT,
  `Other_Health_Care_Insurance_Dependent_Other_Policy_Number` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Healthcare_DCDD Section ***/


/*** Start of Change_Benefits_Insurance_DCDD Section created from https://app.smartsheet.com/sheets/gJ4WqcV7r4Ww2JwWqPJFXxhXmVXVgPQH97gh4c91?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_insurance`;
CREATE TABLE `src_change_benefits_insurance`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency_Reference_ID` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Insurance_Coverage_Plan_Reference_ID` TEXT,
  `Insurance_Coverage_Plan_Reference_ID_Type` TEXT,
  `Coverage_Amount_Reference_ID` TEXT,
  `Coverage_Amount_Reference_ID_Type` TEXT,
  `Benefit_Individual_Rate_ID` TEXT,
  `Employee_Cost_PreTax` TEXT,
  `Employee_Cost_PostTax` TEXT,
  `Employer_Cost_NonTaxable` TEXT,
  `Employer_Cost_Taxable` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_insurance_benalloc`;
CREATE TABLE `src_change_benefits_insurance_benalloc`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Insurance_Coverage_Plan_Reference_ID` TEXT,
  `Beneficiary_Reference_ID` TEXT,
  `Beneficiary_Reference_ID_Type` TEXT,
  `Primary_Percentage` TEXT,
  `Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_insurance_dependents`;
CREATE TABLE `src_change_benefits_insurance_dependents`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Insurance_Coverage_Plan_Reference_ID` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Insurance_DCDD Section ***/


/*** Start of Change_Benefits_Medical_History_DCDD Section created from https://app.smartsheet.com/sheets/2vFXcjmcHFvqjX4M8MpRCVx58mpJMWMJMx99WJx1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_medical_history`;
CREATE TABLE `src_change_benefits_medical_history`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency_Reference_ID` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID_Type` TEXT,
  `Health_Care_Coverage_Target_Reference_ID` TEXT,
  `Health_Care_Coverage_Target_Reference_ID_Type` TEXT,
  `Provider_ID` TEXT,
  `Benefit_Individual_Rate_ID` TEXT,
  `Employee_Cost_PreTax` TEXT,
  `Employee_Cost_PostTax` TEXT,
  `Employer_Cost_NonTaxable` TEXT,
  `Employer_Cost_Taxable` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_medical_history_details`;
CREATE TABLE `src_change_benefits_medical_history_details`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Health_Care_Coverage_Plan_Reference_ID` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Dependent_Provider_ID` TEXT,
  `Dependent_Original_Coverage_Begin_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Medical_History_DCDD Section ***/


/*** Start of Change_Benefits_Retirement_DCDD Section created from https://app.smartsheet.com/sheets/4hpwcX6Xrhx4X972hXVCrFJ6gfJC2jQRP64vXpP1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_retirement`;
CREATE TABLE `src_change_benefits_retirement`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency_Reference_ID` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Retirement_Savings_Plan_Reference_ID` TEXT,
  `Retirement_Savings_Plan_Reference_ID_Type` TEXT,
  `Election_Percentage` TEXT,
  `Election_Amount` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_retirement_details`;
CREATE TABLE `src_change_benefits_retirement_details`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Retirement_Savings_Plan_Reference_ID` TEXT,
  `Beneficiary_Reference_ID` TEXT,
  `Beneficiary_Reference_ID_Type` TEXT,
  `Primary_Percentage` TEXT,
  `Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Retirement_DCDD Section ***/


/*** Start of Change_Benefits_Spending_DCDD Section created from https://app.smartsheet.com/sheets/QpQC4FfGGcFqc7GqQ9gQXqHGvJ78rG8jGGCq3vV1?view=grid ***/

DROP TABLE IF EXISTS `src_change_benefits_spending`;
CREATE TABLE `src_change_benefits_spending`(
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Benefit_Event_Type_Reference_ID_Type` TEXT,
  `Event_Date` TEXT,
  `Benefit_Deduction_Periods_Remaining` TEXT,
  `Remaining_Period_Frequency` TEXT,
  `Remaining_Period_Frequency_Reference_ID_Type` TEXT,
  `Excess_Credits_to_HSA` TEXT,
  `Has_Existing_Medical_Coverage` TEXT,
  `Enrollment_Signature_Date` TEXT,
  `Signing_Worker_Reference_ID` TEXT,
  `Signing_Worker_Reference_ID_Type` TEXT,
  `Original_Signature_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Original_Coverage_Begin_Date` TEXT,
  `Overridden_Coverage_Begin_Date` TEXT,
  `Deduction_Begin_Date` TEXT,
  `Original_Deduction_Begin_Date` TEXT,
  `Spending_Account_Plan` TEXT,
  `Spending_Account_Plan_Reference_ID_Type` TEXT,
  `YTD_Contribution_Amount` TEXT,
  `Annual_Contribution` TEXT,
  `Employee_Cost` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_change_benefits_spending_details`;
CREATE TABLE `src_change_benefits_spending_details`(
  `Employee_ID` TEXT,
  `Benefit_Event_Type_Reference_ID` TEXT,
  `Event_Date` TEXT,
  `Coverage_Begin_Date` TEXT,
  `Spending_Account_Plan` TEXT,
  `Beneficiary_Reference_ID` TEXT,
  `Beneficiary_Reference_ID_Type` TEXT,
  `Primary_Percentage` TEXT,
  `Contingent_Percentage` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Change_Benefits_Spending_DCDD Section ***/


/*** Start of Edit_Dependent_DCDD Section created from https://app.smartsheet.com/sheets/QR3xGggHPMQ6Rx7Cm3Fv4FPGQFHJ6JQqFFwVgHh1?view=grid ***/

DROP TABLE IF EXISTS `src_edit_dependent`;
CREATE TABLE `src_edit_dependent`(
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Dependent_ID` TEXT,
  `Effective_Date` TEXT,
  `Reason_Reference_ID` TEXT,
  `Reason_Reference_ID_Type` TEXT,
  `Related_Person_Relationship_Reference_ID` TEXT,
  `Related_Person_Relationship_Reference_ID_Type` TEXT,
  `Use_Employee_Address` TEXT,
  `Use_Employee_Phone` TEXT,
  `Name_Detail_Data_Formatted_Name` TEXT,
  `Name_Detail_Data_Reporting_Name` TEXT,
  `Name_Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Title_Reference_ID` TEXT,
  `Title_Reference_ID_Type` TEXT,
  `Title_Descriptor` TEXT,
  `Salutation_Reference_ID` TEXT,
  `Salutation_Reference_ID_Type` TEXT,
  `First_Name` TEXT,
  `Middle_Name` TEXT,
  `Last_Name` TEXT,
  `Secondary_Last_Name` TEXT,
  `Tertiary_Last_Name` TEXT,
  `Local_Name_Detail_Data_Local_Name` TEXT,
  `Local_Name_Detail_Data_Local_Script` TEXT,
  `Local_First_Name` TEXT,
  `Local_Middle_Name` TEXT,
  `Local_Last_Name` TEXT,
  `Local_Secondary_Last_Name` TEXT,
  `First_Name_2` TEXT,
  `Middle_Name_2` TEXT,
  `Last_Name_2` TEXT,
  `Secondary_Last_Name_2` TEXT,
  `Social_Suffix_Reference_ID` TEXT,
  `Social_Suffix_Reference_ID_Type` TEXT,
  `Social_Suffix_Descriptor` TEXT,
  `Academic_Suffix_Reference_ID` TEXT,
  `Academic_Suffix_Reference_ID_Type` TEXT,
  `Hereditary_Suffix_Reference_ID` TEXT,
  `Hereditary_Suffix_Reference_ID_Type` TEXT,
  `Honorary_Suffix_Reference_ID` TEXT,
  `Honorary_Suffix_Reference_ID_Type` TEXT,
  `Professional_Suffix_Reference_ID` TEXT,
  `Professional_Suffix_Reference_ID_Type` TEXT,
  `Religious_Suffix_Reference_ID` TEXT,
  `Religious_Suffix_Reference_ID_Type` TEXT,
  `Royal_Suffix_Reference_ID` TEXT,
  `Royal_Suffix_Reference_ID_Type` TEXT,
  `Full_Name_for_Singapore_and_Malaysia` TEXT,
  `QDRO_Benefit_Coverage_Type_Ref_ID` TEXT,
  `QDRO_Benefit_Coverage_Type_Ref_ID_Type` TEXT,
  `QDRO_Start_Date` TEXT,
  `QDRO_End_Date` TEXT,
  `Could_Be_Covered_For_Health_Care_Coverage_Elsewhere` TEXT,
  `Could_Be_Covered_For_Health_Care_Coverage_Elsewhere_EffDate` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_edit_dependent_contact_details`;
CREATE TABLE `src_edit_dependent_contact_details`(
  `Dependent_ID` TEXT,
  `Address_Data_Formatted_Address` TEXT,
  `Address_Data_Address_Format_Type` TEXT,
  `Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Address_Data_Delete` TEXT,
  `Address_Data_Do_Not_Replace_All` TEXT,
  `Address_Data_Effective_Date` TEXT,
  `Address_Country_Reference_ID` TEXT,
  `Address_Country_Reference_ID_Type` TEXT,
  `Address_Last_Modified` TEXT,
  `ADDRESS_LINE_1` TEXT,
  `ADDRESS_LINE_2` TEXT,
  `ADDRESS_LINE_3` TEXT,
  `ADDRESS_LINE_4` TEXT,
  `ADDRESS_LINE_5` TEXT,
  `Address_Line_Data_Type` TEXT,
  `Address_Municipality` TEXT,
  `Address_Country_City_Reference_ID` TEXT,
  `Address_Country_City_Reference_ID_Type` TEXT,
  `Address_Country_City_Reference_ID_parent_id` TEXT,
  `Address_Country_City_Reference_ID_parent_type` TEXT,
  `Address_Submunicipality_Data` TEXT,
  `Address_Submunicipality_Data_Address_Component_Name` TEXT,
  `Address_Submunicipality_Data_Type` TEXT,
  `Address_Country_Region_Reference_ID` TEXT,
  `Address_Country_Region_Reference_ID_Type` TEXT,
  `Address_Country_Region_Descriptor` TEXT,
  `Address_Subregion_Data` TEXT,
  `Subregion_Data_Descriptor` TEXT,
  `Address_Subregion_Data_Type` TEXT,
  `Address_Postal_Code` TEXT,
  `Address_Usage_Type_Public` TEXT,
  `Address_Usage_Type_Primary` TEXT,
  `Address_Usage_Type_Reference_ID` TEXT,
  `Address_Usage_Type_Reference_ID_Type` TEXT,
  `Address_Use_For_Reference_ID` TEXT,
  `Address_Use_For_Reference_ID_Type` TEXT,
  `Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Address_Comments` TEXT,
  `Address_Number_of_Days` TEXT,
  `Address_Municipality_Local` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT,
  `Address_ID` TEXT,
  `Phone_Data_Area_Code` TEXT,
  `Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Phone_Data_International_Formatted_Phone` TEXT,
  `Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Phone_Data_National_Formatted_Phone` TEXT,
  `Phone_Data_E164_Formatted_Phone` TEXT,
  `Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Phone_Data_Delete` TEXT,
  `Phone_Data_Do_Not_Replace_All` TEXT,
  `Phone_Country_ISO_Code` TEXT,
  `Phone_International_Phone_Code` TEXT,
  `Phone_Number` TEXT,
  `Phone_Extension` TEXT,
  `Phone_Device_Type_Reference_ID` TEXT,
  `Phone_Device_Type_Reference_ID_Type` TEXT,
  `Phone_Usage_Type_Public` TEXT,
  `Phone_Usage_Type_Primary` TEXT,
  `Phone_Usage_Type_Reference_ID` TEXT,
  `Phone_Usage_Type_Reference_ID_Type` TEXT,
  `Phone_Use_For_Reference_ID` TEXT,
  `Phone_Use_For_Reference_ID_Type` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Phone_Comments` TEXT,
  `Phone_Reference_ID` TEXT,
  `Phone_Reference_ID_Type` TEXT,
  `Phone_Data_ID` TEXT,
  `Email_Address_Data_Delete` TEXT,
  `Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Email_Address` TEXT,
  `Email_Comment` TEXT,
  `Email_Usage_Type_Public` TEXT,
  `Email_Usage_Type_Primary` TEXT,
  `Email_Usage_Type_Reference_ID` TEXT,
  `Email_Usage_Type_Reference_ID_Type` TEXT,
  `Email_Use_For_Reference_ID` TEXT,
  `Email_Address_Use_For_Reference_ID_Type` TEXT,
  `Email_Use_For_Tenanted_Reference_ID` TEXT,
  `Email_Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Email_Comments` TEXT,
  `Email_Reference_ID` TEXT,
  `Email_Reference_ID_Type` TEXT,
  `Email_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_edit_dependent_details`;
CREATE TABLE `src_edit_dependent_details`(
  `Dependent_ID` TEXT,
  `Date_of_Birth` TEXT,
  `Date_of_Death` TEXT,
  `Gender_Reference_ID` TEXT,
  `Gender_Reference_ID_Type` TEXT,
  `Uses_Tobacco` TEXT,
  `Full_Time_Student` TEXT,
  `Student_Status_Start_Date` TEXT,
  `Student_Status_End_Date` TEXT,
  `Disabled` TEXT,
  `Replace_All` TEXT,
  `Disability_Status_Reference_ID` TEXT,
  `Disability_Status_Reference_ID_Type` TEXT,
  `Delete` TEXT,
  `Disability_Reference_ID` TEXT,
  `Disability_Reference_ID_Type` TEXT,
  `Disability_Status_Date` TEXT,
  `Date_Known` TEXT,
  `Disability_End_Date` TEXT,
  `Disability_Grade_Reference_ID` TEXT,
  `Disability_Grade_Reference_ID_Type` TEXT,
  `Disability_Degree` TEXT,
  `Inactive_Date` TEXT,
  `Dependent_for_Payroll_Purposes` TEXT,
  `Citizenship_Status_Reference_ID` TEXT,
  `Citizenship_Status_Reference_ID_Type` TEXT,
  `Country_of_Nationality_Reference_ID` TEXT,
  `Country_of_Nationality_Reference_ID_Type` TEXT,
  `Country_of_Birth_Reference_ID` TEXT,
  `Country_of_Birth_Reference_ID_Type` TEXT,
  `Region_of_Birth_Reference_ID` TEXT,
  `Region_of_Birth_Reference_ID_Type` TEXT,
  `City_of_Birth` TEXT,
  `Live_With_Worker_Effective_Date` TEXT,
  `Lives_With_Worker` TEXT,
  `Health_Insurance_Effective_Date` TEXT,
  `Has_Health_Insurance` TEXT,
  `Allowed_for_Tax_Deduction_Effective_Date` TEXT,
  `Allowed_for_Tax_Deduction` TEXT,
  `Income_Effective_Date` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Annual_Income` TEXT,
  `Occupation_Effective_Date` TEXT,
  `Occupation` TEXT,
  `Dependent_Verification_Status_Reference_ID` TEXT,
  `Dependent_Verification_Status_Reference_ID_Type` TEXT,
  `Dependent_Verification_Comment` TEXT,
  `Dependent_Verification_Verification_Date` TEXT,
  `Dependent_Verification_Expiration_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_edit_dependent_id_details`;
CREATE TABLE `src_edit_dependent_id_details`(
  `Dependent_ID` TEXT,
  `National_ID_Delete` TEXT,
  `National_ID_Reference_ID` TEXT,
  `National_ID_Reference_ID_Type` TEXT,
  `National_ID_Data_ID` TEXT,
  `National_ID_Type_Reference_ID` TEXT,
  `National_ID_Type_Reference_ID_Type` TEXT,
  `National_ID_Country_Reference_ID` TEXT,
  `National_ID_Country_Reference_ID_Type` TEXT,
  `National_ID_Issued_Date` TEXT,
  `National_ID_Expiration_Date` TEXT,
  `National_ID_Verification_Date` TEXT,
  `National_ID_Series` TEXT,
  `National_ID_Issuing_Agency` TEXT,
  `National_ID_Verified_By_Reference_ID` TEXT,
  `National_ID_Verified_By_Reference_ID_Type` TEXT,
  `National_ID_Shared_Reference_ID` TEXT,
  `National_ID_Shared_Reference_ID_Type` TEXT,
  `Government_ID_Delete` TEXT,
  `Government_ID_Reference_ID` TEXT,
  `Government_ID_Reference_ID_Type` TEXT,
  `Government_ID_Data_ID` TEXT,
  `Government_ID_Type_Reference_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID_Type` TEXT,
  `Government_ID_Country_Reference_ID` TEXT,
  `Government_ID_Country_Reference_ID_Type` TEXT,
  `Government_ID_Issued_Date` TEXT,
  `Government_ID_Expiration_Date` TEXT,
  `Government_ID_Verification_Date` TEXT,
  `Government_ID_Verified_by_Reference_ID` TEXT,
  `Government_ID_Verified_by_Reference_ID_Type` TEXT,
  `Government_ID_Shared_Reference_ID` TEXT,
  `Government_ID_Shared_Reference_ID_Type` TEXT,
  `Visa_ID_Delete` TEXT,
  `Visa_ID_Reference_ID` TEXT,
  `Visa_ID_Reference_ID_Type` TEXT,
  `Visa_ID_Data_ID` TEXT,
  `Visa_ID_Type_Reference_ID` TEXT,
  `Visa_ID_ID_Type_Reference_ID_Type` TEXT,
  `Visa_ID_Country_Reference_ID` TEXT,
  `Visa_ID_Country_Reference_ID_Type` TEXT,
  `Visa_ID_Issued_Date` TEXT,
  `Visa_ID_Expiration_Date` TEXT,
  `Visa_ID_Verification_Date` TEXT,
  `Visa_ID_Verified_By_Reference_ID` TEXT,
  `Visa_ID_Verified_By_Reference_ID_Type` TEXT,
  `Visa_ID_Shared_Reference_ID` TEXT,
  `Visa_ID_Shared_Reference_ID_Type` TEXT,
  `Passport_ID_Delete` TEXT,
  `Passport_ID_Reference_ID` TEXT,
  `Passport_ID_Reference_ID_Type` TEXT,
  `Passport_ID_Data_ID` TEXT,
  `Passport_ID_Type_Reference_ID` TEXT,
  `Passport_ID_ID_Type_Reference_ID_Type` TEXT,
  `Passport_ID_Country_Reference_ID` TEXT,
  `Passport_ID_Country_Reference_ID_Type` TEXT,
  `Passport_ID_Issued_Date` TEXT,
  `Passport_ID_Expiration_Date` TEXT,
  `Passport_ID_Verification_Date` TEXT,
  `Passport_ID_Verified_By_Reference_ID` TEXT,
  `Passport_ID_Verified_By_Reference_ID_Type` TEXT,
  `Passport_ID_Shared_Reference_ID` TEXT,
  `Passport_ID_Shared_Reference_ID_Type` TEXT,
  `License_ID_Delete` TEXT,
  `License_ID_Reference_ID` TEXT,
  `License_ID_Reference_ID_Type` TEXT,
  `License_ID_Data_ID` TEXT,
  `License_ID_Type_Reference_ID` TEXT,
  `License_ID_ID_Type_Reference_ID_Type` TEXT,
  `License_ID_Country_Reference_ID` TEXT,
  `License_ID_Country_Reference_ID_Type` TEXT,
  `License_ID_Country_Region_Reference_ID` TEXT,
  `License_ID_Country_Region_Reference_ID_Type` TEXT,
  `License_Country_Region_Descriptor` TEXT,
  `License_ID_Authority_Reference_ID` TEXT,
  `License_ID_Authority_Reference_ID_Type` TEXT,
  `License_ID_Class` TEXT,
  `License_ID_Issued_Date` TEXT,
  `License_ID_Expiration_Date` TEXT,
  `License_ID_Verification_Date` TEXT,
  `License_ID_Verified_By_Reference_ID` TEXT,
  `License_ID_Verified_By_Reference_ID_Type` TEXT,
  `License_ID_Shared_Reference_ID` TEXT,
  `License_ID_Shared_Reference_ID_Type` TEXT,
  `Custom_ID_Delete` TEXT,
  `Custom_ID_Reference_ID` TEXT,
  `Custom_ID_Reference_ID_Type` TEXT,
  `Custom_ID_Data_ID` TEXT,
  `Custom_ID_Type_Reference_ID` TEXT,
  `Custom_ID_ID_Type_Reference_ID_Type` TEXT,
  `Custom_ID_Issued_Date` TEXT,
  `Custom_ID_Expiration_Date` TEXT,
  `Custom_ID_Organization_ID` TEXT,
  `Custom_ID_Organization_ID_Type` TEXT,
  `Custom_ID_Description` TEXT,
  `Custom_ID_Shared_Reference_ID` TEXT,
  `Custom_ID_Shared_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Edit_Dependent_DCDD Section ***/


/*** Start of Put_Affordable_Care_Act_Worker_Hours_Wages_DCDD Section created from https://app.smartsheet.com/sheets/PGc339w3PmQwFxJP6HJWmH5Rh5GMCRXfRGVG4HC1?view=grid ***/

DROP TABLE IF EXISTS `src_put_affordable_care_act_worker_hours_wages`;
CREATE TABLE `src_put_affordable_care_act_worker_hours_wages`(
  `Delete_Flag` TEXT,
  `Worker_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Taxable_Wages_for_Period` TEXT,
  `Pay_End_Date` TEXT,
  `Paycheck_Date` TEXT,
  `Paycheck_Number` TEXT,
  `Paid_Hours_Worked` TEXT,
  `Paid_Hours_Not_Worked` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Affordable_Care_Act_Worker_Hours_Wages_DCDD Section ***/


/*** Start of Put_Beneficiary_DCDD Section created from https://app.smartsheet.com/sheets/522pmx6PmqMx5Q8crFmPCVHMhh4Ppv72CFg76hp1?view=grid ***/

DROP TABLE IF EXISTS `src_put_beneficiary`;
CREATE TABLE `src_put_beneficiary`(
  `Beneficiary_Reference_ID` TEXT,
  `Beneficiary_Reference_ID_Type` TEXT,
  `Beneficiary_ID` TEXT,
  `Employee_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Existing_Related_Person_Reference_ID` TEXT,
  `Existing_Related_Person_Reference_ID_Type` TEXT,
  `Related_Person_Relationship_Reference_ID` TEXT,
  `Related_Person_Relationship_Reference_ID_Type` TEXT,
  `Irrevocable` TEXT,
  `Use_Employee_Address` TEXT,
  `Use_Employee_Phone` TEXT,
  `Legal_Name_Name_Detail_Data_Formatted_Name` TEXT,
  `Legal_Name_Name_Detail_Data_Reporting_Name` TEXT,
  `Legal_Name_Name_Country_Reference_ID` TEXT,
  `Legal_Name_Country_Reference_ID_Type` TEXT,
  `Legal_Name_Title_Reference_ID` TEXT,
  `Legal_Name_Title_Reference_ID_Type` TEXT,
  `Legal_Name_Title_Descriptor` TEXT,
  `Legal_Name_Salutation_Reference_ID` TEXT,
  `Legal_Name_Salutation_Reference_ID_Type` TEXT,
  `Legal_Name_First_Name` TEXT,
  `Legal_Name_Middle_Name` TEXT,
  `Legal_Name_Last_Name` TEXT,
  `Legal_Name_Secondary_Last_Name` TEXT,
  `Legal_Name_Tertiary_Last_Name` TEXT,
  `Legal_Name_Local_Name_Detail_Data_Local_Name` TEXT,
  `Legal_Name_Local_Name_Detail_Data_Local_Script` TEXT,
  `Legal_Name_Usage_First_Name` TEXT,
  `Legal_Name_Usage_Middle_Name` TEXT,
  `Legal_Name_Usage_Last_Name` TEXT,
  `Legal_Name_Usage_Secondary_Last_Name` TEXT,
  `Legal_Name_First_Name_2` TEXT,
  `Legal_Name_Middle_Name_2` TEXT,
  `Legal_Name_Last_Name_2` TEXT,
  `Legal_Name_Secondary_Last_Name_2` TEXT,
  `Legal_Name_Social_Suffix_Reference_ID` TEXT,
  `Legal_Name_Social_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Social_Suffix_Descriptor` TEXT,
  `Legal_Name_Academic_Suffix_Reference_ID` TEXT,
  `Legal_Name_Academic_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Hereditary_Suffix_Reference_ID` TEXT,
  `Legal_Name_Hereditary_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Honorary_Suffix_Reference_ID` TEXT,
  `Legal_Name_Honorary_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Professional_Suffix_Reference_ID` TEXT,
  `Legal_Name_Professional_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Religious_Suffix_Reference_ID` TEXT,
  `Legal_Name_Religious_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Royal_Suffix_Reference_ID` TEXT,
  `Legal_Name_Royal_Suffix_Reference_ID_Type` TEXT,
  `Legal_Name_Full_Name_for_Singapore_and_Malaysia` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_beneficiary_contact_details`;
CREATE TABLE `src_put_beneficiary_contact_details`(
  `Beneficiary_ID` TEXT,
  `Employee_ID` TEXT,
  `Address_Data_Formatted_Address` TEXT,
  `Address_Data_Address_Format_Type` TEXT,
  `Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Address_Data_Delete` TEXT,
  `Address_Data_Do_Not_Replace_All` TEXT,
  `Address_Data_Effective_Date` TEXT,
  `Address_Country_Reference_ID` TEXT,
  `Address_Country_Reference_ID_Type` TEXT,
  `Address_Last_Modified` TEXT,
  `ADDRESS_LINE_1` TEXT,
  `ADDRESS_LINE_2` TEXT,
  `Address_Line_Data_Type` TEXT,
  `Address_Municipality` TEXT,
  `Address_Country_City_Reference_ID` TEXT,
  `Address_Country_City_Reference_ID_Type` TEXT,
  `Address_Country_City_Reference_ID_parent_id` TEXT,
  `Address_Country_City_Reference_ID_parent_type` TEXT,
  `Address_Submunicipality_Data` TEXT,
  `Address_Submunicipality_Data_Address_Component_Name` TEXT,
  `Address_Submunicipality_Data_Type` TEXT,
  `Address_Country_Region_Reference_ID` TEXT,
  `Address_Country_Region_Reference_ID_Type` TEXT,
  `Address_Country_Region_Descriptor` TEXT,
  `Address_Subregion_Data` TEXT,
  `Address_Subregion_Data_Type` TEXT,
  `Address_Postal_Code` TEXT,
  `Address_Usage_Data_Public` TEXT,
  `Address_Usage_Type_Primary` TEXT,
  `Address_Usage_Type_Reference_ID` TEXT,
  `Address_Usage_Type_Reference_ID_Type` TEXT,
  `Address_Use_For_Reference_ID_1` TEXT,
  `Address_Use_For_Reference_ID_Type_1` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_1` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_Type_1` TEXT,
  `Address_Comments` TEXT,
  `Address_Number_of_Days` TEXT,
  `Address_Municipality_Local` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT,
  `Address_ID` TEXT,
  `Phone_Data_Area_Code` TEXT,
  `Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Phone_Data_International_Formatted_Phone` TEXT,
  `Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Phone_Data_National_Formatted_Phone` TEXT,
  `Phone_Data_E164_Formatted_Phone` TEXT,
  `Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Phone_Data_Delete` TEXT,
  `Phone_Data_Do_Not_Replace_All` TEXT,
  `Phone_Country_ISO_Code` TEXT,
  `Phone_International_Phone_Code` TEXT,
  `Phone_Number` TEXT,
  `Phone_Extension` TEXT,
  `Phone_Device_Type_Reference_ID` TEXT,
  `Phone_Device_Type_Reference_ID_Type` TEXT,
  `Phone_Usage_Data_Public` TEXT,
  `Phone_Usage_Type_Primary` TEXT,
  `Phone_Usage_Type_Reference_ID` TEXT,
  `Phone_Usage_Type_Reference_ID_Type` TEXT,
  `Phone_Use_For_Reference_ID` TEXT,
  `Phone_Use_For_Reference_ID_Type` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID` TEXT,
  `Phone_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Phone_Comments` TEXT,
  `Phone_Reference_ID` TEXT,
  `Phone_Reference_ID_Type` TEXT,
  `Phone_Data_ID` TEXT,
  `Email_Address_Data_Delete` TEXT,
  `Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Email_Address` TEXT,
  `Email_Comment` TEXT,
  `Email_Usage_Data_Public` TEXT,
  `Email_Usage_Type_Primary` TEXT,
  `Email_Usage_Type_Reference_ID` TEXT,
  `Email_Usage_Type_Reference_ID_Type` TEXT,
  `Email_Use_For_Reference_ID` TEXT,
  `Email_Use_For_Reference_ID_Type` TEXT,
  `Email_Use_For_Tenanted_Reference_ID` TEXT,
  `Email_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Email_Comments` TEXT,
  `Email_Reference_ID` TEXT,
  `Email_Reference_ID_Type` TEXT,
  `Email_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_beneficiary_details`;
CREATE TABLE `src_put_beneficiary_details`(
  `Beneficiary_ID` TEXT,
  `Employee_ID` TEXT,
  `National_ID_Delete` TEXT,
  `National_ID_Reference_ID` TEXT,
  `National_ID_Reference_ID_Type` TEXT,
  `National_ID_Data_ID` TEXT,
  `National_ID_Type` TEXT,
  `National_ID_Type_Reference_Type` TEXT,
  `National_ID_Country_Reference_ID` TEXT,
  `National_ID_Country_Reference_ID_Type` TEXT,
  `National_ID_Issued_Date` TEXT,
  `National_ID_Expiration_Date` TEXT,
  `National_ID_Verification_Date` TEXT,
  `National_ID_Series` TEXT,
  `National_ID_Issuing_Agency` TEXT,
  `National_ID_Verified_By_Reference_ID` TEXT,
  `National_ID_Verified_By_Reference_ID_Type` TEXT,
  `National_ID_Shared_Reference_ID` TEXT,
  `National_ID_Shared_Reference_ID_Type` TEXT,
  `Government_ID_Delete` TEXT,
  `Government_ID_Reference_ID` TEXT,
  `Government_ID_Reference_ID_Type` TEXT,
  `Government_ID_Data_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID` TEXT,
  `Government_ID_ID_Type_Reference_ID_Type` TEXT,
  `Government_ID_Country_Reference_ID` TEXT,
  `Government_ID_Country_Reference_ID_Type` TEXT,
  `Government_ID_Issued_Date` TEXT,
  `Government_ID_Expiration_Date` TEXT,
  `Government_ID_Verification_Date` TEXT,
  `Government_ID_Verified_by_Reference_ID` TEXT,
  `Government_ID_Verified_by_Reference_ID_Type` TEXT,
  `Government_ID_Shared_Reference_ID` TEXT,
  `Government_ID_Shared_Reference_ID_Type` TEXT,
  `Visa_ID_Delete` TEXT,
  `Visa_ID_Reference_ID` TEXT,
  `Visa_ID_Reference_ID_Type` TEXT,
  `Visa_ID_Data_ID` TEXT,
  `Visa_ID_ID_Type_Reference_ID` TEXT,
  `Visa_ID_ID_Type_Reference_ID_Type` TEXT,
  `Visa_ID_Country_Reference_ID` TEXT,
  `Visa_ID_Country_Reference_ID_Type` TEXT,
  `Visa_ID_Issued_Date` TEXT,
  `Visa_ID_Expiration_Date` TEXT,
  `Visa_ID_Verification_Date` TEXT,
  `Visa_ID_Verified_By_Reference_ID` TEXT,
  `Visa_ID_Verified_By_Reference_ID_Type` TEXT,
  `Visa_ID_Shared_Reference_ID` TEXT,
  `Visa_ID_Shared_Reference_ID_Type` TEXT,
  `Passport_ID_Delete` TEXT,
  `Passport_ID_Reference_ID` TEXT,
  `Passport_ID_Reference_ID_Type` TEXT,
  `Passport_ID_Data_ID` TEXT,
  `Passport_ID_ID_Type_Reference_ID` TEXT,
  `Passport_ID_ID_Type_Reference_ID_Type` TEXT,
  `Passport_ID_Country_Reference_ID` TEXT,
  `Passport_ID_Country_Reference_ID_Type` TEXT,
  `Passport_ID_Issued_Date` TEXT,
  `Passport_ID_Expiration_Date` TEXT,
  `Passport_ID_Verification_Date` TEXT,
  `Passport_ID_Verified_By_Reference_ID` TEXT,
  `Passport_ID_Verified_By_Reference_ID_Type` TEXT,
  `Passport_ID_Shared_Reference_ID` TEXT,
  `Passport_ID_Shared_Reference_ID_Type` TEXT,
  `License_ID_Delete` TEXT,
  `License_ID_Reference_ID` TEXT,
  `License_ID_Reference_ID_Type` TEXT,
  `License_ID_Data_ID` TEXT,
  `License_ID_ID_Type_Reference_ID` TEXT,
  `License_ID_ID_Type_Reference_ID_Type` TEXT,
  `License_ID_Country_Reference_ID` TEXT,
  `License_ID_Country_Reference_ID_Type` TEXT,
  `License_ID_Country_Region_Reference_ID` TEXT,
  `License_ID_Country_Region_Reference_ID_Type` TEXT,
  `License_ID_Country_Region_Descriptor` TEXT,
  `License_ID_Authority_Reference_ID` TEXT,
  `License_ID_Authority_Reference_ID_Type` TEXT,
  `License_ID_License_Class` TEXT,
  `License_ID_Issued_Date` TEXT,
  `License_ID_Expiration_Date` TEXT,
  `License_ID_Verification_Date` TEXT,
  `License_ID_Verified_By_Reference_ID` TEXT,
  `License_ID_Verified_By_Reference_ID_Type` TEXT,
  `License_ID_Shared_Reference_ID` TEXT,
  `License_ID_Shared_Reference_ID_Type` TEXT,
  `Custom_ID_Delete` TEXT,
  `Custom_ID_Reference_ID` TEXT,
  `Custom_ID_Reference_ID_Type` TEXT,
  `Custom_ID_Data_ID` TEXT,
  `Custom_ID_Type_Reference_ID` TEXT,
  `Custom_ID_Type_Reference_ID_Type` TEXT,
  `Custom_ID_Issued_Date` TEXT,
  `Custom_ID_Expiration_Date` TEXT,
  `Custom_ID_Organization_ID` TEXT,
  `Custom_ID_Organization_ID_Type` TEXT,
  `Custom_ID_Description` TEXT,
  `Custom_ID_Shared_Reference_ID` TEXT,
  `Custom_ID_Shared_Reference_ID_Type` TEXT,
  `Date_of_Birth` TEXT,
  `Date_of_Death` TEXT,
  `Gender_Reference_ID` TEXT,
  `Gender_Reference_ID_Type` TEXT,
  `Court_Order_Benefit_Coverage_Type_Reference_ID` TEXT,
  `Court_Order_Benefit_Coverage_Type_Reference_ID_Type` TEXT,
  `Court_Order_Start_Date` TEXT,
  `Court_Order_End_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_beneficiary_trust`;
CREATE TABLE `src_put_beneficiary_trust`(
  `Beneficiary_ID` TEXT,
  `Employee_ID` TEXT,
  `Trust_Name` TEXT,
  `Trust_Tax_ID` TEXT,
  `Trust_Trust_Date` TEXT,
  `Trustee_Name_Is_Legal` TEXT,
  `Trustee_Name_Is_Preferred` TEXT,
  `Trustee_Name_Effective_Date` TEXT,
  `Trustee_Name_Last_Modified` TEXT,
  `Trustee_Name_Country_ISO_Code` TEXT,
  `Trustee_Name_Additional_Name_Type` TEXT,
  `Trustee_Name_Prefix` TEXT,
  `Trustee_Name_Prefix_Type` TEXT,
  `Trustee_Name_First_Name` TEXT,
  `Trustee_Name_Middle_Name` TEXT,
  `Trustee_Name_Last_Name` TEXT,
  `Trustee_Name_Last_Name_Type` TEXT,
  `Trustee_Name_Local_Name` TEXT,
  `Trustee_Name_Local_Script` TEXT,
  `Trustee_Name_Local_First_Name` TEXT,
  `Trustee_Name_Local_Middle_Name` TEXT,
  `Trustee_Name_Local_Last_Name` TEXT,
  `Trustee_Name_Local_Last_Name_Type` TEXT,
  `Trustee_Name_Suffix` TEXT,
  `Trustee_Name_Suffix_Type` TEXT,
  `Trustee_Address_Last_Modified` TEXT,
  `Trustee_Address_Effective_Date` TEXT,
  `Trustee_Address_Country_ISO_Code` TEXT,
  `Trustee_Address_Line` TEXT,
  `Trustee_Address_Line_Descriptor` TEXT,
  `Trustee_Address_Line_Type` TEXT,
  `Trustee_Address_Municipality` TEXT,
  `Trustee_Address_Submunicipality` TEXT,
  `Trustee_Address_Region` TEXT,
  `Trustee_Address_Subregion` TEXT,
  `Trustee_Address_Subregion_Descriptor` TEXT,
  `Trustee_Address_Subregion_Type` TEXT,
  `Trustee_Address_Postal_Code` TEXT,
  `Trustee_Address_Public` TEXT,
  `Trustee_Address_Type_Reference` TEXT,
  `Trustee_Address_Primary` TEXT,
  `Trustee_Address_Use_For_Reference` TEXT,
  `Trustee_Address_Comments` TEXT,
  `Trustee_Phone_Country_ISO_Code` TEXT,
  `Trustee_Phone_International_Phone_Code` TEXT,
  `Trustee_Phone_Area_Code` TEXT,
  `Trustee_Phone_Number` TEXT,
  `Trustee_Phone_Extension` TEXT,
  `Trustee_Phone_Device_Type_Description` TEXT,
  `Trustee_Phone_Public` TEXT,
  `Trustee_Phone_Type_Reference` TEXT,
  `Trustee_Phone_Primary` TEXT,
  `Trustee_Phone_Use_For_Reference` TEXT,
  `Trustee_Phone_Comments` TEXT,
  `Trustee_Email_Address` TEXT,
  `Trustee_Email_Comment` TEXT,
  `Trustee_Email_Public` TEXT,
  `Trustee_Email_Type_Reference` TEXT,
  `Trustee_Email_Primary` TEXT,
  `Trustee_Email_Use_For_Reference` TEXT,
  `Trustee_Email_Comments` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Beneficiary_DCDD Section ***/


/*** Start of Put_Benefit_Annual_Credit_DCDD Section created from https://app.smartsheet.com/sheets/PhVrJCQgQ8FPVXFMh4pRMjcq3pFCmHr9prRRqm81?view=grid ***/

DROP TABLE IF EXISTS `src_put_benefit_annual_credit`;
CREATE TABLE `src_put_benefit_annual_credit`(
  `Effective_Date` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Benefit_Annual_Credit` TEXT,
  `Benefit_Annual_Credit_Currency_Reference_ID` TEXT,
  `Benefit_Annual_Credit_Currency_Reference_ID_Type` TEXT,
  `Benefit_Annual_Credit_Type_Reference_ID` TEXT,
  `Benefit_Annual_Credit_Type_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Benefit_Annual_Credit_DCDD Section ***/


/*** Start of Put_Benefit_Annual_Rate_DCDD Section created from https://app.smartsheet.com/sheets/GR2gj5qpHMMFp7q9344MMgJ35JVvRfFpw3PXp981?view=grid ***/

DROP TABLE IF EXISTS `src_put_benefit_annual_rate`;
CREATE TABLE `src_put_benefit_annual_rate`(
  `Benefit_Annual_Rate_Reference_ID` TEXT,
  `Benefit_Annual_Rate_Reference_ID_Type` TEXT,
  `Benefit_Annual_Rate_ID` TEXT,
  `Effective_Date` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Benefit_Annual_Rate` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Benefit_Annual_Rate_Type_Reference_ID` TEXT,
  `Benefit_Annual_Rate_Type_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Benefit_Annual_Rate_DCDD Section ***/


/*** Start of Put_Postal_Code_Set_DCDD Section created from https://app.smartsheet.com/sheets/4Jpm9Gf3WrPCv97jJFrXRFR4JJ2FjvR96C7wpRG1?view=grid ***/

DROP TABLE IF EXISTS `src_put_postal_code_set`;
CREATE TABLE `src_put_postal_code_set`(
  `Postal_Code_Set_Reference_ID` TEXT,
  `Postal_Code_Set_Reference_ID_Type` TEXT,
  `Name` TEXT,
  `Postal_Code_Set_Description` TEXT,
  `Postal_Code` TEXT,
  `Country_Region_Reference_ID` TEXT,
  `Country_Region_Reference_ID_Type` TEXT,
  `Effective_Date` TEXT,
  `Postal_Code_Set_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Postal_Code_Set_DCDD Section ***/


/*** Start of Put_Worker_Wellness_Data_DCDD Section created from https://app.smartsheet.com/sheets/xVm9GCfV7Mwvfwpcm38f5xG9jqQ5px8QRPV4Vcp1?view=grid ***/

DROP TABLE IF EXISTS `src_put_worker_wellness_data`;
CREATE TABLE `src_put_worker_wellness_data`(
  `Worker_Wellness_Data_Reference_ID` TEXT,
  `Worker_Wellness_Data_Reference_ID_Type` TEXT,
  `Wellness_ID` TEXT,
  `Effective_Date` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Participates_in_Wellness_Date` TEXT,
  `Participates_in_Wellness_Program` TEXT,
  `Wellness_Score_Date` TEXT,
  `Wellness_Score` TEXT,
  `Uses_Tobacco_Date` TEXT,
  `Uses_Tobacco` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Worker_Wellness_Data_DCDD Section ***/


/* NO LONGER SETTING UP AS AN SP
SET autocommit=1;
END STAGING;
*/