/*
    Staging Table: payroll
    Version: AutoCreated
    Comments: DDL created from https://app.smartsheet.com/sheets/FHw3c6hXHpQM2XhHrcFJmMpxJC3r8Cc4JPpvv3r1?view=grid
*/

/* NO LONGER SETTING UP AS AN SP
USE hellboy;     
DROP PROCEDURE IF EXISTS `sp_slng_ddl_payroll`;
-- DELIMITER $$   -- *** Comment out the delimiter declaration to load via SLNG *** -- 
CREATE DEFINER=`slng_user`@`%` PROCEDURE `sp_slng_ddl_payroll`()
  STAGING:BEGIN
*/

/*** Start of AddUpdate_Employee_Pay_Group_Assignment_DCDD Section created from https://app.smartsheet.com/sheets/jPcHP86852Pc7h98Xr867fhH3RrPWPQPqxfgF9H1?view=grid ***/

DROP TABLE IF EXISTS `src_addupdate_employee_pay_group_assignment`;
CREATE TABLE `src_addupdate_employee_pay_group_assignment`(
  `Effective_Date` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Pay_Group_Reference_ID` TEXT,
  `Pay_Group_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of AddUpdate_Employee_Pay_Group_Assignment_DCDD Section ***/


/*** Start of AddUpdate_Pay_Run_Group_DCDD Section created from https://app.smartsheet.com/sheets/gjG98GF6VvGg492cw7xFmpVXXQFv78G3qhRWjHg1?view=grid ***/

DROP TABLE IF EXISTS `src_addupdate_pay_run_group`;
CREATE TABLE `src_addupdate_pay_run_group`(
  `Pay_Run_Group_Name` TEXT,
  `Integration_ID_Reference_ID` TEXT,
  `Integration_ID_Reference_ID_System_ID` TEXT,
  `Run_Category_Name` TEXT,
  `Schedule_Name` TEXT,
  `Frequency_Name` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of AddUpdate_Pay_Run_Group_DCDD Section ***/


/*** Start of Assign_Pay_Group_DCDD Section created from https://app.smartsheet.com/sheets/vCq7V548H8V95w8qR22j4x2wPvPqqX7qc4542Mc1?view=grid ***/

DROP TABLE IF EXISTS `src_assign_pay_group`;
CREATE TABLE `src_assign_pay_group`(
  `Assign_Pay_Group_Event_Reference_ID` TEXT,
  `Assign_Pay_Group_Event_Reference_ID_Type` TEXT,
  `Assign_Pay_Group_Event_ID` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Pay_Group_Reference_ID` TEXT,
  `Pay_Group_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Effective_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Assign_Pay_Group_DCDD Section ***/


/*** Start of Import_Payroll_Input_DCDD Section created from https://app.smartsheet.com/sheets/M4hgP6fVQ478W5wxHfVxR58vcx5cG9mX638qgWX1?view=grid ***/

DROP TABLE IF EXISTS `src_import_payroll_input_request`;
CREATE TABLE `src_import_payroll_input_request`(
  `Default_Batch_ID` TEXT,
  `Payroll_Input_Data_Last_Period_End_Date` TEXT,
  `Payroll_Input_ID` TEXT,
  `Batch_ID` TEXT,
  `Source_Reference_ID` TEXT,
  `Source_Reference_ID_Type` TEXT,
  `Ongoing_Input` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT,
  `Run_Category_Reference_ID` TEXT,
  `Run_Category_Reference_ID_Type` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Amount` TEXT,
  `Hours` TEXT,
  `Rate` TEXT,
  `Adjustment` TEXT,
  `Location_Reference_ID` TEXT,
  `Location_Reference_ID_Type` TEXT,
  `Region_Reference_ID` TEXT,
  `Region_Reference_ID_Type` TEXT,
  `Job_Profile_Reference_ID` TEXT,
  `Job_Profile_Reference_ID_Type` TEXT,
  `Cost_Center_Reference_ID` TEXT,
  `Cost_Center_Reference_ID_Type` TEXT,
  `Withholding_Order_Case_Reference_ID` TEXT,
  `Withholding_Order_Case_Reference_ID_Type` TEXT,
  `State_Authority_Reference_ID` TEXT,
  `State_Authority_Reference_ID_Type` TEXT,
  `Workers_Compensation_Code_Reference_ID` TEXT,
  `Workers_Compensation_Code_Reference_ID_Type` TEXT,
  `County_Authority_Reference_ID` TEXT,
  `County_Authority_Reference_ID_Type` TEXT,
  `City_Authority_Reference_ID` TEXT,
  `City_Authority_Reference_ID_Type` TEXT,
  `School_District_Authority_Reference_ID` TEXT,
  `School_District_Authority_Reference_ID_Type` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Object_Class_Reference_ID` TEXT,
  `Object_Class_Reference_ID_Type` TEXT,
  `Custom_Organization_Reference_ID` TEXT,
  `Custom_Organization_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `NI_Category_Reference_ID` TEXT,
  `NI_Category_Reference_ID_Type` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID_Type` TEXT,
  `Income_Code_Reference_ID` TEXT,
  `Income_Code_Reference_ID_Type` TEXT,
  `Exemption_Code_Reference_ID` TEXT,
  `Exemption_Code_Reference_ID_Type` TEXT,
  `Tax_Residency_Country_Reference_ID` TEXT,
  `Tax_Residency_Country_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Phase_Reference_ID` TEXT,
  `Project_Phase_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Related_Calculation_Reference_ID` TEXT,
  `Related_Calculation_Reference_ID_Type` TEXT,
  `Input_Value` TEXT,
  `Date_Input_Value` TEXT,
  `Boolean_Input_Value` TEXT,
  `Text_Input_Value` TEXT,
  `Comment` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Match_Existing_Input` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT,
  `Costing_Company_Reference_ID` TEXT,
  `Costing_Company_Reference_ID_Type` TEXT,
  `Prior_Period_Tax_Adjustment` TEXT,
  `Coverage_Start_Date` TEXT,
  `Coverage_End_Date` TEXT,
  `Earning_Reference_ID` TEXT,
  `Earning_Reference_ID_Type` TEXT,
  `Deduction_Reference_ID` TEXT,
  `Deduction_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_import_payroll_input_request_details`;
CREATE TABLE `src_import_payroll_input_request_details`(
  `Default_Batch_ID` TEXT,
  `Batch_ID` TEXT,
  `Start_Date` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID_Type` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Import_Payroll_Input_DCDD Section ***/


/*** Start of Put_Company_Tax_Reporting_DCDD Section created from https://app.smartsheet.com/sheets/qcX2qP49MF566vVVp724wRHR6q3MHhXCqCgqHxH1?view=grid ***/

DROP TABLE IF EXISTS `src_put_company_tax_reporting`;
CREATE TABLE `src_put_company_tax_reporting`(
  `Company_Tax_Reporting_Reference_ID` TEXT,
  `Company_Tax_Reporting_Reference_ID_Type` TEXT,
  `Company_Tax_Reporting_ID` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT,
  `Use_Above_EI_N` TEXT,
  `Payroll_Tax_Authority_EI_N` TEXT,
  `Exemptfrom_SU_I` TEXT,
  `Use_Tax_Override_Rate` TEXT,
  `Tax_Override_Rate` TEXT,
  `Payment_Limit_Override` TEXT,
  `Excludefrom_Tax_Filing` TEXT,
  `Use_Alternate_Wage_Limit` TEXT,
  `Alternate_Wage_Limit` TEXT,
  `Multistate_Resident_Rule_Calculate_State_Reference_ID` TEXT,
  `Multistate_Resident_Rule_Calculate_State_Reference_ID_Type` TEXT,
  `Multistate_Resident_Rule_Calculation_Method_Reference_ID` TEXT,
  `Multistate_Resident_Rule_Calculation_Method_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_company_tax_reporting_details`;
CREATE TABLE `src_put_company_tax_reporting_details`(
  `Company_Reference_ID` TEXT,
  `Deduction_All_Object_ID` TEXT,
  `Deduction_All_Object_ID_Type` TEXT,
  `Supplemental_Tax_Method_Separate_Check_Object_ID` TEXT,
  `Supplemental_Tax_Method_Separate_Check_Object_ID_Type` TEXT,
  `Supplemental_Tax_Method_Single_Check_Object_ID` TEXT,
  `Supplemental_Tax_Method_Single_Check_Object_ID_Type` TEXT,
  `Payroll_Tax_Authority_Object_ID` TEXT,
  `Payroll_Tax_Authority_Object_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Company_Tax_Reporting_DCDD Section ***/


/*** Start of Put_Customer_Tax_Information_DCDD Section created from https://app.smartsheet.com/sheets/JwC26Jpvwf76Q5h6rF48wRfqwX45HpmpHWRvj8r1?view=grid ***/

DROP TABLE IF EXISTS `src_put_customer_tax_information`;
CREATE TABLE `src_put_customer_tax_information`(
  `Customer_Reference_ID` TEXT,
  `Customer_Reference_ID_Type` TEXT,
  `Tax_Info_Customer_ID` TEXT,
  `Tax_Info_Customer_Reference_ID` TEXT,
  `Address_Level_Tax_Details_Delete` TEXT,
  `Reference_ID` TEXT,
  `Tax_ID_Type_Reference_ID` TEXT,
  `Tax_ID_Type_Reference_ID_Type` TEXT,
  `Tax_ID_Identification` TEXT,
  `Transaction_Tax_Status_Reference_ID` TEXT,
  `Transaction_Tax_Status_Reference_ID_Type` TEXT,
  `Transaction_Tax_ID` TEXT,
  `Inactive` TEXT,
  `Replace_All` TEXT,
  `Entity_Activity_Code_Delete` TEXT,
  `Entity_Activity_Code_Reference_ID` TEXT,
  `Entity_Activity_Code_Reference_ID_Type` TEXT,
  `Code` TEXT,
  `Entity_Activity_Code_Type_Reference_ID` TEXT,
  `Entity_Activity_Code_Type_Reference_ID_Type` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Description` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_customer_tax_information_addr`;
CREATE TABLE `src_put_customer_tax_information_addr`(
  `Tax_Info_Customer_ID` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Customer_Tax_Information_DCDD Section ***/


/*** Start of Put_Deduction_DCDD Section created from https://app.smartsheet.com/sheets/76WCpf4pQcgXm97jrrxP7GpFCP39jXh28HwJ9Q21?view=grid ***/

DROP TABLE IF EXISTS `src_put_deduction`;
CREATE TABLE `src_put_deduction`(
  `Add_Only` TEXT,
  `Deduction_Reference_ID` TEXT,
  `Deduction_Reference_ID_Type` TEXT,
  `Name` TEXT,
  `Deduction_Code` TEXT,
  `Default_Payslip_Name` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Comments` TEXT,
  `Input_Amount_Allowed` TEXT,
  `Prorate_Using_Calendar_Days` TEXT,
  `Prorate_Using_Days_Worked` TEXT,
  `Prorate_Using_Annual_Working_Days` TEXT,
  `Annual_Working_Days_Calculation_Reference_ID` TEXT,
  `Annual_Working_Days_Calculation_Reference_ID_Type` TEXT,
  `Override_Frequency_Reference_ID` TEXT,
  `Override_Frequency_Reference_ID_Type` TEXT,
  `Recalculate_during_Retro` TEXT,
  `Do_Not_Apply_Percent_Splits_for_Ongoing_Multiple_Work_Jurisd` TEXT,
  `Worktag_Type_Reference_ID` TEXT,
  `Worktag_Type_Reference_ID_Type` TEXT,
  `Include_Input_Worktags` TEXT,
  `Coverage_Cost_As_Of_Payment_Date` TEXT,
  `Effective_Date` TEXT,
  `Inactive` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_deduction_details`;
CREATE TABLE `src_put_deduction_details`(
  `Deduction_Code` TEXT,
  `PCG_Add_or_Reference_Calculation_Type` TEXT,
  `PCG_Add_or_Reference_Workday_Owned` TEXT,
  `PCG_Add_or_Reference_Calculation_Name` TEXT,
  `PCG_Add_or_Reference_ID` TEXT,
  `PCG_Add_or_Reference_Type` TEXT,
  `PCG_Add_or_Reference_WID` TEXT,
  `Eligibility_Run_Category_Reference_ID` TEXT,
  `Eligibility_Run_Category_Reference_ID_Type` TEXT,
  `Eligibility_Pay_Group_Detail_Reference_ID` TEXT,
  `Eligibility_Pay_Group_Detail_Reference_ID_Type` TEXT,
  `Worker_Eligibility_Order` TEXT,
  `Worker_Eligibility_Calculation_Type` TEXT,
  `Worker_Eligibility_Calculation_Workday_Owned` TEXT,
  `Worker_Eligibility_Calculation_Name` TEXT,
  `Worker_Eligibility_Calculation_ID` TEXT,
  `Worker_Eligibility_Calculation_Reference_Type` TEXT,
  `Worker_Eligibility_Calculation_WID` TEXT,
  `Scheduling_Order` TEXT,
  `Scheduling_Calculation_Reference_Calculation_Type` TEXT,
  `Scheduling_Calculation_Reference_Workday_Owned` TEXT,
  `Scheduling_Calculation_Reference_Calculation_Name` TEXT,
  `Scheduling_Calculation_ID` TEXT,
  `Scheduling_Calculation_Reference_Type` TEXT,
  `Scheduling_Calculation_Reference_WID` TEXT,
  `Numeric_Calculation_Reference_Calculation_Type` TEXT,
  `Numeric_Calculation_Reference_Workday_Owned` TEXT,
  `Numeric_Calculation_Reference_Calculation_Name` TEXT,
  `Numeric_Calculation_ID` TEXT,
  `Numeric_Calculation_Reference_Type` TEXT,
  `Numeric_Calculation_Reference_WID` TEXT,
  `Events_Causing_Payroll_Proration_Event_Type_Reference_ID` TEXT,
  `Events_Causing_Payroll_Proration_Event_Type_Reference_ID_Type` TEXT,
  `Calculation_Worktag_Reference_ID` TEXT,
  `Calculation_Worktag_Reference_ID_Type` TEXT,
  `Benefit_Plan_Reference_ID` TEXT,
  `Benefit_Plan_Reference_ID_Type` TEXT,
  `ROE_Earning_Period_Allocation_Method_Reference_ID` TEXT,
  `ROE_Earning_Period_Allocation_Method_Reference_ID_Type` TEXT,
  `ROE_Allocation_Method_for_Retro_Amount_Reference_ID` TEXT,
  `ROE_Allocation_Method_for_Retro_Amount_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_deduction_limits`;
CREATE TABLE `src_put_deduction_limits`(
  `Deduction_Code` TEXT,
  `Limits_Value_Calculation_Type` TEXT,
  `Limits_Value_Calculation_Workday_Owned` TEXT,
  `Limits_Value_Calculation_Name` TEXT,
  `Limits_Value_Calculation_ID` TEXT,
  `Limits_Value_Calculation_Reference_Type` TEXT,
  `Limits_Value_Calculation_WID` TEXT,
  `Limits_Balance_Period` TEXT,
  `Limits_Balance_Period_Workday_Owned` TEXT,
  `Limits_Balance_Period_Calculation_Type` TEXT,
  `Pay_Accumulation_Workday_Owned` TEXT,
  `Limits_Balance_Period_Calculation_Name` TEXT,
  `Limits_Balance_Period_ID` TEXT,
  `Limits_Balance_Period_Reference_Type` TEXT,
  `Limits_Balance_Period_WID` TEXT,
  `Limits_Include_Current_Value_Calculation_Type` TEXT,
  `Limits_Include_Current_Value_Workday_Owned` TEXT,
  `Limits_Include_Current_Value_Calculation_Name` TEXT,
  `Limits_Include_Current_Value_ID` TEXT,
  `Limits_Include_Current_Value_Reference_Type` TEXT,
  `Limits_Include_Current_Value_WID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_deduction_pcrc`;
CREATE TABLE `src_put_deduction_pcrc`(
  `Deduction_Code` TEXT,
  `PCRC_PCG_AoR_Calculation_Type` TEXT,
  `PCRC_PCG_AoR_Workday_Owned` TEXT,
  `PCRC_PCG_AoR_Calculation_Name` TEXT,
  `PCRC_PCG_AoR_ID` TEXT,
  `PCRC_PCG_AoR_Reference_Type` TEXT,
  `PCRC_PCG_AoR_WID` TEXT,
  `PCRC_RelCalcRef_Calculation_Type` TEXT,
  `PCRC_RelCalcRef_Workday_Owned` TEXT,
  `PCRC_RelCalcRef_Calculation_Name` TEXT,
  `PCRC_RelCalcRef_ID` TEXT,
  `PCRC_RelCalcRef_Reference_Type` TEXT,
  `PCRC_RelCalcRef_WID` TEXT,
  `PCRC_OverrideValue_NumCalc_Calculation_Type` TEXT,
  `PCRC_OverrideValue_NumCalc_Workday_Owned` TEXT,
  `PCRC_OverrideValue_NumCalc_Calculation_Name` TEXT,
  `PCRC_OverrideValue_NumCalc_ID` TEXT,
  `PCRC_OverrideValue_NumCalc_Reference_Type` TEXT,
  `PCRC_OverrideValue_NumCalc_WID` TEXT,
  `PCRC_FLSA_Premium_Calculation_Type_Reference_ID` TEXT,
  `PCRC_FLSA_Premium_Calculation_Type_Reference_ID_Type` TEXT,
  `PCRC_LimitValue_Calculation_Type` TEXT,
  `PCRC_LimitValue_Workday_Owned` TEXT,
  `PCRC_LimitValue_Calculation_Name` TEXT,
  `PCRC_LimitValue_ID` TEXT,
  `PCRC_LimitValue_Reference_Type` TEXT,
  `PCRC_LimitValue_WID` TEXT,
  `PCRC_LimitBalPeriod_Balance_Period` TEXT,
  `PCRC_LimitBalPeriod_Workday_Owned` TEXT,
  `PCRC_BasedOnPayAccum_Calculation_Type` TEXT,
  `PCRC_BasedOnPayAccum_Workday_Owned` TEXT,
  `PCRC_BasedOnPayAccum_Calculation_Name` TEXT,
  `PCRC_BasedOnPayAccum_ID` TEXT,
  `PCRC_BasedOnPayAccum_Reference_Type` TEXT,
  `PCRC_BasedOnPayAccum_WID` TEXT,
  `PCRC_InclCurrValue_Calculation_Type` TEXT,
  `PCRC_InclCurrValue_Workday_Owned` TEXT,
  `PCRC_InclCurrValue_Calculation_Name` TEXT,
  `PCRC_InclCurrValue_ID` TEXT,
  `PCRC_InclCurrValue_Reference_Type` TEXT,
  `PCRC_InclCurrValue_WID` TEXT,
  `PCRC_Limit_Filter_Worktags_Reference_ID` TEXT,
  `PCRC_Limit_Filter_Worktags_Reference_ID_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Calculation_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Workday_Owned` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Calculation_Name` TEXT,
  `PCRC_ConditionLimitFilterWorktags_ID` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Reference_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_WID` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Worktag_Name` TEXT,
  `PCRC_Code` TEXT,
  `PCRC_Input_Allowed` TEXT,
  `PCRC_Aggregate` TEXT,
  `PCRC_Do_Not_Store_as_Related_Result_Line` TEXT,
  `PCRC_Do_Not_Store_as_Related_Result_Line_if_Zero` TEXT,
  `PCRC_Display_Current` TEXT,
  `PCRC_Display_Current_and_Balances` TEXT,
  `PCRC_Hours_at_Result_Level` TEXT,
  `PCRC_Option_for_Result_Line_Reporting_of_Hours_Ref_ID` TEXT,
  `PCRC_Option_for_Result_Line_Reporting_of_Hours_Ref_ID_Type` TEXT,
  `PCRC_OverrideRelCalc_Do_Not_Apply_Percentage_Splits` TEXT,
  `PCRC_OverrideRelCalc_Apply_Percentage_Splits` TEXT,
  `PCRC_Hide_on_Retro_Results` TEXT,
  `PCRC_Pay_Comp_Related_Calculation_Order` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Deduction_DCDD Section ***/


/*** Start of Put_Earning_DCDD Section created from https://app.smartsheet.com/sheets/PMRphg783V5cwHRX64Q3p4H7WQvh7wRfvhmC3gC1?view=grid ***/

DROP TABLE IF EXISTS `src_put_earning`;
CREATE TABLE `src_put_earning`(
  `Add_Only` TEXT,
  `Earning_Reference_ID` TEXT,
  `Earning_Reference_ID_Type` TEXT,
  `Name` TEXT,
  `Earning_Code` TEXT,
  `Default_Payslip_Name` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Comments` TEXT,
  `Input_Amount_Allowed` TEXT,
  `Prorate_Using_Calendar_Days` TEXT,
  `Prorate_Using_Days_Worked` TEXT,
  `Prorate_Using_Annual_Working_Days` TEXT,
  `Annual_Working_Days_Calculation_Reference_ID` TEXT,
  `Annual_Working_Days_Calculation_Reference_ID_Type` TEXT,
  `Always_Gross_Up` TEXT,
  `Gross_Up_Type_Reference_ID` TEXT,
  `Gross_Up_Type_Reference_ID_Type` TEXT,
  `Gross_Up_Percentage` TEXT,
  `Resolve_by_FLSA_Period` TEXT,
  `FLSA_Bonus_Allocation_Across_Coverage_Dates_Ref_ID` TEXT,
  `FLSA_Bonus_Allocation_Across_Coverage_Dates_Ref_ID_Type` TEXT,
  `Subject_to_State_Rules_for_Flat_Sum_Bonus` TEXT,
  `Allow_Coverage_Dates_for_Bonuses` TEXT,
  `Do_Not_Apply_Percent_Splits_for_Ongoing_Multiple_Work_Jurisd` TEXT,
  `Override_Frequency_Reference_ID` TEXT,
  `Override_Frequency_Reference_ID_Type` TEXT,
  `Do_Not_Recalculate_During_Retro` TEXT,
  `Worktag_Type_Reference_ID` TEXT,
  `Worktag_Type_Reference_ID_Type` TEXT,
  `Include_Input_Worktags` TEXT,
  `Coverage_Cost_As_Of_Payment_Date` TEXT,
  `Exclude_From_Forward_Accrual` TEXT,
  `Effective_Date` TEXT,
  `Inactive` TEXT,
  `Split_by_UK_Statutory_Holiday_Pay_Work_Period_Calendar` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_earning_details`;
CREATE TABLE `src_put_earning_details`(
  `Earning_Code` TEXT,
  `PCG_Add_or_Reference_Calculation_Type` TEXT,
  `PCG_Add_or_Reference_Workday_Owned` TEXT,
  `PCG_Add_or_Reference_Calculation_Name` TEXT,
  `PCG_Add_or_Reference_ID` TEXT,
  `PCG_Add_or_Reference_Type` TEXT,
  `PCG_Add_or_Reference_WID` TEXT,
  `Eligibility_Run_Category_Reference_ID` TEXT,
  `Eligibility_Run_Category_Reference_ID_Type` TEXT,
  `Eligibility_Pay_Group_Detail_Reference_ID` TEXT,
  `Eligibility_Pay_Group_Detail_Reference_ID_Type` TEXT,
  `Worker_Eligibility_Order` TEXT,
  `Worker_Eligibility_Calculation_Type` TEXT,
  `Worker_Eligibility_Calculation_Workday_Owned` TEXT,
  `Worker_Eligibility_Calculation_Name` TEXT,
  `Worker_Eligibility_Calculation_ID` TEXT,
  `Worker_Eligibility_Calculation_Reference_Type` TEXT,
  `Worker_Eligibility_Calculation_WID` TEXT,
  `Scheduling_Order` TEXT,
  `Scheduling_Calculation_Reference_Calculation_Type` TEXT,
  `Scheduling_Calculation_Reference_Workday_Owned` TEXT,
  `Scheduling_Calculation_Reference_Calculation_Name` TEXT,
  `Scheduling_Calculation_ID` TEXT,
  `Scheduling_Calculation_Reference_Type` TEXT,
  `Scheduling_Calculation_Reference_WID` TEXT,
  `Numeric_Calculation_Reference_Calculation_Type` TEXT,
  `Numeric_Calculation_Reference_Workday_Owned` TEXT,
  `Numeric_Calculation_Reference_Calculation_Name` TEXT,
  `Numeric_Calculation_ID` TEXT,
  `Numeric_Calculation_Reference_Type` TEXT,
  `Numeric_Calculation_Reference_WID` TEXT,
  `Events_Causing_Payroll_Proration_Event_Type_Ref_ID` TEXT,
  `Events_Causing_Payroll_Proration_Event_Type_Ref_ID_Type` TEXT,
  `Calculation_Worktag_Reference_ID` TEXT,
  `Calculation_Worktag_Reference_ID_Type` TEXT,
  `Compensation_Element_Reference_ID` TEXT,
  `Compensation_Element_Reference_ID_Type` TEXT,
  `Time_Code_Reference_ID` TEXT,
  `Time_Code_Reference_ID_Type` TEXT,
  `Time_Calculation_Tag_Reference_ID` TEXT,
  `Time_Calculation_Tag_Reference_ID_Type` TEXT,
  `Benefit_Plan_Reference_ID` TEXT,
  `Benefit_Plan_Reference_ID_Type` TEXT,
  `Benefit_Group_Reference_ID` TEXT,
  `Benefit_Group_Reference_ID_Type` TEXT,
  `Benefit_Coverage_Type_Reference_ID` TEXT,
  `Benefit_Coverage_Type_Reference_ID_Type` TEXT,
  `Waived_Coverage_Type_Credit_Reference_ID` TEXT,
  `Waived_Coverage_Type_Credit_Reference_ID_Type` TEXT,
  `Waived_Coverage_Type_Credit_ID` TEXT,
  `ROE_Earning_Period_Allocation_Method_Reference_ID` TEXT,
  `ROE_Earning_Period_Allocation_Method_Reference_ID_Type` TEXT,
  `ROE_Earning_Period_for_Hours_Allocation_Method_Reference_ID` TEXT,
  `ROE_Earning_Period_for_Hours_Alloc_Method_RefID_Type` TEXT,
  `ROE_Allocation_Method_for_Retro_Amount_Reference_ID` TEXT,
  `ROE_Allocation_Method_for_Retro_Amount_Reference_ID_Type` TEXT,
  `ROE_Allocation_Method_for_Retro_Hours_Reference_ID` TEXT,
  `ROE_Allocation_Method_for_Retro_Hours_Reference_ID_Type` TEXT,
  `ROE_Reporting_Type_Reference_ID` TEXT,
  `ROE_Reporting_Type_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_earning_limits`;
CREATE TABLE `src_put_earning_limits`(
  `Earning_Code` TEXT,
  `Limits_Value_Calculation_Type` TEXT,
  `Limits_Value_Calculation_Workday_Owned` TEXT,
  `Limits_Value_Calculation_Name` TEXT,
  `Limits_Value_Calculation_ID` TEXT,
  `Limits_Value_Calculation_Reference_Type` TEXT,
  `Limits_Value_Calculation_WID` TEXT,
  `Limits_Balance_Period` TEXT,
  `Limits_Balance_Period_Workday_Owned` TEXT,
  `Limits_Balance_Period_Calculation_Type` TEXT,
  `Pay_Accumulation__Workday_Owned` TEXT,
  `Limits_Balance_Period_Calculation_Name` TEXT,
  `Limits_Balance_Period_ID` TEXT,
  `Limits_Balance_Period_Reference_Type` TEXT,
  `Limits_Balance_Period_WID` TEXT,
  `Limits_Include_Current_Value_Calculation_Type` TEXT,
  `Limits_Include_Current_Value_Workday_Owned` TEXT,
  `Limits_Include_Current_Value_Calculation_Name` TEXT,
  `Limits_Include_Current_Value_ID` TEXT,
  `Limits_Include_Current_Value_Reference_Type` TEXT,
  `Limits_Include_Current_Value_WID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_earning_pcrc`;
CREATE TABLE `src_put_earning_pcrc`(
  `Earning_Code` TEXT,
  `PCRC_PCG_AoR_Calculation_Type` TEXT,
  `PCRC_PCG_AoR_Workday_Owned` TEXT,
  `PCRC_PCG_AoR_Calculation_Name` TEXT,
  `PCRC_PCG_AoR_ID` TEXT,
  `PCRC_PCG_AoR_Reference_Type` TEXT,
  `PCRC_PCG_AoR_WID` TEXT,
  `PCRC_RelCalcRef_Calculation_Type` TEXT,
  `PCRC_RelCalcRef_Workday_Owned` TEXT,
  `PCRC_RelCalcRef_Calculation_Name` TEXT,
  `PCRC_RelCalcRef_ID` TEXT,
  `PCRC_RelCalcRef_Reference_Type` TEXT,
  `PCRC_RelCalcRef_WID` TEXT,
  `PCRC_OverrideValue_NumCalc_Calculation_Type` TEXT,
  `PCRC_OverrideValue_NumCalc_Workday_Owned` TEXT,
  `PCRC_OverrideValue_NumCalc_Calculation_Name` TEXT,
  `PCRC_OverrideValue_NumCalc_ID` TEXT,
  `PCRC_OverrideValue_NumCalc_Reference_Type` TEXT,
  `PCRC_OverrideValue_NumCalc_WID` TEXT,
  `PCRC_FLSA_Premium_Calculation_Type_Reference_ID` TEXT,
  `PCRC_FLSA_Premium_Calculation_Type_Reference_ID_Type` TEXT,
  `PCRC_LimitValue_Calculation_Type` TEXT,
  `PCRC_LimitValue_Workday_Owned` TEXT,
  `PCRC_LimitValue_Calculation_Name` TEXT,
  `PCRC_LimitValue_ID` TEXT,
  `PCRC_LimitValue_Reference_Type` TEXT,
  `PCRC_LimitValue_WID` TEXT,
  `PCRC_LimitBalPeriod_Balance_Period` TEXT,
  `PCRC_LimitBalPeriod_Workday_Owned` TEXT,
  `PCRC_BasedOnPayAccum_Calculation_Type` TEXT,
  `PCRC_BasedOnPayAccum_Workday_Owned` TEXT,
  `PCRC_BasedOnPayAccum_Calculation_Name` TEXT,
  `PCRC_BasedOnPayAccum_ID` TEXT,
  `PCRC_BasedOnPayAccum_Reference_Type` TEXT,
  `PCRC_BasedOnPayAccum_WID` TEXT,
  `PCRC_InclCurrValue_Calculation_Type` TEXT,
  `PCRC_InclCurrValue_Workday_Owned` TEXT,
  `PCRC_InclCurrValue_Calculation_Name` TEXT,
  `PCRC_InclCurrValue_ID` TEXT,
  `PCRC_InclCurrValue_Reference_Type` TEXT,
  `PCRC_InclCurrValue_WID` TEXT,
  `PCRC_Limit_Filter_Worktags_Reference_ID` TEXT,
  `PCRC_Limit_Filter_Worktags_Reference_ID_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Calculation_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Workday_Owned` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Calculation_Name` TEXT,
  `PCRC_ConditionLimitFilterWorktags_ID` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Reference_Type` TEXT,
  `PCRC_ConditionLimitFilterWorktags_WID` TEXT,
  `PCRC_ConditionLimitFilterWorktags_Worktag_Name` TEXT,
  `PCRC_Code` TEXT,
  `PCRC_Input_Allowed` TEXT,
  `PCRC_Aggregate` TEXT,
  `PCRC_Do_Not_Store_as_Related_Result_Line` TEXT,
  `PCRC_Do_Not_Store_as_Related_Result_Line_if_Zero` TEXT,
  `PCRC_Display_Current` TEXT,
  `PCRC_Display_Current_and_Balances` TEXT,
  `PCRC_Hours_at_Result_Level` TEXT,
  `PCRC_Option_for_Result_Line_Reporting_of_Hours_Ref_ID` TEXT,
  `PCRC_Option_for_Result_Line_Reporting_of_Hours_Ref_ID_Type` TEXT,
  `PCRC_OverrideRelCalc_Do_Not_Apply_Percentage_Splits` TEXT,
  `PCRC_OverrideRelCalc_Apply_Percentage_Splits` TEXT,
  `PCRC_Hide_on_Retro_Results` TEXT,
  `PCRC_Pay_Comp_Related_Calculation_Order` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Earning_DCDD Section ***/


/*** Start of Put_Pay_Group_DCDD Section created from https://app.smartsheet.com/sheets/wRxcjjrfHRpWM6PgxP8RWQh3252HrJCxRgG7RWJ1?view=grid ***/

DROP TABLE IF EXISTS `src_put_pay_group`;
CREATE TABLE `src_put_pay_group`(
  `Pay_Group_Reference_ID` TEXT,
  `Pay_Group_Reference_ID_Type` TEXT,
  `Effective_Date` TEXT,
  `Pay_Group_Data_ID` TEXT,
  `Include_Organization_ID_in_Name` TEXT,
  `Organization_Name` TEXT,
  `Phonetic_Name` TEXT,
  `Organization_Code` TEXT,
  `Include_Organization_Code_in_Name` TEXT,
  `Organization_Active` TEXT,
  `Availability_Date` TEXT,
  `Organization_Visibility_Reference_ID` TEXT,
  `Organization_Visibility_Reference_ID_Type` TEXT,
  `External_URL_Reference_ID` TEXT,
  `External_URL_Reference_ID_Type` TEXT,
  `Integration_ID_Data_ID` TEXT,
  `Integration_ID_Data_ID_System_ID` TEXT,
  `Organization_Subtype_Reference_ID` TEXT,
  `Organization_Subtype_Reference_ID_Type` TEXT,
  `Used_in_Payroll_Interface` TEXT,
  `Pay_Group_Country_Reference_ID` TEXT,
  `Pay_Group_Country_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_pay_group_details`;
CREATE TABLE `src_put_pay_group_details`(
  `Pay_Group_Data_ID` TEXT,
  `Organization_Container_Reference_ID` TEXT,
  `Organization_Container_Reference_ID_Type` TEXT,
  `Pay_Group_Detailed_Data_ID` TEXT,
  `Run_Category_Reference_ID` TEXT,
  `Run_Category_Reference_ID_Type` TEXT,
  `Period_Schedule_Reference_ID` TEXT,
  `Period_Schedule_Reference_ID_Type` TEXT,
  `Start_Period_Reference_ID` TEXT,
  `Start_Period_Reference_ID_Type` TEXT,
  `Days_from_Payment_Date_to_display_Payslip` TEXT,
  `Pay_Run_Group_Reference_ID` TEXT,
  `Pay_Run_Group_Reference_ID_Type` TEXT,
  `Pay_Run_Group_Data_ID` TEXT,
  `Pay_Run_Group_Name` TEXT,
  `Pay_Group_Selection_Reference_ID` TEXT,
  `Pay_Group_Selection_Reference_ID_Type` TEXT,
  `Pay_Group_Automatic_Assignment_Rule_Reference_ID` TEXT,
  `Pay_Group_Automatic_Assignment_Rule_Reference_ID_Type` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Pay_Group_DCDD Section ***/


/*** Start of Put_Paycheck_Delivery_Public_DCDD Section created from https://app.smartsheet.com/sheets/PqFG5GG8r6C7C7G48M836J67qrxjf3Wv52WW8gJ1?view=grid ***/

DROP TABLE IF EXISTS `src_put_paycheck_delivery_public`;
CREATE TABLE `src_put_paycheck_delivery_public`(
  `Paycheck_Delivery_ID` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Date_Last_Updated` TEXT,
  `Paycheck_Delivery_Method_Reference_ID` TEXT,
  `Paycheck_Delivery_Method_Reference_ID_Type` TEXT,
  `Payslip_Printing_Override_Reference_ID` TEXT,
  `Payslip_Printing_Override_Reference_ID_Type` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Paycheck_Delivery_Public_DCDD Section ***/


/*** Start of Put_Payment_Election_Option_DCDD Section created from https://app.smartsheet.com/sheets/GFmWm6Crv69CmXpgrgHCG7HV25MW743FRGcjjCj1?view=grid ***/

DROP TABLE IF EXISTS `src_put_payment_election_option`;
CREATE TABLE `src_put_payment_election_option`(
  `Add_Only` TEXT,
  `Payment_Election_Option_Reference_ID` TEXT,
  `Payment_Election_Option_Reference_ID_Type` TEXT,
  `Payment_Election_Option_ID` TEXT,
  `Role_Reference_ID` TEXT,
  `Role_Reference_ID_Type` TEXT,
  `Default_Country_Reference_ID` TEXT,
  `Default_Country_Reference_ID_Type` TEXT,
  `Default_Currency_Reference_ID` TEXT,
  `Default_Currency_Reference_ID_Type` TEXT,
  `Payment_Election_Rule_Reference_ID` TEXT,
  `Payment_Election_Rule_Reference_ID_Type` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Payment_Type_Reference_ID_1` TEXT,
  `Payment_Type_Reference_ID_2` TEXT,
  `Payment_Type_Reference_ID_3` TEXT,
  `Payment_Type_Reference_ID_4` TEXT,
  `Payment_Type_Reference_ID_5` TEXT,
  `Payment_Type_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Payment_Election_Option_DCDD Section ***/


/*** Start of Put_Payroll_Deduction_Recipient_DCDD Section created from https://app.smartsheet.com/sheets/q9qqR36pQrRWx49QWf67pcj7Xx75PhRjQx36QX31?view=grid ***/

DROP TABLE IF EXISTS `src_put_payroll_ded_recipient_settlement_addr`;
CREATE TABLE `src_put_payroll_ded_recipient_settlement_addr`(
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Settlement_Bank_Account_ID` TEXT,
  `Settlement_Account_Formatted_Address` TEXT,
  `Settlement_Account_Address_Format_Type` TEXT,
  `Settlement_Account_Defaulted_Business_Site_Address` TEXT,
  `Settlement_Account_Address_Delete` TEXT,
  `Settlement_Account_Address_Do_Not_Replace_All` TEXT,
  `Settlement_Account_Address_Effective_Date` TEXT,
  `Settlement_Account_Address_Country_Reference_ID` TEXT,
  `Settlement_Account_Address_Country_Reference_ID_Type` TEXT,
  `Settlement_Account_Last_Modified` TEXT,
  `Settlement_Account_Address_Line_Data` TEXT,
  `Settlement_Account_Line_Descriptor` TEXT,
  `Settlement_Account_Line_Type` TEXT,
  `Settlement_Account_Municipality` TEXT,
  `Settlement_Account_Country_City_Reference_ID` TEXT,
  `Settlement_Account_Country_City_Reference_ID_Type` TEXT,
  `Settlement_Account_Country_City_Reference_ID_Parent_ID` TEXT,
  `Settlement_Account_Country_City_Reference_ID_Parent_Type` TEXT,
  `Settlement_Account_Submunicipality_Data` TEXT,
  `Settlement_Account_Address_Component_Name` TEXT,
  `Settlement_Account_Submunicipality_Type` TEXT,
  `Settlement_Account_Country_Region_Reference_ID` TEXT,
  `Settlement_Account_Country_Region_Reference_ID_Type` TEXT,
  `Settlement_Account_Country_Region_Descriptor` TEXT,
  `Settlement_Account_Subregion_Data` TEXT,
  `Settlement_Account_Subregion_Descriptor` TEXT,
  `Settlement_Account_Subregion_Type` TEXT,
  `Settlement_Account_Postal_Code` TEXT,
  `Settlement_Account_Public` TEXT,
  `Settlement_Account_Address_Primary` TEXT,
  `Settlement_Account_Address_Type_Reference_ID` TEXT,
  `Settlement_Account_Address_Type_Reference_ID_Type` TEXT,
  `Settlement_Account_Use_For_Reference_ID` TEXT,
  `Settlement_Account_Use_For_Reference_ID_Type` TEXT,
  `Settlement_Account_Use_For_Tenanted_Reference_ID` TEXT,
  `Settlement_Account_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Settlement_Account_Comments` TEXT,
  `Settlement_Account_Number_of_Days` TEXT,
  `Settlement_Account_Municipality_Local` TEXT,
  `Settlement_Account_Address_Reference_ID` TEXT,
  `Settlement_Account_Address_Reference_ID_Type` TEXT,
  `Settlement_Account_Address_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_ded_recipient_settlement_intermed`;
CREATE TABLE `src_put_payroll_ded_recipient_settlement_intermed`(
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Settlement_Bank_Account_ID` TEXT,
  `Intermediary_Bank_Widget_Replace_All` TEXT,
  `Widget_Intermediary_Bank_Delete` TEXT,
  `Intermediary_Bank_Account_ID` TEXT,
  `Intermediary_Bank_Order` TEXT,
  `Widget_Intermediary_Bank_Country_Reference_ID` TEXT,
  `Widget_Intermediary_Bank_Country_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Currency_Reference_ID` TEXT,
  `Intermediary_Bank_Currency_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Bank_Account_Nickname` TEXT,
  `Intermediary_Bank_Bank_Account_Type_Reference_ID` TEXT,
  `Intermediary_Bank_Bank_Account_Type_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Bank_Name` TEXT,
  `Intermediary_Bank_Routing_Transit_Number` TEXT,
  `Intermediary_Bank_Branch_ID` TEXT,
  `Intermediary_Bank_Branch_Name` TEXT,
  `Intermediary_Bank_Bank_Account_Number` TEXT,
  `Intermediary_Bank_Check_Digit` TEXT,
  `Intermediary_Bank_Bank_Account_Name` TEXT,
  `Intermediary_Bank_Roll_Number` TEXT,
  `Intermediary_Bank_IBAN` TEXT,
  `Intermediary_Bank_SWIFT_Bank_Identification_Code` TEXT,
  `Intermediary_Bank_Inactive` TEXT,
  `Intermediary_Bank_Bank_Instructions` TEXT,
  `Intermediary_Bank_Formatted_Address` TEXT,
  `Intermediary_Bank_Address_Format_Type` TEXT,
  `Intermediary_Bank_Defaulted_Business_Site_Address` TEXT,
  `Intermediary_Bank_Address_Delete` TEXT,
  `Intermediary_Bank_Address_Do_Not_Replace_All` TEXT,
  `Intermediary_Bank_Address_Effective_Date` TEXT,
  `Intermediary_Bank_Address_Country_Reference_ID` TEXT,
  `Intermediary_Bank_Address_Country_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Last_Modified` TEXT,
  `Intermediary_Bank_Address_Line_Data` TEXT,
  `Intermediary_Bank_Line_Descriptor` TEXT,
  `Intermediary_Bank_Line_Type` TEXT,
  `Intermediary_Bank_Municipality` TEXT,
  `Intermediary_Bank_Country_City_Reference_ID` TEXT,
  `Intermediary_Bank_Country_City_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Country_City_Reference_ID_Parent_ID` TEXT,
  `Intermediary_Bank_Country_City_Reference_ID_Parent_Type` TEXT,
  `Intermediary_Bank_Submunicipality_Data` TEXT,
  `Intermediary_Bank_Address_Component_Name` TEXT,
  `Intermediary_Bank_Submunicipality_Type` TEXT,
  `Intermediary_Bank_Country_Region_Reference_ID` TEXT,
  `Intermediary_Bank_Country_Region_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Country_Region_Descriptor` TEXT,
  `Intermediary_Bank_Subregion_Data` TEXT,
  `Intermediary_Bank_Subregion_Descriptor` TEXT,
  `Intermediary_Bank_Subregion_Type` TEXT,
  `Intermediary_Bank_Postal_Code` TEXT,
  `Intermediary_Bank_Public` TEXT,
  `Intermediary_Bank_Address_Primary` TEXT,
  `Intermediary_Bank_Address_Type_Reference_ID` TEXT,
  `Intermediary_Bank_Address_Type_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Use_For_Reference_ID` TEXT,
  `Intermediary_Bank_Use_For_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Use_For_Tenanted_Reference_ID` TEXT,
  `Intermediary_Bank_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Comments` TEXT,
  `Intermediary_Bank_Number_of_Days` TEXT,
  `Intermediary_Bank_Municipality_Local` TEXT,
  `Intermediary_Bank_Address_Reference_ID` TEXT,
  `Intermediary_Bank_Address_Reference_ID_Type` TEXT,
  `Intermediary_Bank_Address_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_deduction_recipient`;
CREATE TABLE `src_put_payroll_deduction_recipient`(
  `Payroll_Deduction_Recipient_Reference_ID` TEXT,
  `Payroll_Deduction_Recipient_Reference_ID_Type` TEXT,
  `Payroll_Deduction_Recipient_Name` TEXT,
  `Payroll_Alternate_Deduction_Recipient_Name` TEXT,
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Payment_Type_Reference_ID` TEXT,
  `Payment_Type_Reference_ID_Type` TEXT,
  `Payroll_Deduction_Recipient_Snapshot_Effective_Date` TEXT,
  `DeductionRecipient_Country_Reference_ID` TEXT,
  `DeductionRecipient_Country_Reference_ID_Type` TEXT,
  `Deduction_Recipient_Snapshot_Inactive` TEXT,
  `Enable_Payroll_Third_Party_Payments` TEXT,
  `Payroll_Third_Party_Payment_Always_Separate_Payments` TEXT,
  `Payroll_Third_Party_Payment_Category_Reference_ID` TEXT,
  `Payroll_Third_Party_Payment_Category_Reference_ID_Type` TEXT,
  `Business_Entity_Name` TEXT,
  `Business_Entity_Phonetic_Name` TEXT,
  `Business_Entity_Tax_ID` TEXT,
  `External_Entity_ID` TEXT,
  `Business_Entity_Logo_Filename` TEXT,
  `Business_Entity_Logo_Image` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_deduction_recipient_contact`;
CREATE TABLE `src_put_payroll_deduction_recipient_contact`(
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Address_Data_Formatted_Address` TEXT,
  `Address_Data_Address_Format_Type` TEXT,
  `Address_Data_Defaulted_Business_Site_Address` TEXT,
  `Address_Data_Delete` TEXT,
  `Address_Data_Do_Not_Replace_All` TEXT,
  `Address_Data_Effective_Date` TEXT,
  `Address_Country_Reference_ID` TEXT,
  `Address_Country_Reference_ID_Type` TEXT,
  `Last_Modified` TEXT,
  `ADDRESS_LINE_1` TEXT,
  `ADDRESS_LINE_2` TEXT,
  `Address_Line_Data_Type` TEXT,
  `Address_Municipality` TEXT,
  `Address_Country_City_Reference_ID` TEXT,
  `Address_Country_City_Reference_ID_Type` TEXT,
  `Address_Country_City_Reference_ID_parent_id` TEXT,
  `Address_Country_City_Reference_ID_parent_type` TEXT,
  `Address_Submunicipality_Data` TEXT,
  `Address_Submunicipality_Data_Address_Component_Name` TEXT,
  `Address_Submunicipality_Data_Type` TEXT,
  `Address_Country_Region_Reference_ID` TEXT,
  `Address_Country_Region_Reference_ID_Type` TEXT,
  `Address_Subregion_Data` TEXT,
  `Address_Subregion_Data_Type` TEXT,
  `Address_Postal_Code` TEXT,
  `Address_Usage_Data_Public` TEXT,
  `Address_Type_Data_Primary` TEXT,
  `Address_Usage_Type_Reference_ID` TEXT,
  `Address_Usage_Type_Reference_ID_Type` TEXT,
  `Address_Use_For_Reference_ID` TEXT,
  `Address_Use_For_Reference_ID_Type` TEXT,
  `Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Address_Comments` TEXT,
  `Address_Number_of_Days` TEXT,
  `Address_Municipality_Local` TEXT,
  `Address_Address_Reference_ID` TEXT,
  `Address_Address_Reference_ID_Type` TEXT,
  `Address_Address_ID` TEXT,
  `Phone_Data_Area_Code` TEXT,
  `Phone_Data_Tenant_Formatted_Phone` TEXT,
  `Phone_Data_International_Formatted_Phone` TEXT,
  `Phone_Data_Phone_Number_Without_Area_Code` TEXT,
  `Phone_Data_National_Formatted_Phone` TEXT,
  `Phone_Data_E164_Formatted_Phone` TEXT,
  `Phone_Data_Workday_Traditional_Formatted_Phone` TEXT,
  `Phone_Data_Delete` TEXT,
  `Phone_Data_Do_Not_Replace_All` TEXT,
  `Phone_Data_Country_ISO_Code` TEXT,
  `Phone_Data_International_Phone_Code` TEXT,
  `Phone_Data_Phone_Number` TEXT,
  `Phone_Data_Phone_Extension` TEXT,
  `Phone_Data_Phone_Device_Type_Reference_ID` TEXT,
  `Phone_Data_Phone_Device_Type_Reference_ID_Type` TEXT,
  `Phone_Data_Usage_Data_Public` TEXT,
  `Phone_Data_Type_Data_Primary` TEXT,
  `Phone_Data_Usage_Type_Reference_ID` TEXT,
  `Phone_Data_Usage_Type_Reference_ID_Type` TEXT,
  `Phone_Data_Use_For_Reference_ID` TEXT,
  `Phone_Data_Use_For_Reference_ID_Type` TEXT,
  `Phone_Data_Use_For_Tenanted_Reference_ID` TEXT,
  `Phone_Data_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Phone_Data_Comments` TEXT,
  `Phone_Data_Phone_Reference_ID` TEXT,
  `Phone_Data_Phone_Reference_ID_Type` TEXT,
  `Phone_Data_ID` TEXT,
  `Email_Address_Data_Delete` TEXT,
  `Email_Address_Data_Do_Not_Replace_All` TEXT,
  `Email_Address` TEXT,
  `Email_Address_Email_Comment` TEXT,
  `Email_Address_Usage_Data_Public` TEXT,
  `Email_Address_Type_Data_Primary` TEXT,
  `Email_Address_Usage_Type_Reference_ID` TEXT,
  `Email_Address_Usage_Type_Reference_ID_Type` TEXT,
  `Email_Address_Use_For_Reference_ID` TEXT,
  `Email_Address_Use_For_Reference_ID_Type` TEXT,
  `Email_Address_Use_For_Tenanted_Reference_ID` TEXT,
  `Email_Address_Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Email_Address_Comments` TEXT,
  `Email_Address_Email_Reference_ID` TEXT,
  `Email_Address_Email_Reference_ID_Type` TEXT,
  `Email_Address_Data_ID` TEXT,
  `Instant_Messenger_Address` TEXT,
  `Instant_Messenger_Type_Reference_ID` TEXT,
  `Instant_Messenger_Type_Reference_ID_Type` TEXT,
  `Instant_Messenger_Comment` TEXT,
  `Instant_Messenger_Reference_ID` TEXT,
  `Instant_Messenger_Reference_ID_Type` TEXT,
  `Instant_Messenger_Data_ID` TEXT,
  `Web_Address` TEXT,
  `Web_Address_Comment` TEXT,
  `Web_Address_Reference_ID` TEXT,
  `Web_Address_Reference_ID_Type` TEXT,
  `Web_Address_Data_ID` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_deduction_recipient_settlement`;
CREATE TABLE `src_put_payroll_deduction_recipient_settlement`(
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Settlement_Account_Widget_Replace_All` TEXT,
  `Widget_Settlement_Account_Delete` TEXT,
  `Settlement_Bank_Account_ID` TEXT,
  `Widget_Settlement_Account_Country_Reference_ID` TEXT,
  `Widget_Settlement_Account_Country_Reference_ID_Type` TEXT,
  `Settlement_Account_Currency_Reference_ID` TEXT,
  `Settlement_Account_Currency_Reference_ID_Type` TEXT,
  `Settlement_Account_Bank_Account_Nickname` TEXT,
  `Settlement_Account_Bank_Account_Type_Reference_ID` TEXT,
  `Settlement_Account_Bank_Account_Type_Reference_ID_Type` TEXT,
  `Settlement_Account_Bank_Name` TEXT,
  `Settlement_Account_Routing_Transit_Number` TEXT,
  `Settlement_Account_Branch_ID` TEXT,
  `Settlement_Account_Branch_Name` TEXT,
  `Settlement_Account_Bank_Account_Number` TEXT,
  `Settlement_Account_Check_Digit` TEXT,
  `Settlement_Account_Bank_Account_Name` TEXT,
  `Settlement_Account_Roll_Number` TEXT,
  `Settlement_Account_IBAN` TEXT,
  `Settlement_Account_SWIFT_Bank_Identification_Code` TEXT,
  `Settlement_Accepts_Payment_Types_Reference_ID` TEXT,
  `Settlement_Accepts_Payment_Types_Reference_ID_Type` TEXT,
  `Settlement_Payment_Types_Reference_ID` TEXT,
  `Settlement_Payment_Types_Reference_ID_Type` TEXT,
  `Settlement_For_Supplier_Connections_Only` TEXT,
  `Settlement_Requires_Prenote` TEXT,
  `Settlement_Payment_Type_Prenote_Reference_ID` TEXT,
  `Settlement_Payment_Type_Prenote_Reference_ID_Type` TEXT,
  `Settlement_Account_Inactive` TEXT,
  `Settlement_Account_Bank_Instructions` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_deduction_recipient_third_party`;
CREATE TABLE `src_put_payroll_deduction_recipient_third_party`(
  `Payroll_Deduction_Recipient_ID` TEXT,
  `Benefit_Plan_Reference_ID` TEXT,
  `Benefit_Plan_Reference_ID_Type` TEXT,
  `Payroll_Worktag_Reference_ID` TEXT,
  `Payroll_Worktag_Reference_ID_Type` TEXT,
  `Payroll_Worktag_Reference_ID_Parent_ID` TEXT,
  `Payroll_Worktag_Reference_ID_Parent_Type` TEXT,
  `Comment` TEXT,
  `Deduction_Recipient_Snapshot_PAY_Third_Party_Pay_Conf_Delete` TEXT,
  `Deduction_Reference_ID` TEXT,
  `Deduction_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Payroll_Deduction_Recipient_DCDD Section ***/


/*** Start of Put_Payroll_History_Payment_DCDD Section created from https://app.smartsheet.com/sheets/GPgmvw6WfgGj5XFJFCcpPXgphH2F9vxC982vv3Q1?view=grid ***/

DROP TABLE IF EXISTS `src_put_payroll_history_payment`;
CREATE TABLE `src_put_payroll_history_payment`(
  `Payroll_History_Payment_Reference_ID` TEXT,
  `Payroll_History_Payment_Reference_ID_Type` TEXT,
  `Batch_ID` TEXT,
  `Payment_ID` TEXT,
  `Employee_Reference_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Period_Date` TEXT,
  `Run_Category_Reference_ID` TEXT,
  `Run_Category_Reference_ID_Type` TEXT,
  `Pay_Group_Reference_ID` TEXT,
  `Pay_Group_Reference_ID_Type` TEXT,
  `Payroll_ID_Reference_ID` TEXT,
  `Payroll_ID_Reference_ID_Type` TEXT,
  `Third_Party_Sick_Pay` TEXT,
  `Payment_Date` TEXT,
  `Gross_Amount` TEXT,
  `Net_Amount` TEXT,
  `Sub_Period_Start_Date` TEXT,
  `Sub_Period_End_Date` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT,
  `Result_Worktag_Overrides_Region_Reference_ID` TEXT,
  `Result_Worktag_Overrides_Region_Reference_ID_Type` TEXT,
  `Result_Worktag_Overrides_Location_Reference_ID` TEXT,
  `Result_Worktag_Overrides_Location_Reference_ID_Type` TEXT,
  `Result_Worktag_Overrides_Cost_Center_Reference_ID` TEXT,
  `Result_Worktag_Overrides_Cost_Center_Reference_ID_Type` TEXT,
  `Result_Worktag_Overrides_Job_Profile_Reference_ID` TEXT,
  `Result_Worktag_Overrides_Job_Profile_Reference_ID_Type` TEXT,
  `State_Work_Reference_ID` TEXT,
  `State_Work_Reference_ID_Type` TEXT,
  `SUI_Authority_Reference_ID` TEXT,
  `SUI_Authority_Reference_ID_Type` TEXT,
  `State_Resident_Reference_ID` TEXT,
  `State_Resident_Reference_ID_Type` TEXT,
  `County_Work_Reference_ID` TEXT,
  `County_Work_Reference_ID_Type` TEXT,
  `County_Resident_Reference_ID` TEXT,
  `County_Resident_Reference_ID_Type` TEXT,
  `City_Work_Reference_ID` TEXT,
  `City_Work_Reference_ID_Type` TEXT,
  `City_Resident_Reference_ID` TEXT,
  `City_Resident_Reference_ID_Type` TEXT,
  `School_District_Resident_Reference_ID` TEXT,
  `School_District_Resident_Reference_ID_Type` TEXT,
  `Other_Authority_Reference_ID` TEXT,
  `Other_Authority_Reference_ID_Type` TEXT,
  `Payroll_Reference_Number_Reference_ID` TEXT,
  `Payroll_Reference_Number_Reference_ID_Type` TEXT,
  `Add_to_Existing_Input_Data` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Amount` TEXT,
  `Taxable_Wages` TEXT,
  `Subject_Wages` TEXT,
  `Payroll_Input_Worktags_Location_Reference_ID` TEXT,
  `Payroll_Input_Worktags_Location_Reference_ID_Type` TEXT,
  `Payroll_Input_Worktags_Region_Reference_ID` TEXT,
  `Payroll_Input_Worktags_Region_Reference_ID_Type` TEXT,
  `Payroll_Input_Worktags_Job_Profile_Reference_ID` TEXT,
  `Payroll_Input_Worktags_Job_Profile_Reference_ID_Type` TEXT,
  `Payroll_Input_Worktags_Cost_Center_Reference_ID` TEXT,
  `Payroll_Input_Worktags_Cost_Center_Reference_ID_Type` TEXT,
  `Withholding_Order_Case_Reference_ID` TEXT,
  `Withholding_Order_Case_Reference_ID_Type` TEXT,
  `State_Authority_Reference_ID` TEXT,
  `State_Authority_Reference_ID_Type` TEXT,
  `Workers_Compensation_Code_Reference_ID` TEXT,
  `Workers_Compensation_Code_Reference_ID_Type` TEXT,
  `County_Authority_Reference_ID` TEXT,
  `County_Authority_Reference_ID_Type` TEXT,
  `City_Authority_Reference_ID` TEXT,
  `City_Authority_Reference_ID_Type` TEXT,
  `School_District_Authority_Reference_ID` TEXT,
  `School_District_Authority_Reference_ID_Type` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Object_Class_Reference_ID` TEXT,
  `Object_Class_Reference_ID_Type` TEXT,
  `Custom_Organization_Reference_ID` TEXT,
  `Custom_Organization_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID_Type` TEXT,
  `NI_Category_Reference_ID` TEXT,
  `NI_Category_Reference_ID_Type` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID_Type` TEXT,
  `Income_Code_Reference_ID` TEXT,
  `Income_Code_Reference_ID_Type` TEXT,
  `Exemption_Code_Reference_ID` TEXT,
  `Exemption_Code_Reference_ID_Type` TEXT,
  `Tax_Residency_Country_Reference_ID` TEXT,
  `Tax_Residency_Country_Reference_ID_Type` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Phase_Reference_ID` TEXT,
  `Project_Phase_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Comment` TEXT,
  `Related_Calculation_Reference_ID` TEXT,
  `Related_Calculation_Reference_ID_Type` TEXT,
  `Input_Value` TEXT,
  `Date_Input_Value` TEXT,
  `Boolean_Input_Value` TEXT,
  `Text_Input_Value` TEXT,
  `Costing_Company_Reference_ID` TEXT,
  `Costing_Company_Reference_ID_Type` TEXT,
  `Earning_Reference_ID` TEXT,
  `Earning_Reference_ID_Type` TEXT,
  `Deduction_Reference_ID` TEXT,
  `Deduction_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Payroll_History_Payment_DCDD Section ***/


/*** Start of Put_Payroll_Involuntary_Withholding_Order_DCDD Section created from https://app.smartsheet.com/sheets/GVHG2M2C4GgP3PWCR4ww5h96MHx3JRcCv593g3P1?view=grid ***/

DROP TABLE IF EXISTS `src_put_payroll_involuntary_withholding_order`;
CREATE TABLE `src_put_payroll_involuntary_withholding_order`(
  `Add_Only` TEXT,
  `Copied_Message` TEXT,
  `Copied_To` TEXT,
  `Copied_From` TEXT,
  `Processing_Message` TEXT,
  `Copied_From_Date` TEXT,
  `Copied_To_Date` TEXT,
  `Employee_Reference_ID` TEXT,
  `Employee_Reference_ID_Type` TEXT,
  `Withholding_Order_Type_Reference_ID` TEXT,
  `Withholding_Order_Type_Reference_ID_Type` TEXT,
  `Withholding_Order_Additional_Order_Number` TEXT,
  `Order_Date` TEXT,
  `Received_Date` TEXT,
  `Begin_Date` TEXT,
  `End_Date` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT,
  `Inactive_Order` TEXT,
  `Order_Status` TEXT,
  `Withholding_Order_Amount_Type_Reference_ID` TEXT,
  `Withholding_Order_Amount_Type_Reference_ID_Type` TEXT,
  `Pay_Period_Frequency_Reference_ID` TEXT,
  `Pay_Period_Frequency_Reference_ID_Type` TEXT,
  `Total_Debt_Amount` TEXT,
  `Monthly_Limit` TEXT,
  `Issued_in_Reference_ID` TEXT,
  `Issued_in_Reference_ID_Type` TEXT,
  `Payroll_Involuntary_Withholding_Order_Deduction_Recipient_Ref_ID` TEXT,
  `Payroll_Involuntary_Withholding_Deduction_Recipient_Ref_ID_Type` TEXT,
  `Originating_Authority` TEXT,
  `Memo` TEXT,
  `Department_of_Education_Student_Loan` TEXT,
  `Withholding_Order_Withholding_Frequency_Reference_ID` TEXT,
  `Withholding_Order_Withholding_Frequency_Reference_ID_Type` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Withholding_Order_ID` TEXT,
  `Withholding_Order_Case_Reference_ID` TEXT,
  `Withholding_Order_Case_Reference_ID_Type` TEXT,
  `Case_Number` TEXT,
  `Withholding_Order_Amount` TEXT,
  `Withholding_Order_Amount_as_Percent` TEXT,
  `Payroll_Involuntary_Withholding_Order_Reference_ID` TEXT,
  `Payroll_Involuntary_Withholding_Order_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_involuntary_withholding_order_contact`;
CREATE TABLE `src_put_payroll_involuntary_withholding_order_contact`(
  `Employee_Reference_ID` TEXT,
  `Formatted_Address` TEXT,
  `Address_Format_Type` TEXT,
  `Defaulted_Business_Site_Address` TEXT,
  `Delete` TEXT,
  `Do_Not_Replace_All` TEXT,
  `Effective_Date` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Last_Modified` TEXT,
  `Address_Line_1` TEXT,
  `Address_Line_2` TEXT,
  `Address_Line_3` TEXT,
  `Address_Line_Data_Descriptor` TEXT,
  `Address_Line_Type` TEXT,
  `Municipality` TEXT,
  `Country_City_Reference_ID` TEXT,
  `Country_City_Reference_ID_Type` TEXT,
  `Country_City_Reference_ID_Parent_ID` TEXT,
  `Country_City_Reference_ID_Parent_Type` TEXT,
  `Submunicipality_Data` TEXT,
  `Address_Component_Name` TEXT,
  `Submunicipality_Type` TEXT,
  `Country_Region_Reference_ID` TEXT,
  `Country_Region_Reference_ID_Type` TEXT,
  `Country_Region_Descriptor` TEXT,
  `Subregion_Data` TEXT,
  `Subregion_Data_Descriptor` TEXT,
  `Subregion_Type` TEXT,
  `Postal_Code` TEXT,
  `Public` TEXT,
  `Primary` TEXT,
  `Type_Reference_ID` TEXT,
  `Type_Reference_ID_Type` TEXT,
  `Use_For_Reference_ID` TEXT,
  `Use_For_Reference_ID_Type` TEXT,
  `Use_For_Tenanted_Reference_ID` TEXT,
  `Use_For_Tenanted_Reference_ID_Type` TEXT,
  `Comments` TEXT,
  `Number_of_Days` TEXT,
  `Municipality_Local` TEXT,
  `Address_Reference_ID` TEXT,
  `Address_Reference_ID_Type` TEXT,
  `Address_ID` TEXT,
  `Case_Number` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_payroll_involuntary_withholding_order_details`;
CREATE TABLE `src_put_payroll_involuntary_withholding_order_details`(
  `Employee_Reference_ID` TEXT,
  `Withholding_Order_Fee_Reference_ID` TEXT,
  `Withholding_Order_Fee_Reference_ID_Type` TEXT,
  `Fee_Type_Reference_ID` TEXT,
  `Fee_Type_Reference_ID_Type` TEXT,
  `Withholding_Order_Fee_Amount_Type_Reference_ID` TEXT,
  `Withholding_Order_Fee_Amount_Type_Reference_ID_Type` TEXT,
  `Fee_Amount` TEXT,
  `Fee_Percent` TEXT,
  `US_Withholding_Order_Fee_Data_Deduction_Recipient_Reference_ID` TEXT,
  `US_Withholding_Order_Fee_Data_Deduction_Recipient_Ref_ID_Type` TEXT,
  `Override_Fee_Schedule` TEXT,
  `Fee_Begin_Date` TEXT,
  `Fee_End_Date` TEXT,
  `Fee_Monthly_Limit` TEXT,
  `Case_Number` TEXT,
  `Chapter_13` TEXT,
  `Chapter_7` TEXT,
  `Creditor_Garnishment_Type_Reference_ID` TEXT,
  `Creditor_Garnishment_Type_Reference_ID_Type` TEXT,
  `Non_Resident_State_Reference_ID` TEXT,
  `Non_Resident_State_Reference_ID_Type` TEXT,
  `Creditor_Garnishment_Data_Head_of_Household` TEXT,
  `Creditor_Garnishment_Data_Number_of_Dependents` TEXT,
  `Creditor_Garnishment_Payroll_Local_County_Authority_FIPS_Code` TEXT,
  `Creditor_Garnishment_Data_Worker_is_Laborer_or_Mechanic` TEXT,
  `Creditor_Garnishment_Data_Worker_Income_is_Poverty_Level` TEXT,
  `Creditor_Garnishment_Data_Good_Cause_Limit_Percent` TEXT,
  `Weekly_Gross_Wages` TEXT,
  `Expected_Annual_Earnings` TEXT,
  `Tax_Levy_Signed_Part_3_Date` TEXT,
  `Payroll_Marital_Status_Reference` TEXT,
  `Federal_Tax_Levy_Data_Personal_Exemptions` TEXT,
  `Additional_Exemptions_65_or_Blind` TEXT,
  `Exemption_Amount_Override` TEXT,
  `Exemption_Frequency_Reference_ID` TEXT,
  `Exemption_Frequency_Reference_ID_Type` TEXT,
  `Tax_Levy_Termination_Date` TEXT,
  `Federal_Tax_Levy_Dependent_Reference_Dependent_Name` TEXT,
  `Federal_Tax_Levy_Dependent_Ref_Dependent_Identification_Number` TEXT,
  `Lock_Tax_Elections` TEXT,
  `Load_Baseline_Restrictions` TEXT,
  `Form_and_Revision_Number_Reference_ID` TEXT,
  `Form_and_Revision_Number_Reference_ID_Type` TEXT,
  `Payroll_Marital_Status_Reference_ID` TEXT,
  `Payroll_Marital_Status_Reference_ID_Type` TEXT,
  `State_Tax_Levy_Order_Data_Number_of_Dependents` TEXT,
  `State_Tax_Levy_Order_Payroll_Local_County_Authority_FIPS_Code` TEXT,
  `State_Tax_Levy_Order_Data_Worker_is_Laborer_or_Mechanic` TEXT,
  `State_Tax_Levy_Order_Data_Worker_Income_is_Poverty_Level` TEXT,
  `Part_3_Effective_Date` TEXT,
  `Pay_Period_Exemption_Override_Amount` TEXT,
  `State_Tax_Levy_Federal_Data_Personal_Exemptions` TEXT,
  `Additional_65_or_Blind_Exemptions` TEXT,
  `Termination_Date` TEXT,
  `State_Tax_Levy_Dependant_Reference_Dependent_Name` TEXT,
  `State_Tax_Levy_Dependant_Ref_Dependent_Identification_Number` TEXT,
  `State_Tax_Levy_Order_Data_Good_Cause_Limit_Percent` TEXT,
  `Process_Until_Reference_ID` TEXT,
  `Process_Until_Reference_ID_Type` TEXT,
  `Prorate_Until_Date` TEXT,
  `Support_Order_Data_Custodial_Party_Name` TEXT,
  `Support_Order_Data_Supports_Second_Family` TEXT,
  `Support_Order_Data_Remittance_ID_Override` TEXT,
  `Support_Order_Dependant_Reference_Child_s_Name_Last_First_MI` TEXT,
  `Support_Order_Dependant_Reference_Child_s_Birth_Date` TEXT,
  `Support_Order_Details_Reference_Order_Form_Amount` TEXT,
  `Support_Order_Details_Reference_Support_Type_Reference_ID` TEXT,
  `Support_Order_Details_Reference_Support_Type_Reference_ID_Type` TEXT,
  `Support_Order_Details_Reference_Arrears_Over_12_Weeks` TEXT,
  `Support_Order_Details_Reference_Pay_Period_Amount_Override` TEXT,
  `Support_Order_Details_Reference_Amount_as_Percent` TEXT,
  `Support_Order_Payroll_Local_County_Authority_FIPS_Code` TEXT,
  `Original_Order` TEXT,
  `Amended_Order` TEXT,
  `Termination_Order` TEXT,
  `Process_in_Regular_Period` TEXT,
  `Payroll_Support_Order_Lump_Sum_Data_Custodial_Party_Name` TEXT,
  `Payroll_Support_Order_Lump_Sum_Data_Remittance_ID_Override` TEXT,
  `Payroll_Support_Order_Lump_Sum_Data_Supports_Second_Family` TEXT,
  `Payroll_Local_County_Authority_Reference_ID` TEXT,
  `Payroll_Local_County_Authority_Reference_ID_Type` TEXT,
  `Dependants_Reference_Child_s_Name_Last_First_MI` TEXT,
  `Dependants_Reference_Child_s_Birth_Date` TEXT,
  `Support_Order_Detail_Reference_Order_Form_Amount` TEXT,
  `Support_Order_Detail_Reference_Support_Type_Reference_ID` TEXT,
  `Support_Order_Detail_Reference_Support_Type_Reference_ID_Type` TEXT,
  `Support_Order_Detail_Reference_Arrears_Over_12_Weeks` TEXT,
  `Support_Order_Detail_Reference_Pay_Period_Amount_Override` TEXT,
  `Support_Order_Detail_Reference_Amount_as_Percent` TEXT,
  `Payroll_Support_Order_L_Payroll_Local_County_Authority_FIPS_Code` TEXT,
  `Regulated_Loan` TEXT,
  `Wage_Assignment_Data_Head_of_Household` TEXT,
  `Married` TEXT,
  `Support_Order_Reference_ID` TEXT,
  `Support_Order_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Payroll_Involuntary_Withholding_Order_DCDD Section ***/


/*** Start of Put_Period_Schedule_DCDD Section created from https://app.smartsheet.com/sheets/xrH2J2v58M4GJXfw7HgwGmWCQmqvcfg9pp8jwpX1?view=grid ***/

DROP TABLE IF EXISTS `src_put_period_schedule`;
CREATE TABLE `src_put_period_schedule`(
  `Add_Only` TEXT,
  `Period_Schedule_Reference_ID` TEXT,
  `Period_Schedule_Reference_ID_Type` TEXT,
  `Period_Schedule_ID` TEXT,
  `Period_Schedule_Name` TEXT,
  `Frequency_Reference_ID` TEXT,
  `Frequency_Reference_ID_Type` TEXT,
  `Regular_Pay_Day_Reference_ID` TEXT,
  `Regular_Pay_Day_Reference_ID_Type` TEXT,
  `Payment_Date_Auto_Adjust_Saturday` TEXT,
  `Payment_Date_Auto_Adjust_Sunday` TEXT,
  `Payment_Date_Offset_Days_Default` TEXT,
  `Pay_On_Demand_Payment_Date_Default_Offset` TEXT,
  `Pay_On_Demand_Payment_Date_Auto_Adjust_Saturday` TEXT,
  `Pay_On_Demand_Payment_Date_Auto_Adjust_Sunday` TEXT,
  `Pay_On_Demand_Days_After_Period_Start_Date_to_Open_Requests` TEXT,
  `Pay_On_Demand_Days_From_Period_End_Date_to_Close_Requests` TEXT,
  `Allow_Timesheet_Changes` TEXT,
  `Payroll_Period_Schedule_Reference_ID` TEXT,
  `Payroll_Period_Schedule_Reference_ID_Type` TEXT,
  `Enable_Auto_Calc_Period` TEXT,
  `Default_Number_of_Days_After_Period_Start_Date_for_Auto_Calc` TEXT,
  `Default_Time_to_Process_Reference_ID` TEXT,
  `Default_Time_to_Process_Reference_ID_Type` TEXT,
  `Time_Zone_Reference_ID` TEXT,
  `Time_Zone_Reference_ID_Type` TEXT,
  `Enable_Automatic_Stop_Period` TEXT,
  `Default_Number_of_Days_Before_Period_Payment_Date_for_Auto_Stop` TEXT,
  `Default_Time_for_Auto_Stop_Reference_ID` TEXT,
  `Default_Time_for_Auto_Stop_Reference_ID_Type` TEXT,
  `Time_Zone_for_Auto_Stop_Reference_ID` TEXT,
  `Time_Zone_for_Auto_Stop_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_period_schedule_details`;
CREATE TABLE `src_put_period_schedule_details`(
  `Period_Schedule_ID` TEXT,
  `Usage_Reference_ID` TEXT,
  `Usage_Reference_ID_Type` TEXT,
  `Time_Tracking_Eligibility_Rule_Reference_ID` TEXT,
  `Time_Tracking_Eligibility_Rule_Reference_ID_Type` TEXT,
  `Period_Start_Date` TEXT,
  `Period_End_Date` TEXT,
  `Payroll_Payment_Date` TEXT,
  `Accounting_Date_Override` TEXT,
  `Payroll_GL_Accruals` TEXT,
  `Days_to_Accrue` TEXT,
  `Days_in_Basis` TEXT,
  `Accrual_Date` TEXT,
  `Accrual_Reversal_Date` TEXT,
  `Open_Time_Entry` TEXT,
  `Lock_Time_Entry` TEXT,
  `Unlock_for_Adjustments` TEXT,
  `Close_Time_Entry` TEXT,
  `Payroll_Period_Reference_ID` TEXT,
  `Payroll_Period_Reference_ID_Type` TEXT,
  `Pay_On_Demand_Open_Requests` TEXT,
  `Pay_On_Demand_Close_Requests` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Payroll_Settlement_Valuation_Date` TEXT,
  `Period_ID` TEXT,
  `Auto_Calc_Date` TEXT,
  `Auto_Calc_Time_Reference_ID` TEXT,
  `Auto_Calc_Time_Reference_ID_Type` TEXT,
  `Automatic_Stop_Date` TEXT,
  `Automatic_Stop_Time_Reference_ID` TEXT,
  `Automatic_Stop_Time_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Period_Schedule_DCDD Section ***/


/*** Start of Put_Run_Category_DCDD Section created from https://app.smartsheet.com/sheets/P5Wr5Rc8mPxf99X7x6WWxrgcH44Rr45267H5rw81?view=grid ***/

DROP TABLE IF EXISTS `src_put_run_category`;
CREATE TABLE `src_put_run_category`(
  `Add_Only` TEXT,
  `Run_Category_Reference_ID` TEXT,
  `Run_Category_Reference_ID_Type` TEXT,
  `Run_Category_ID` TEXT,
  `Run_Category_Name` TEXT,
  `Regular_Run_Category` TEXT,
  `Non_Regular_Taxation` TEXT,
  `Use_State_Supplemental_Flat_Tax_Rate` TEXT,
  `Aggregate_Federal_Withholding_Wages` TEXT,
  `Used_in_Payroll_Interface` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_run_category_details`;
CREATE TABLE `src_put_run_category_details`(
  `Run_Category_ID` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Gross_Pay_Accumulation_Reference_ID` TEXT,
  `Gross_Pay_Accumulation_Reference_ID_Type` TEXT,
  `Net_Pay_Accumulation_Reference_ID` TEXT,
  `Net_Pay_Accumulation_Reference_ID_Type` TEXT,
  `Minimum_Net` TEXT,
  `Additional_Pay_Component_Reference_ID` TEXT,
  `Additional_Pay_Component_Reference_ID_Type` TEXT,
  `Additional_Pay_Component_Group_Reference_ID` TEXT,
  `Additional_Pay_Component_Group_Reference_ID_Type` TEXT,
  `Payroll_Processing_Status_Reference_ID` TEXT,
  `Payroll_Processing_Status_Reference_ID_Type` TEXT,
  `Eligibility_Calculation_Reference_ID` TEXT,
  `Eligibility_Calculation_Reference_ID_Type` TEXT,
  `Cycle_and_On_Demand_Replacement_Pay_Component_Reference_ID` TEXT,
  `Cycle_and_On_Demand_Replacement_Pay_Component_Reference_ID_Type` TEXT,
  `Cycle_and_On_Demand_Replacement_Pay_Cmpnt_Group_RefID_Pay_Cmpnt` TEXT,
  `Cycle_and_On_Demand_Replacement_Pay_Cmpnt_Group_RefID_Type_Pay` TEXT,
  `On_cycle_Non_active_Payroll_Processing_Status_Reference_ID` TEXT,
  `On_cycle_Non_active_Payroll_Processing_Status_Reference_ID_Type` TEXT,
  `On_cycle_Non_active_Leave_Type_Reference_ID` TEXT,
  `On_cycle_Non_active_Leave_Type_Reference_ID_Type` TEXT,
  `On_cycle_Non_active_Calculation_Reference_ID` TEXT,
  `On_cycle_Non_active_Calculation_Reference_ID_Type` TEXT,
  `Off_Cycle_On_Demand_Additional_and_Manual_Pay_Pay_Cmpnt_RefID_P` TEXT,
  `Off_Cycle_On_Demand_Additional_and_Manual_Pay_Pay_Cmpnt_RefID_T` TEXT,
  `Off_Cycle_On_Demand_Pay_Component_Group_Reference_ID` TEXT,
  `Off_Cycle_On_Demand_Pay_Component_Group_Reference_ID_Type` TEXT,
  `Payroll_Off_cycle_Type_Reference_ID` TEXT,
  `Payroll_Off_cycle_Type_Reference_ID_Type` TEXT,
  `Payroll_Action_Reason_Reference_ID` TEXT,
  `Payroll_Action_Reason_Reference_ID_Type` TEXT,
  `Off_cycle_Process_Detail_PAY_Calc_PAY_Processing_Status_RefID_P` TEXT,
  `Off_cycle_Process_Detail_PAY_Calc_PAY_Processing_Status_RefID_T` TEXT,
  `Off_cycle_Process_Leave_Type_Reference_ID` TEXT,
  `Off_cycle_Process_Leave_Type_Reference_ID_Type` TEXT,
  `Off_cycle_Process_Calculation_Reference_ID` TEXT,
  `Off_cycle_Process_Calculation_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Run_Category_DCDD Section ***/


/*** Start of Submit_Payment_Election_Enrollment_DCDD Section created from https://app.smartsheet.com/sheets/Jm6c6Mf39MX8xXrpXHF9V8wGh3cQV53Wv7Pjpqx1?view=grid ***/

DROP TABLE IF EXISTS `src_submit_payment_election_enrollment`;
CREATE TABLE `src_submit_payment_election_enrollment`(
  `Retain_Unused_Worker_Bank_Accounts` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Worker_Country_Reference_ID` TEXT,
  `Worker_Country_Reference_ID_Type` TEXT,
  `Worker_Currency_Reference_ID` TEXT,
  `Worker_Currency_Reference_ID_Type` TEXT,
  `Payment_Election_Higher_Order_Rule_ID` TEXT,
  `Payment_Election_Higher_Order_Rule_ID_Type` TEXT,
  `Election_Order` TEXT,
  `Payment_Election_Rule_ID` TEXT,
  `Payment_Election_Rule_ID_Type` TEXT,
  `Payment_Election_Rule_Country` TEXT,
  `Payment_Election_Rule_Country_Type` TEXT,
  `Payment_Election_Rule_Currency_ID` TEXT,
  `Payment_Election_Rule_Currency_ID_Type` TEXT,
  `Payment_Type_Reference_ID` TEXT,
  `Payment_Type_Reference_ID_Type` TEXT,
  `Bank_Account_Country_Reference_ID` TEXT,
  `Bank_Account_Country_Reference_ID_Type` TEXT,
  `Bank_Account_Currency_Reference_ID` TEXT,
  `Bank_Account_Currency_Reference_ID_Type` TEXT,
  `Bank_Account_Nickname` TEXT,
  `Bank_Account_Name` TEXT,
  `Bank_Account_Number` TEXT,
  `Roll_Number` TEXT,
  `Bank_Account_Type_Code` TEXT,
  `Bank_Account_Type_Reference_ID` TEXT,
  `Bank_Account_Type_Reference_ID_Type` TEXT,
  `Bank_Name` TEXT,
  `Bank_Account_IBAN` TEXT,
  `Bank_Account_ID_Number` TEXT,
  `Bank_Account_BIC` TEXT,
  `Bank_Account_Branch_Name` TEXT,
  `Bank_Account_Branch_ID_Number` TEXT,
  `Bank_Account_Check_Digit` TEXT,
  `Distribution_Amount` TEXT,
  `Distribution_Percentage` TEXT,
  `Distribution_Balance` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Submit_Payment_Election_Enrollment_DCDD Section ***/


/*** Start of Submit_Payroll_Input_DCDD Section created from https://app.smartsheet.com/sheets/gqgrF8gVrPH5x4x5xcGxj7qJw6wqmpPH8C9r38W1?view=grid ***/

DROP TABLE IF EXISTS `src_submit_payroll_input`;
CREATE TABLE `src_submit_payroll_input`(
  `Last_Period_End_Date` TEXT,
  `Payroll_Input_ID` TEXT,
  `Batch_ID` TEXT,
  `Source_Reference_ID` TEXT,
  `Source_Reference_ID_Type` TEXT,
  `Ongoing_Input` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT,
  `Run_Category_Reference_ID` TEXT,
  `Run_Category_Reference_ID_Type` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Amount` TEXT,
  `Hours` TEXT,
  `Rate` TEXT,
  `Adjustment` TEXT,
  `Location_Reference_ID` TEXT,
  `Location_Reference_ID_Type` TEXT,
  `Region_Reference_ID` TEXT,
  `Region_Reference_ID_Type` TEXT,
  `Job_Profile_Reference_ID` TEXT,
  `Job_Profile_Reference_ID_Type` TEXT,
  `Cost_Center_Reference_ID` TEXT,
  `Cost_Center_Reference_ID_Type` TEXT,
  `Withholding_Order_Case_Reference_ID` TEXT,
  `Withholding_Order_Case_Reference_ID_Type` TEXT,
  `State_Authority_Reference_ID` TEXT,
  `State_Authority_Reference_ID_Type` TEXT,
  `Workers_Compensation_Code_Reference_ID` TEXT,
  `Workers_Compensation_Code_Reference_ID_Type` TEXT,
  `County_Authority_Reference_ID` TEXT,
  `County_Authority_Reference_ID_Type` TEXT,
  `City_Authority_Reference_ID` TEXT,
  `City_Authority_Reference_ID_Type` TEXT,
  `School_District_Authority_Reference_ID` TEXT,
  `School_District_Authority_Reference_ID_Type` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID` TEXT,
  `Flexible_Payment_Deduction_ID_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Object_Class_Reference_ID` TEXT,
  `Object_Class_Reference_ID_Type` TEXT,
  `Custom_Organization_Reference_ID` TEXT,
  `Custom_Organization_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID` TEXT,
  `Local_Other_Tax_Authorities_Reference_ID_Type` TEXT,
  `NI_Category_Reference_ID` TEXT,
  `NI_Category_Reference_ID_Type` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID` TEXT,
  `ARRCO_AGIRC_Category_Reference_ID_Type` TEXT,
  `Income_Code_Reference_ID` TEXT,
  `Income_Code_Reference_ID_Type` TEXT,
  `Exemption_Code_Reference_ID` TEXT,
  `Exemption_Code_Reference_ID_Type` TEXT,
  `Tax_Residency_Country_Reference_ID` TEXT,
  `Tax_Residency_Country_Reference_ID_Type` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Phase_Reference_ID` TEXT,
  `Project_Phase_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Related_Calculation_Reference_ID` TEXT,
  `Related_Calculation_Reference_ID_Type` TEXT,
  `Input_Value` TEXT,
  `Date_Input_Value` TEXT,
  `Boolean_Input_Value` TEXT,
  `Text_Input_Value` TEXT,
  `Comment` TEXT,
  `Currency_Reference_ID` TEXT,
  `Currency_Reference_ID_Type` TEXT,
  `Match_Existing_Input` TEXT,
  `Company_Reference_ID` TEXT,
  `Company_Reference_ID_Type` TEXT,
  `Costing_Company_Reference_ID` TEXT,
  `Costing_Company_Reference_ID_Type` TEXT,
  `Prior_Period_Tax_Adjustment` TEXT,
  `Coverage_Start_Date` TEXT,
  `Coverage_End_Date` TEXT,
  `Earning_Reference_ID` TEXT,
  `Earning_Reference_ID_Type` TEXT,
  `Deduction_Reference_ID` TEXT,
  `Deduction_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Submit_Payroll_Input_DCDD Section ***/


/* NO LONGER SETTING UP AS AN SP
SET autocommit=1;
END STAGING;
*/