/*
    Staging Table: absence
    Version: AutoCreated
    Comments: DDL created from https://app.smartsheet.com/sheets/FHw3c6hXHpQM2XhHrcFJmMpxJC3r8Cc4JPpvv3r1?view=grid
*/

/* NO LONGER SETTING UP AS AN SP
USE hellboy;     
DROP PROCEDURE IF EXISTS `sp_slng_ddl_absence`;
-- DELIMITER $$   -- *** Comment out the delimiter declaration to load via SLNG *** -- 
CREATE DEFINER=`slng_user`@`%` PROCEDURE `sp_slng_ddl_absence`()
  STAGING:BEGIN
*/

/*** Start of AddUpdate_Employee_Leave_Of_Absence_DCDD Section created from https://app.smartsheet.com/sheets/vPQhwXPV4cgFqrGwCPGjFcQqHvqR2Qw8vHGHrvw1?view=grid ***/

DROP TABLE IF EXISTS `src_addupdate_employee_leave_of_absence`;
CREATE TABLE `src_addupdate_employee_leave_of_absence`(
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Request_Leave_of_Absence_ID` TEXT,
  `Correction` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID_Type` TEXT,
  `Leave_Type_Reason_Reference_ID` TEXT,
  `Leave_Type_Reason_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Last_Day_of_Work` TEXT,
  `First_Day_of_Leave` TEXT,
  `Estimated_Last_Day_of_Leave` TEXT,
  `Links_Back_to_Prior_Event_Reference_ID` TEXT,
  `Links_Back_to_Prior_Event_Reference_ID_Type` TEXT,
  `Last_Date_for_Which_Paid` TEXT,
  `Expected_Due_Date` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Child_s_Birth_Date` TEXT,
  `Stillbirth_Baby_Deceased` TEXT,
  `Date_Baby_Arrived_Home_From_Hospital` TEXT,
  `Adoption_Placement_Date` TEXT,
  `Adoption_Notification_Date` TEXT,
  `Date_Child_Entered_Country` TEXT,
  `Multiple_Child_Indicator` TEXT,
  `Number_of_Babies_Adopted_Children` TEXT,
  `Number_of_Previous_Births` TEXT,
  `Number_of_Previous_Maternity_Leaves` TEXT,
  `Number_of_Child_Dependents` TEXT,
  `Single_Parent_Indicator` TEXT,
  `Age_of_Dependent` TEXT,
  `Work_Related` TEXT,
  `Stop_Payment_Date` TEXT,
  `Social_Security_Disability_Code` TEXT,
  `Location_During_Leave` TEXT,
  `Caesarean_Section_Birth` TEXT,
  `Leave_Percentage` TEXT,
  `Week_of_Confinement` TEXT,
  `Leave_Entitlement_Override` TEXT,
  `Date_of_Recall` TEXT,
  `Child_s_Date_of_Death` TEXT,
  `First_Day_Back_at_Work` TEXT,
  `Actual_Last_Day_of_Leave` TEXT,
  `Comment` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of AddUpdate_Employee_Leave_Of_Absence_DCDD Section ***/


/*** Start of Adjust_Time_Off_DCDD Section created from https://app.smartsheet.com/sheets/VvWQm9fRwf4jXg25MGQgGmMWP64rmXM7QFwPcwv1?view=grid ***/

DROP TABLE IF EXISTS `src_adjust_time_off`;
CREATE TABLE `src_adjust_time_off`(
  `Run_Time_Off_Validations` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Time_Off_Entry_ID` TEXT,
  `Time_Off_Entry_Reference_ID` TEXT,
  `Time_Off_Entry_Reference_ID_Type` TEXT,
  `Adjustment_to_Requested` TEXT,
  `Comment` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Adjust_Time_Off_DCDD Section ***/


/*** Start of Enter_Time_Off_DCDD Section created from https://app.smartsheet.com/sheets/5Vr4Gwwv4V6qvgVpQ65PfGPG7896xPPh3HF3WMQ1?view=grid ***/

DROP TABLE IF EXISTS `src_enter_time_off`;
CREATE TABLE `src_enter_time_off`(
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Time_Off_Entry_ID` TEXT,
  `Time_Off_Date` TEXT,
  `Start_Time` TEXT,
  `End_Time` TEXT,
  `Requested_Units` TEXT,
  `Time_Off_Type_Reference_ID` TEXT,
  `Time_Off_Type_Reference_ID_Type` TEXT,
  `Time_Off_Reference_ID` TEXT,
  `Time_Off_Reference_ID_Type` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Cost_Center_Reference_ID` TEXT,
  `Cost_Center_Reference_ID_Type` TEXT,
  `Custom_Organization_01_Reference_ID` TEXT,
  `Custom_Organization_01_Reference_ID_Type` TEXT,
  `Custom_Organization_02_Reference_ID` TEXT,
  `Custom_Organization_02_Reference_ID_Type` TEXT,
  `Custom_Organization_03_Reference_ID` TEXT,
  `Custom_Organization_03_Reference_ID_Type` TEXT,
  `Custom_Organization_04_Reference_ID` TEXT,
  `Custom_Organization_04_Reference_ID_Type` TEXT,
  `Custom_Organization_05_Reference_ID` TEXT,
  `Custom_Organization_05_Reference_ID_Type` TEXT,
  `Custom_Organization_06_Reference_ID` TEXT,
  `Custom_Organization_06_Reference_ID_Type` TEXT,
  `Custom_Organization_07_Reference_ID` TEXT,
  `Custom_Organization_07_Reference_ID_Type` TEXT,
  `Custom_Organization_08_Reference_ID` TEXT,
  `Custom_Organization_08_Reference_ID_Type` TEXT,
  `Custom_Organization_09_Reference_ID` TEXT,
  `Custom_Organization_09_Reference_ID_Type` TEXT,
  `Custom_Organization_10_Reference_ID` TEXT,
  `Custom_Organization_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Job_Profile_Reference_ID` TEXT,
  `Job_Profile_Reference_ID_Type` TEXT,
  `Location_Reference_ID` TEXT,
  `Location_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Region_Reference_ID` TEXT,
  `Region_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Absence_Table_Reference_ID` TEXT,
  `Absence_Table_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Time_Off_Reason_Reference_ID` TEXT,
  `Time_Off_Reason_Reference_ID_Type` TEXT,
  `Time_Off_Comment` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Enter_Time_Off_DCDD Section ***/


/*** Start of Import_Time_Off_Request_Event_Batch_DCDD Section created from https://app.smartsheet.com/sheets/v7Xp8QCh9wV3v2GHpvgvGprfqG495mQw7382MFJ1?view=grid ***/

DROP TABLE IF EXISTS `src_import_time_off_request_event_batch`;
CREATE TABLE `src_import_time_off_request_event_batch`(
  `Turn_Off_Run_Time_Calculations_with_Time_Off_Approval` TEXT,
  `Run_Time_Off_Validations` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Time_Off_Entry_ID` TEXT,
  `Date` TEXT,
  `Start_Time` TEXT,
  `End_Time` TEXT,
  `Requested` TEXT,
  `Time_Off_Type_Reference_ID` TEXT,
  `Time_Off_Type_Reference_ID_Type` TEXT,
  `Time_Off_Reference_ID` TEXT,
  `Time_Off_Reference_ID_Type` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Cost_Center_Reference_ID` TEXT,
  `Cost_Center_Reference_ID_Type` TEXT,
  `Custom_Organization_01_Reference_ID` TEXT,
  `Custom_Organization_01_Reference_ID_Type` TEXT,
  `Custom_Organization_02_Reference_ID` TEXT,
  `Custom_Organization_02_Reference_ID_Type` TEXT,
  `Custom_Organization_03_Reference_ID` TEXT,
  `Custom_Organization_03_Reference_ID_Type` TEXT,
  `Custom_Organization_04_Reference_ID` TEXT,
  `Custom_Organization_04_Reference_ID_Type` TEXT,
  `Custom_Organization_05_Reference_ID` TEXT,
  `Custom_Organization_05_Reference_ID_Type` TEXT,
  `Custom_Organization_06_Reference_ID` TEXT,
  `Custom_Organization_06_Reference_ID_Type` TEXT,
  `Custom_Organization_07_Reference_ID` TEXT,
  `Custom_Organization_07_Reference_ID_Type` TEXT,
  `Custom_Organization_08_Reference_ID` TEXT,
  `Custom_Organization_08_Reference_ID_Type` TEXT,
  `Custom_Organization_09_Reference_ID` TEXT,
  `Custom_Organization_09_Reference_ID_Type` TEXT,
  `Custom_Organization_10_Reference_ID` TEXT,
  `Custom_Organization_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Job_Profile_Reference_ID` TEXT,
  `Job_Profile_Reference_ID_Type` TEXT,
  `Location_Reference_ID` TEXT,
  `Location_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Region_Reference_ID` TEXT,
  `Region_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Absence_Table_Reference_ID` TEXT,
  `Absence_Table_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Time_Off_Reason_Reference_ID` TEXT,
  `Time_Off_Reason_Reference_ID_Type` TEXT,
  `Comment` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Import_Time_Off_Request_Event_Batch_DCDD Section ***/


/*** Start of Put_Absence_Input_DCDD Section created from https://app.smartsheet.com/sheets/w96wMGMMHMJfVQ437xWQwPMQg79MW9X6mmgvwXQ1?view=grid ***/

DROP TABLE IF EXISTS `src_put_absence_input`;
CREATE TABLE `src_put_absence_input`(
  `Absence_Input_Reference_ID` TEXT,
  `Absence_Input_Reference_ID_Type` TEXT,
  `Absence_Input_ID` TEXT,
  `Batch_ID` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Absence_Component_Reference_ID` TEXT,
  `Absence_Component_Reference_ID_Type` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT,
  `Reference_Date` TEXT,
  `Hours` TEXT,
  `Adjustment` TEXT,
  `Allocation_Pool_Reference_ID` TEXT,
  `Allocation_Pool_Reference_ID_Type` TEXT,
  `Appropriation_Reference_ID` TEXT,
  `Appropriation_Reference_ID_Type` TEXT,
  `Business_Unit_Reference_ID` TEXT,
  `Business_Unit_Reference_ID_Type` TEXT,
  `Cost_Center_Reference_ID` TEXT,
  `Cost_Center_Reference_ID_Type` TEXT,
  `Custom_Organization_01_Reference_ID` TEXT,
  `Custom_Organization_01_Reference_ID_Type` TEXT,
  `Custom_Organization_02_Reference_ID` TEXT,
  `Custom_Organization_02_Reference_ID_Type` TEXT,
  `Custom_Organization_03_Reference_ID` TEXT,
  `Custom_Organization_03_Reference_ID_Type` TEXT,
  `Custom_Organization_04_Reference_ID` TEXT,
  `Custom_Organization_04_Reference_ID_Type` TEXT,
  `Custom_Organization_05_Reference_ID` TEXT,
  `Custom_Organization_05_Reference_ID_Type` TEXT,
  `Custom_Organization_06_Reference_ID` TEXT,
  `Custom_Organization_06_Reference_ID_Type` TEXT,
  `Custom_Organization_07_Reference_ID` TEXT,
  `Custom_Organization_07_Reference_ID_Type` TEXT,
  `Custom_Organization_08_Reference_ID` TEXT,
  `Custom_Organization_08_Reference_ID_Type` TEXT,
  `Custom_Organization_09_Reference_ID` TEXT,
  `Custom_Organization_09_Reference_ID_Type` TEXT,
  `Custom_Organization_10_Reference_ID` TEXT,
  `Custom_Organization_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_01_Reference_ID` TEXT,
  `Custom_Worktag_01_Reference_ID_Type` TEXT,
  `Custom_Worktag_02_Reference_ID` TEXT,
  `Custom_Worktag_02_Reference_ID_Type` TEXT,
  `Custom_Worktag_03_Reference_ID` TEXT,
  `Custom_Worktag_03_Reference_ID_Type` TEXT,
  `Custom_Worktag_04_Reference_ID` TEXT,
  `Custom_Worktag_04_Reference_ID_Type` TEXT,
  `Custom_Worktag_05_Reference_ID` TEXT,
  `Custom_Worktag_05_Reference_ID_Type` TEXT,
  `Custom_Worktag_06_Reference_ID` TEXT,
  `Custom_Worktag_06_Reference_ID_Type` TEXT,
  `Custom_Worktag_07_Reference_ID` TEXT,
  `Custom_Worktag_07_Reference_ID_Type` TEXT,
  `Custom_Worktag_08_Reference_ID` TEXT,
  `Custom_Worktag_08_Reference_ID_Type` TEXT,
  `Custom_Worktag_09_Reference_ID` TEXT,
  `Custom_Worktag_09_Reference_ID_Type` TEXT,
  `Custom_Worktag_10_Reference_ID` TEXT,
  `Custom_Worktag_10_Reference_ID_Type` TEXT,
  `Custom_Worktag_11_Reference_ID` TEXT,
  `Custom_Worktag_11_Reference_ID_Type` TEXT,
  `Custom_Worktag_12_Reference_ID` TEXT,
  `Custom_Worktag_12_Reference_ID_Type` TEXT,
  `Custom_Worktag_13_Reference_ID` TEXT,
  `Custom_Worktag_13_Reference_ID_Type` TEXT,
  `Custom_Worktag_14_Reference_ID` TEXT,
  `Custom_Worktag_14_Reference_ID_Type` TEXT,
  `Custom_Worktag_15_Reference_ID` TEXT,
  `Custom_Worktag_15_Reference_ID_Type` TEXT,
  `Fund_Reference_ID` TEXT,
  `Fund_Reference_ID_Type` TEXT,
  `Gift_Reference_ID` TEXT,
  `Gift_Reference_ID_Type` TEXT,
  `Grant_Reference_ID` TEXT,
  `Grant_Reference_ID_Type` TEXT,
  `Job_Profile_Reference_ID` TEXT,
  `Job_Profile_Reference_ID_Type` TEXT,
  `Location_Reference_ID` TEXT,
  `Location_Reference_ID_Type` TEXT,
  `Program_Reference_ID` TEXT,
  `Program_Reference_ID_Type` TEXT,
  `Region_Reference_ID` TEXT,
  `Region_Reference_ID_Type` TEXT,
  `Project_Reference_ID` TEXT,
  `Project_Reference_ID_Type` TEXT,
  `Project_Task_Reference_ID` TEXT,
  `Project_Task_Reference_ID_Type` TEXT,
  `Comment` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Absence_Input_DCDD Section ***/


/*** Start of Put_Carryover_Override_DCDD Section created from https://app.smartsheet.com/sheets/6J4vf36cj684RQVGq45j8xX888j6R8PMf3745Wm1?view=grid ***/

DROP TABLE IF EXISTS `src_put_carryover_override`;
CREATE TABLE `src_put_carryover_override`(
  `Carryover_Expiration_Limit_Override_Reference_ID` TEXT,
  `Carryover_Expiration_Limit_Override_Reference_ID_Type` TEXT,
  `Carryover_Override_Data_ID` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Absence_Plan_Reference_ID` TEXT,
  `Absence_Plan_Reference_ID_Type` TEXT,
  `Carryover_Date` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Carryover_Override_Amount` TEXT,
  `Carryover_Expiration_Date` TEXT,
  `Carryover_Override_Data_Comments` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Carryover_Override_DCDD Section ***/


/*** Start of Put_Override_Balance_DCDD Section created from https://app.smartsheet.com/sheets/hrXvMcwXxxfrxPM6rqpF24F5rJvC6P8cfwjjG2J1?view=grid ***/

DROP TABLE IF EXISTS `src_put_override_balance`;
CREATE TABLE `src_put_override_balance`(
  `Override_Balance_Reference_ID` TEXT,
  `Override_Balance_Reference_ID_Type` TEXT,
  `Override_Balance_Data_ID` TEXT,
  `Batch_ID` TEXT,
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `Time_Off_Plan_Reference_ID` TEXT,
  `Time_Off_Plan_Reference_ID_Type` TEXT,
  `Override_Balance_Date` TEXT,
  `Override_Balance_Units` TEXT,
  `Carryover_Date` TEXT,
  `Carryover_Expiration_Date` TEXT,
  `Carryover_Override_Balance_Units` TEXT,
  `Override_Balance_Data_Comments` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Override_Balance_DCDD Section ***/


/*** Start of Put_Period_Schedule_DCDD Section created from https://app.smartsheet.com/sheets/xrH2J2v58M4GJXfw7HgwGmWCQmqvcfg9pp8jwpX1?view=grid ***/

DROP TABLE IF EXISTS `src_put_period_schedule`;
CREATE TABLE `src_put_period_schedule`(
  `Add_Only` TEXT,
  `Period_Schedule_Reference_ID` TEXT,
  `Period_Schedule_Reference_ID_Type` TEXT,
  `Period_Schedule_ID` TEXT,
  `Period_Schedule_Name` TEXT,
  `Frequency_Reference_ID` TEXT,
  `Frequency_Reference_ID_Type` TEXT,
  `Regular_Pay_Day_Reference_ID` TEXT,
  `Regular_Pay_Day_Reference_ID_Type` TEXT,
  `Payment_Date_Auto_Adjust_Saturday` TEXT,
  `Payment_Date_Auto_Adjust_Sunday` TEXT,
  `Payment_Date_Offset_Days_Default` TEXT,
  `Pay_On_Demand_Payment_Date_Default_Offset` TEXT,
  `Pay_On_Demand_Payment_Date_Auto_Adjust_Saturday` TEXT,
  `Pay_On_Demand_Payment_Date_Auto_Adjust_Sunday` TEXT,
  `Pay_On_Demand_Days_After_Period_Start_Date_to_Open_Requests` TEXT,
  `Pay_On_Demand_Days_From_Period_End_Date_to_Close_Requests` TEXT,
  `Allow_Timesheet_Changes` TEXT,
  `Payroll_Period_Schedule_Reference_ID` TEXT,
  `Payroll_Period_Schedule_Reference_ID_Type` TEXT,
  `Enable_Auto_Calc_Period` TEXT,
  `Default_Number_of_Days_After_Period_Start_Date_for_Auto_Calc` TEXT,
  `Default_Time_to_Process_Reference_ID` TEXT,
  `Default_Time_to_Process_Reference_ID_Type` TEXT,
  `Time_Zone_Reference_ID` TEXT,
  `Time_Zone_Reference_ID_Type` TEXT,
  `Enable_Automatic_Stop_Period` TEXT,
  `Default_Number_of_Days_Before_Period_Payment_Date_for_Auto_Stop` TEXT,
  `Default_Time_for_Auto_Stop_Reference_ID` TEXT,
  `Default_Time_for_Auto_Stop_Reference_ID_Type` TEXT,
  `Time_Zone_for_Auto_Stop_Reference_ID` TEXT,
  `Time_Zone_for_Auto_Stop_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_put_period_schedule_details`;
CREATE TABLE `src_put_period_schedule_details`(
  `Period_Schedule_ID` TEXT,
  `Usage_Reference_ID` TEXT,
  `Usage_Reference_ID_Type` TEXT,
  `Time_Tracking_Eligibility_Rule_Reference_ID` TEXT,
  `Time_Tracking_Eligibility_Rule_Reference_ID_Type` TEXT,
  `Period_Start_Date` TEXT,
  `Period_End_Date` TEXT,
  `Payroll_Payment_Date` TEXT,
  `Accounting_Date_Override` TEXT,
  `Payroll_GL_Accruals` TEXT,
  `Days_to_Accrue` TEXT,
  `Days_in_Basis` TEXT,
  `Accrual_Date` TEXT,
  `Accrual_Reversal_Date` TEXT,
  `Open_Time_Entry` TEXT,
  `Lock_Time_Entry` TEXT,
  `Unlock_for_Adjustments` TEXT,
  `Close_Time_Entry` TEXT,
  `Payroll_Period_Reference_ID` TEXT,
  `Payroll_Period_Reference_ID_Type` TEXT,
  `Pay_On_Demand_Open_Requests` TEXT,
  `Pay_On_Demand_Close_Requests` TEXT,
  `Country_Reference_ID` TEXT,
  `Country_Reference_ID_Type` TEXT,
  `Payroll_Settlement_Valuation_Date` TEXT,
  `Period_ID` TEXT,
  `Auto_Calc_Date` TEXT,
  `Auto_Calc_Time_Reference_ID` TEXT,
  `Auto_Calc_Time_Reference_ID_Type` TEXT,
  `Automatic_Stop_Date` TEXT,
  `Automatic_Stop_Time_Reference_ID` TEXT,
  `Automatic_Stop_Time_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Put_Period_Schedule_DCDD Section ***/


/*** Start of Request_Leave_of_Absence_DCDD Section created from https://app.smartsheet.com/sheets/H3Gf8GFFqjFrGC5CPhH9hm9PMwFR3c4MVrR7V8J1?view=grid ***/

DROP TABLE IF EXISTS `src_request_leave_of_absence`;
CREATE TABLE `src_request_leave_of_absence`(
  `Request_Leave_of_Absence_Worker_Ref_ID` TEXT,
  `Request_Leave_of_Absence_Worker_Ref_ID_Type` TEXT,
  `Request_Leave_of_Absence_ID` TEXT,
  `Correction` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID_Type` TEXT,
  `Leave_Reason_Reference_ID` TEXT,
  `Leave_Reason_Reference_ID_Type` TEXT,
  `Position_Reference_ID` TEXT,
  `Position_Reference_ID_Type` TEXT,
  `First_Day_of_Leave` TEXT,
  `Last_Day_of_Work` TEXT,
  `Estimated_Last_Day_of_Leave` TEXT,
  `Links_Back_to_Prior_Event_Reference_ID` TEXT,
  `Links_Back_to_Prior_Event_Reference_ID_Type` TEXT,
  `Dependent_Reference_ID` TEXT,
  `Dependent_Reference_ID_Type` TEXT,
  `Last_Date_for_Which_Paid` TEXT,
  `Expected_Due_Date` TEXT,
  `Child_s_Birth_Date` TEXT,
  `Stillbirth_Baby_Deceased` TEXT,
  `Child_Disability_Indicator` TEXT,
  `Date_Baby_Arrived_Home_From_Hospital` TEXT,
  `Adoption_Placement_Date` TEXT,
  `Adoption_Notification_Date` TEXT,
  `Date_Child_Entered_Country` TEXT,
  `Multiple_Child_Indicator` TEXT,
  `Number_of_Babies_Adopted_Children` TEXT,
  `Number_of_Previous_Births` TEXT,
  `Number_of_Previous_Maternity_Leaves` TEXT,
  `Number_of_Child_Dependents` TEXT,
  `Single_Parent_Indicator` TEXT,
  `Age_of_Dependent` TEXT,
  `Work_Related` TEXT,
  `Stop_Payment_Date` TEXT,
  `Social_Security_Disability_Code` TEXT,
  `Location_During_Leave` TEXT,
  `Case_Number` TEXT,
  `Caesarean_Section_Birth` TEXT,
  `Leave_Percentage` TEXT,
  `Week_of_Confinement` TEXT,
  `Leave_Entitlement_Override` TEXT,
  `Date_of_Recall` TEXT,
  `Child_s_Date_of_Death` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_request_leave_of_absence_cobra`;
CREATE TABLE `src_request_leave_of_absence_cobra`(
  `Request_Leave_of_Absence_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `COBRA_Eligible` TEXT,
  `Review_COBRA_Eligibility_Data_Reason_Reference_ID` TEXT,
  `Review_COBRA_Eligibility_Data_Reason_Reference_ID_Type` TEXT,
  `COBRA_Eligible_Date` TEXT,
  `Qualifying_Event_Date` TEXT,
  `Coverage_End_Date` TEXT,
  `Participant_Reference_ID` TEXT,
  `Participant_Reference_ID_Type` TEXT,
  `Benefit_Plan_Reference_ID` TEXT,
  `Benefit_Plan_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_request_leave_of_absence_costing`;
CREATE TABLE `src_request_leave_of_absence_costing`(
  `Request_Leave_of_Absence_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `Assign_Costing_Allocation_Discard_On_Exit_Validation_Error` TEXT,
  `Assign_Costing_Allocation_Comment` TEXT,
  `Assign_Costing_Allocation_Worker_Reference_ID` TEXT,
  `Assign_Costing_Allocation_Worker_Reference_ID_Type` TEXT,
  `Assign_Costing_Allocation_File_Name` TEXT,
  `Assign_Costing_Allocation_Event_Attachment_Description` TEXT,
  `Assign_Costing_Allocation_Event_Attachment_Category_Ref_ID` TEXT,
  `Assign_Costing_Allocation_Event_Attachment_Category_Ref_ID_Type` TEXT,
  `Assign_Costing_Allocation_File` TEXT,
  `Assign_Costing_Allocation_Content_Type` TEXT,
  `Assign_Costing_Allocation_Auto_Complete` TEXT,
  `Assign_Costing_Allocation_Skip` TEXT,
  `Delete` TEXT,
  `Costing_Override_ID_Update_Key` TEXT,
  `Start_Date_Update_Key` TEXT,
  `Costing_Override_ID` TEXT,
  `Start_Date` TEXT,
  `End_Date` TEXT,
  `Order` TEXT,
  `Default_from_Organization_Assignment` TEXT,
  `Costing_Override_Company_Reference_ID` TEXT,
  `Costing_Override_Company_Reference_ID_Type` TEXT,
  `Costing_Override_Worktag_Reference_ID` TEXT,
  `Costing_Override_Worktag_Reference_ID_Type` TEXT,
  `Costing_Override_Worktag_Reference_ID_Parent_ID` TEXT,
  `Costing_Override_Worktag_Reference_ID_Parent_Type` TEXT,
  `Distribution_Percent` TEXT,
  `SOC_Order` TEXT,
  `SOC_Default_from_Organization_Assignment` TEXT,
  `SOC_Costing_Override_Company_Reference_ID` TEXT,
  `SOC_Costing_Override_Company_Reference_ID_Type` TEXT,
  `SOC_Override_Worktag_Reference_ID` TEXT,
  `SOC_Override_Worktag_Reference_ID_Type` TEXT,
  `SOC_Override_Worktag_Reference_ID_Parent_ID` TEXT,
  `SOC_Override_Worktag_Reference_ID_Parent_Type` TEXT,
  `SOC_Distribution_Percent` TEXT,
  `Costing_Allocation_Level_Reference_ID` TEXT,
  `Costing_Allocation_Level_Reference_ID_Type` TEXT,
  `Costing_Allocation_Earning_Reference_ID` TEXT,
  `Costing_Allocation_Earning_Reference_ID_Type` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_request_leave_of_absence_prop_comp`;
CREATE TABLE `src_request_leave_of_absence_prop_comp`(
  `Request_Leave_of_Absence_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `Position_Element_for_Compensation_Transaction_Reference_ID` TEXT,
  `Position_Element_for_Compensation_Transaction_Reference_ID_Type` TEXT,
  `Propose_Compensation_for_Leave_of_Absence_Data_Reason_Ref_ID` TEXT,
  `Propose_Compensation_for_Leave_of_Absence_Dat_Reason_Ref_ID_Type` TEXT,
  `Initialize_Using_Defaulting_Logic` TEXT,
  `Employee_Visibility_Date` TEXT,
  `Primary_Compensation_Basis` TEXT,
  `Compensation_Package_Reference_ID` TEXT,
  `Compensation_Package_Reference_ID_Type` TEXT,
  `Compensation_Grade_Reference_ID` TEXT,
  `Compensation_Grade_Reference_ID_Type` TEXT,
  `Compensation_Grade_Profile_Reference_ID` TEXT,
  `Compensation_Grade_Profile_Reference_ID_Type` TEXT,
  `Compensation_Step_Reference_ID` TEXT,
  `Compensation_Step_Reference_ID_Type` TEXT,
  `Progression_Start_Date` TEXT,
  `Pay_Replace` TEXT,
  `Pay_Plan_Reference_ID` TEXT,
  `Pay_Plan_Reference_ID_Type` TEXT,
  `Pay_Plan_Sub_Data_Amount` TEXT,
  `Pay_Currency_Reference_ID` TEXT,
  `Pay_Currency_Reference_ID_Type` TEXT,
  `Pay_Frequency_Reference_ID` TEXT,
  `Pay_Frequency_Reference_ID_Type` TEXT,
  `Pay_Plan_Sub_Data_Expected_End_Date` TEXT,
  `Pay_Actual_End_Date` TEXT,
  `Unit_Salary_Replace` TEXT,
  `Unit_Salary_Plan_Reference_ID` TEXT,
  `Unit_Salary_Plan_Reference_ID_Type` TEXT,
  `Unit_Salary_Plan_Sub_Data_Per_Unit_Amount` TEXT,
  `Unit_Salary_Currency_Reference_ID` TEXT,
  `Unit_Salary_Currency_Reference_ID_Type` TEXT,
  `Default_Units` TEXT,
  `Unit_Salary_Frequency_Reference_ID` TEXT,
  `Unit_Salary_Frequency_Reference_ID_Type` TEXT,
  `Unit_Salary_Actual_End_Date` TEXT,
  `Allowance_Replace` TEXT,
  `Allowance_Plan_Reference_ID` TEXT,
  `Allowance_Plan_Reference_ID_Type` TEXT,
  `Allowance_Manage_by_Compensation_Basis_Override_Amount` TEXT,
  `Allowance_Currency_Reference_ID` TEXT,
  `Allowance_Currency_Reference_ID_Type` TEXT,
  `Allowance_Frequency_Reference_ID` TEXT,
  `Allowance_Frequency_Reference_ID_Type` TEXT,
  `Allowance_Plan_Sub_Data_Expected_End_Date` TEXT,
  `Allowance_Plan_Sub_Data_Reimbursement_Start_Date` TEXT,
  `Allowance_Actual_End_Date` TEXT,
  `Allowance_Fixed_for_Manage_by_Basis_Total` TEXT,
  `Percent` TEXT,
  `Allowance_Plan_Sub_Data_Amount` TEXT,
  `Unit_Allowance_Replace` TEXT,
  `Unit_Allowance_Plan_Reference_ID` TEXT,
  `Unit_Allowance_Plan_Reference_ID_Type` TEXT,
  `Number_of_Units` TEXT,
  `Unit_Allowance_Frequency_Reference_ID` TEXT,
  `Unit_Allowance_Frequency_Reference_ID_Type` TEXT,
  `Unit_Allowance_Plan_Sub_Data_Per_Unit_Amount` TEXT,
  `Unit_Allowance_Currency_Reference_ID` TEXT,
  `Unit_Allowance_Currency_Reference_ID_Type` TEXT,
  `Unit_Allowance_Plan_Sub_Data_Reimbursement_Start_Date` TEXT,
  `Unit_Allowance_Actual_End_Date` TEXT,
  `Unit_Allowance_Fixed_for_Manage_by_Basis_Total` TEXT,
  `Bonus_Replace` TEXT,
  `Bonus_Plan_Reference_ID` TEXT,
  `Bonus_Plan_Reference_ID_Type` TEXT,
  `Bonus_Manage_by_Compensation_Basis_Override_Amount` TEXT,
  `Bonus_Plan_Sub_Data_Guaranteed_Minimum` TEXT,
  `Percent_Assigned` TEXT,
  `Bonus_Actual_End_Date` TEXT,
  `Bonus_Fixed_for_Manage_by_Basis_Total` TEXT,
  `Bonus_Individual_Target_Amount` TEXT,
  `Bonus_Individual_Target_Percent` TEXT,
  `Merit_Replace` TEXT,
  `Merit_Plan_Reference_ID` TEXT,
  `Merit_Plan_Reference_ID_Type` TEXT,
  `Merit_Individual_Target_Amount` TEXT,
  `Merit_Individual_Target_Percent` TEXT,
  `Merit_Plan_Sub_Data_Guaranteed_Minimum` TEXT,
  `Merit_Actual_End_Date` TEXT,
  `Commission_Replace` TEXT,
  `Commission_Plan_Reference_ID` TEXT,
  `Commission_Plan_Reference_ID_Type` TEXT,
  `Target_Amount` TEXT,
  `Commission_Currency_Reference_ID` TEXT,
  `Commission_Currency_Reference_ID_Type` TEXT,
  `Commission_Frequency_Reference_ID` TEXT,
  `Commission_Frequency_Reference_ID_Type` TEXT,
  `Draw_Amount` TEXT,
  `Draw_Frequency_Reference_ID` TEXT,
  `Draw_Frequency_Reference_ID_Type` TEXT,
  `Draw_Duration` TEXT,
  `Recoverable` TEXT,
  `Commission_Actual_End_Date` TEXT,
  `Commission_Fixed_for_Manage_by_Basis_Total` TEXT,
  `Stock_Replace` TEXT,
  `Stock_Plan_Reference_ID` TEXT,
  `Stock_Plan_Reference_ID_Type` TEXT,
  `Stock_Manage_by_Compensation_Basis_Override_Amount` TEXT,
  `Stock_Currency_Reference_ID` TEXT,
  `Stock_Currency_Reference_ID_Type` TEXT,
  `Stock_Actual_End_Date` TEXT,
  `Stock_Fixed_for_Manage_by_Basis_Total` TEXT,
  `Individual_Target_Shares` TEXT,
  `Stock_Individual_Target_Percent` TEXT,
  `Stock_Individual_Target_Amount` TEXT,
  `Period_Salary_Replace` TEXT,
  `Period_Salary_Plan_Reference_ID` TEXT,
  `Period_Salary_Plan_Reference_ID_Type` TEXT,
  `Compensation_Period_Reference_ID` TEXT,
  `Compensation_Period_Reference_ID_Type` TEXT,
  `Period_Salary_Manage_by_Compensation_Basis_Override_Amount` TEXT,
  `Period_Salary_Currency_Reference_ID` TEXT,
  `Period_Salary_Currency_Reference_ID_Type` TEXT,
  `Compensation_Period_Multiplier` TEXT,
  `Period_Salary_Frequency_Reference_ID` TEXT,
  `Period_Salary_Frequency_Reference_ID_Type` TEXT,
  `Period_Salary_Actual_End_Date` TEXT,
  `Calculated_Replace` TEXT,
  `Calculated_Plan_Reference_ID` TEXT,
  `Calculated_Plan_Reference_ID_Type` TEXT,
  `Amount_Override` TEXT,
  `Calculated_Currency_Reference_ID` TEXT,
  `Calculated_Currency_Reference_ID_Type` TEXT,
  `Calculated_Frequency_Reference_ID` TEXT,
  `Calculated_Frequency_Reference_ID_Type` TEXT,
  `Calculated_Actual_End_Date` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';


DROP TABLE IF EXISTS `src_request_leave_of_absence_roles`;
CREATE TABLE `src_request_leave_of_absence_roles`(
  `Request_Leave_of_Absence_ID` TEXT,
  `Leave_of_Absence_Type_Reference_ID` TEXT,
  `Role_Assignment_Reference_ID` TEXT,
  `Role_Assignment_Reference_ID_Type` TEXT,
  `Role_Assignment_Data_Role_Assigner_Reference_ID` TEXT,
  `Role_Assignment_Data_Role_Assigner_Reference_ID_Type` TEXT,
  `Role_Assignment_Data_Role_Assigne_Role_Assigner_Ref_ID_Parent_ID` TEXT,
  `Role_Assignment_Data_Role_Assig_Role_Assigner_Ref_ID_Parent_Type` TEXT,
  `Organization_Role_Reference_ID` TEXT,
  `Organization_Role_Reference_ID_Type` TEXT,
  `Role_Assignment_Data_Role_Assignee_Reference_ID` TEXT,
  `Role_Assignment_Data_Role_Assignee_Reference_ID_Type` TEXT,
  `Single_Assignment_Manager_Reference_ID` TEXT,
  `Single_Assignment_Manager_Reference_ID_Type` TEXT,
  `Assign_Roles_Discard_On_Exit_Validation_Error` TEXT,
  `Assign_Roles_Comment` TEXT,
  `Assign_Roles_Worker_Reference_ID` TEXT,
  `Assign_Roles_Worker_Reference_ID_Type` TEXT,
  `Assign_Roles_File_Name` TEXT,
  `Assign_Roles_Event_Attachment_Description` TEXT,
  `Assign_Roles_Event_Attachment_Category_Reference_ID` TEXT,
  `Assign_Roles_Event_Attachment_Category_Reference_ID_Type` TEXT,
  `Assign_Roles_File` TEXT,
  `Assign_Roles_Content_Type` TEXT,
  `Assign_Roles_Auto_Complete` TEXT,
  `Assign_Roles_Skip` TEXT,
  `Remove_All_Role_Assignments_for_Event_Target_Assignee` TEXT,
  `Assign_Roles_Role_Assignment_Data_Role_Assigner_Reference_ID` TEXT,
  `Assign_Roles_Role_Assignment_Data_Role_Assigner_Ref_ID_Type` TEXT,
  `Assign_Roles_Role_Assignment_Data_Role_Assigner_Ref_ID_Parent_ID` TEXT,
  `Assign_Roles_Role_Assignment_Da_Role_Assigner_Ref_ID_Parent_Type` TEXT,
  `Assignable_Role_Reference_ID` TEXT,
  `Assignable_Role_Reference_ID_Type` TEXT,
  `Remove_Existing_Assignees_for_Assignable_Role_on_Role_Assigner` TEXT,
  `Update_Later_Dated_Assignments` TEXT,
  `Assignees_to_Add_Reference_ID` TEXT,
  `Assignees_to_Add_Reference_ID_Type` TEXT,
  `Assignees_to_Remove_Reference_ID` TEXT,
  `Assignees_to_Remove_Reference_ID_Type` TEXT,
  `Supervisory_Organization_Single_Assignment_Manager_Reference_ID` TEXT,
  `Supervisory_Organization_Single_Assignment_Manager_Ref_ID_Type` TEXT,
  `Remove_Supervisory_Organization_Single_Assignment_Manager` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Request_Leave_of_Absence_DCDD Section ***/


/*** Start of Request_Return_from_Leave_of_Absence_DCDD Section created from https://app.smartsheet.com/sheets/hfFM3GPpCwHJqP3VHWXhH7XqgXvPMfCMw7QVv4V1?view=grid ***/

DROP TABLE IF EXISTS `src_request_return_from_leave_of_absence`;
CREATE TABLE `src_request_return_from_leave_of_absence`(
  `Worker_Reference_ID` TEXT,
  `Worker_Reference_ID_Type` TEXT,
  `First_Day_Back_at_Work` TEXT,
  `Request_Leave_of_Absence_Reference_ID` TEXT,
  `Request_Leave_of_Absence_Reference_ID_Type` TEXT,
  `Correction_Flag` TEXT,
  `Actual_Last_Day_of_Leave` TEXT
) ENGINE=InnoDB ENCRYPTION='Y' COMMENT '';

/*** End of Request_Return_from_Leave_of_Absence_DCDD Section ***/


/* NO LONGER SETTING UP AS AN SP
SET autocommit=1;
END STAGING;
*/